### PR TITLE
Style changes

### PR DESCRIPTION
**Pull request by atmyers**
1. Does "using namespace amrex" in several functions instead of using `amrex::` a lot.
2. Add spaces to function declarations / definitions to make searching easier.

### CODE REVIEW

**Comment by dpgrote** [comment]
Is this the agreed upon style for WarpX, not using the amrex:: prefix? I've been doing the opposite, adding the amrex:: in all of my code. I can do it either way, but my preference is to always use the prefix since this makes it clear where the names are coming from and avoids any naming confusion.

**Comment by atmyers** [comment]
I don't know that it's agreed upon. Back in the olden days of WarpX, we would usually do `using namespace amrex` at file scope in cpp files, but not in header files to avoid polluting the global namespace. But most of the function implementations were in cpp files. Now that we have a lot of templates / inlining, many of the implementations are in header files, so (I think) we starting doing a lot of explicit `amrex::`. But we could also have the using statement at function scope, as in this PR. We don't currently have any consistent guideline about that, though. In `Source/Particles/Deposition/CurrentDeposition.H`, one of the functions was doing this and the other wasn't.  

My opinion is that for things like `Real`, it makes too much clutter to have the `amrex::` all the time. For functions like "exp" or "max", its better to use the explicit namespace because there is more likely to be some ambiguity with the standard library functions.

**Comment by MaxThevenet** [comment]
Let us discuss this at the next developers meeting. It is on the program.

**Comment by atmyers** [comment]
Since there is currently no official guideline about this, I'll just close this for now and reissue the device gather PR without the style changes.

**Pull request closed without merging**
