### PR TITLE
Remove costs full diagnostic

### PR DESCRIPTION
**Pull request by mrowan137**
This pull request removes the full costs diagnostic, in preparation for transitioning the timer-based costs to a vector of (pointer to) vectors.  Diagnostics for costs is not removed, as a reduced diagnostic is proposed in PR #790 .

### CODE REVIEW

**Comment by mrowan137** [comment]
The `PlasmaMirror` test fails because `warpx.plot_costs` is now an unused input variable.

**Comment by mrowan137** [comment]
> Looks good, thanks! Could you fix merge conflicts?

Thanks!  Merge conflict is fixed, so this should be good to go.

**Comment by MaxThevenet** [comment]
Could you `git grep plot_costs`? I think you left some occurrences.

**Comment by mrowan137** [comment]
> Could you `git grep plot_costs`? I think you left some occurrences.

I found one, it is now removed.

**Pull request merged**
