### PR TITLE
Docs: Ascent 0.8.0 on Summit

### PR DESCRIPTION
**Pull request by ax3l**
Update the Ascent installation location to use @cyrush's new install for us.

## Configure & Build
```console
cmake -S . -B build_summit -DWarpX_COMPUTE=CUDA -DWarpX_ASCENT=ON
cmake --build build_summit -j 6
```
- [x] configure: :heavy_check_mark:
- [x] build: :heavy_check_mark:
## Run
```
2: 0: Initializing CUDA...
2: 0: CUDA initialized with 1 GPU per MPI rank; 24 GPU(s) used in total
2: 0: MPI initialized with 24 MPI processes
2: 0: MPI initialized with thread support level 3
2: 0: AMReX (22.04-24-gf2d7f67848de) initialized
2: 0: WarpX (22.04-27-gf316aa4e8c19)
2: 0: PICSAR (e7ef03b852b8)
2: 0: Level 0: dt = 1.564936033e-16 ; dx = 9.375e-08 ; dy = 9.375e-08 ; dz = 6.640625e-08
2: 0: 
2: 0: Grids Summary:
2: 0:   Level 0   200 grids  419430400 cells  100 % of domain
2: 0:             smallest grid: 128 x 128 x 128  biggest grid: 128 x 128 x 128
2: 0: 
2: 0: -------------------------------------------------------------------------------
2: 0: --------------------------- MAIN EM PIC PARAMETERS ----------------------------
2: 0: -------------------------------------------------------------------------------
2: 0: Geometry:             | 3D (XYZ)
2: 0: Operation mode:       | Electromagnetic
2: 0:                       | - vacuum
2: 0: -------------------------------------------------------------------------------
2: 0: Current Deposition:   | Esirkepov 
2: 0: Particle Pusher:      | Boris 
2: 0: Charge Deposition:    | standard 
2: 0: Field Gathering:      | energy-conserving 
2: 0: Particle Shape Factor:| 3
2: 0: -------------------------------------------------------------------------------
2: 0: Maxwell Solver:       | Yee 
2: 0: -------------------------------------------------------------------------------
2: 0: Moving window:        |    ON  
2: 0:                       |  - moving_window_dir = z 
2: 0:                       |  - moving_window_v = 299792458
2: 0: ------------------------------------------------------------------------------- 
2: 0: ey/contour/pc/p0 pseudocolor plot yielded no data, i.e., no cells remain
2: 0: STEP 1 starts ...
2: 0: 
2: 0: 
2: 0: **** WARNINGS ******************************************************************
2: 0: * GLOBAL warning list  after  [ FIRST STEP ]
2: 0: *
2: 0: * No recorded warnings.
2: 0: ********************************************************************************
2: 0: 
2: 0: STEP 1 ends. TIME = 1.564936033e-16 DT = 1.564936033e-16
2: 0: Evolve time = 0.139503986 s; This step = 0.139503986 s; Avg. per step = 0.139503986 s
2: 0: 
2: 0: STEP 2 starts ...
...
2: 0: ----------------------------------------------------------------------------------------------------------
2: 0: Name                                                       NCalls  Incl. Min  Incl. Avg  Incl. Max   Max %
2: 0: ----------------------------------------------------------------------------------------------------------
2: 0: main()                                                          1      270.9      270.9      270.9 100.00%
2: 0: REG::WarpX::Evolve()                                            1      267.2      267.2      267.2  98.63%
2: 0: WarpX::Evolve()                                                 1      267.2      267.2      267.2  98.63%
2: 0: WarpX::Evolve::step                                          1000      266.9      266.9      267.1  98.59%
2: 0: Diagnostics::FilterComputePackFlush()                        1002      122.2      122.4      125.8  46.44%
2: 0: FlushFormatAscent::WriteToFile()                               21      119.7        120      123.6  45.62%
2: 0: FlushFormatAscent::WriteToFile::execute                        21      118.3      118.5      122.1  45.06%
2: 0: WarpX::OneStep_nosub()                                       1000      93.81      94.36         96  35.43%
2: 0: WarpX::SyncCurrent()                                         1000      38.41      57.57      68.13  25.15%
2: 0: FabArray::ParallelCopy()                                     3022      30.44      49.17       59.8  22.07%
2: 0: FabArray::ParallelCopy_finish()                              3022      24.52      43.15      53.82  19.87%
2: 0: WarpXCommUtil::FillBoundary                                 16399      43.66       47.5      50.67  18.70%
2: 0: FabArray::FillBoundary()                                    16399      43.64      47.48      50.65  18.70%
2: 0: FillBoundary_finish()                                       22399      34.56      40.43      46.13  17.03%
2: 0: PhysicalParticleContainer::Evolve()                          1000      1.167       11.4      30.94  11.42%
...
```
- [x] :heavy_check_mark:

### CODE REVIEW

**Comment by ax3l** [comment]
@cyrush when configuring WarpX with the libs avove, I get a conflicting HDF5 in:
```
CMake Warning at CMakeLists.txt:156 (add_executable):
  Cannot generate a safe runtime search path for target app because files in
  some directories may conflict with libraries in implicit directories:

    runtime library [libhdf5.so.103] in /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/hdf5-1.10.7-erpzjzv6dakrblzacmwiuyrgg54wawqa/lib may be hidden by files in:
      /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/hdf5-1.10.7-4b77lkzgqo6zq6waojy3c24asrm5tu5h/lib
    runtime library [libmpiprofilesupport.so.3] in /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/lib may be hidden by files in:
      /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/xl-16.1.1-10/spectrum-mpi-10.4.0.3-20210112-dzedzfvocsuzkm4jkqe7o64x53yhq7nm/lib
    runtime library [libmpi_ibm.so.3] in /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/lib may be hidden by files in:
      /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/xl-16.1.1-10/spectrum-mpi-10.4.0.3-20210112-dzedzfvocsuzkm4jkqe7o64x53yhq7nm/lib

  Some of these libraries may not be found correctly.
```

Can you use the [module we use for HDF5](https://warpx.readthedocs.io/en/latest/install/hpc/summit.html), from `module load hdf5/1.10.7`, as external provider for your HDF5 build?

**Comment by cyrush** [comment]
This is a bit of a puzzle, we are linked against:

/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/hdf5-1.10.7-4b77lkzgqo6zq6waojy3c24asrm5tu5h/

which corresponds to:

```
module load gcc/9.3.0
module load hdf5/1.10.7
```

In this case we should be looking at the right MPI libs:

```
ldd /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/hdf5-1.10.7-4b77lkzgqo6zq6waojy3c24asrm5tu5h/lib/libhdf5.so 
	linux-vdso64.so.1 (0x00007fffa40c0000)
	libz.so.1 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/zlib-1.2.11-5ylwliurlfdizyqq2h2ujwdvl44ukaef/lib/libz.so.1 (0x00007fffa3b60000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fffa3b10000)
	libm.so.6 => /lib64/power9/libm.so.6 (0x00007fffa39e0000)
	libmpiprofilesupport.so.3 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-2s7kpbzydf6val7k2d3e6cz3zdhtcwlw/lib/libmpiprofilesupport.so.3 (0x00007fffa39b0000)
	libmpi_ibm.so.3 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-2s7kpbzydf6val7k2d3e6cz3zdhtcwlw/lib/libmpi_ibm.so.3 (0x00007fffa37f0000)
	libpthread.so.0 => /lib64/power9/libpthread.so.0 (0x00007fffa37a0000)
	libc.so.6 => /lib64/power9/libc.so.6 (0x00007fffa3590000)
	/lib64/ld64.so.2 (0x00007fffa40e0000)
	librt.so.1 => /lib64/power9/librt.so.1 (0x00007fffa3560000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007fffa3530000)
	libhwloc_ompi.so.15 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-2s7kpbzydf6val7k2d3e6cz3zdhtcwlw/lib/libhwloc_ompi.so.15 (0x00007fffa34a0000)
	libevent_core-2.1.so.6 => /lib64/libevent_core-2.1.so.6 (0x00007fffa3430000)
	libevent_pthreads-2.1.so.6 => /lib64/libevent_pthreads-2.1.so.6 (0x00007fffa3400000)
	libopen-rte.so.3 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-2s7kpbzydf6val7k2d3e6cz3zdhtcwlw/lib/libopen-rte.so.3 (0x00007fffa32e0000)
	libopen-pal.so.3 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-2s7kpbzydf6val7k2d3e6cz3zdhtcwlw/lib/libopen-pal.so.3 (0x00007fffa3180000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007fffa2e10000)
```

But, it appears XL runtime paths for MPI are still some how in the mix. 

I'll dive in and see what is going on.

**Comment by cyrush** [comment]
Some progress: 

Current hdf5 module load resolves to:
`hdf5-1.10.7-erpzjzv6dakrblzacmwiuyrgg54wawqa`

During my builds it resolved to:

`hdf5-1.10.7-4b77lkzgqo6zq6waojy3c24asrm5tu5h`

This is b/c when my spack configs were setup -  That was the valid path, and it has now changed. 

I'll fix this and create a new build. 

But I still want to understand more about why XL is showing up.

**Comment by cyrush** [comment]
@ax3l

I figured out the issue with XL MPI paths sneaking in. 
My spack builds were not cleanly applying the expected modules. I had to add some extra defense against default mpi modules.  A bit of a surprise - perhaps this is because I am using an older spack, but regardless I found a way. 

I will build a new version in the ums location and let you know when it is ready.

**Comment by cyrush** [comment]
I reinstalled the ums install and I believe everything is sorted out for the build to match your modules, here is `ldd` output to capture what hdf5, etc are used:

```
bash-4.4$ ldd bin/warpx
	linux-vdso64.so.1 (0x0000200000050000)
	libmpi_ibm_usempif08.so => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/lib/libmpi_ibm_usempif08.so (0x0000200000070000)
	libmpi_ibm_usempi_ignore_tkr.so => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/lib/libmpi_ibm_usempi_ignore_tkr.so (0x00002000000a0000)
	libmpi_ibm_mpifh.so.3 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/lib/libmpi_ibm_mpifh.so.3 (0x00002000000d0000)
	librt.so.1 => /lib64/power9/librt.so.1 (0x00002000001a0000)
	libhdf5.so.103 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/hdf5-1.10.7-erpzjzv6dakrblzacmwiuyrgg54wawqa/lib/libhdf5.so.103 (0x00002000001d0000)
	libnvToolsExt.so.1 => /sw/summit/cuda/11.3.1/targets/ppc64le-linux/lib/libnvToolsExt.so.1 (0x00002000006a0000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002000006c0000)
	libadios2_cxx11_mpi.so.2 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/adios2-2.7.1-co24zackzpgozynhz4otsmkjnjh3dsah/lib64/libadios2_cxx11_mpi.so.2 (0x00002000006f0000)
	libadios2_cxx11.so.2 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/adios2-2.7.1-co24zackzpgozynhz4otsmkjnjh3dsah/lib64/libadios2_cxx11.so.2 (0x0000200000720000)
	libmpiprofilesupport.so.3 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/lib/libmpiprofilesupport.so.3 (0x00002000008e0000)
	libmpi_ibm.so.3 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/lib/libmpi_ibm.so.3 (0x0000200000910000)
	libpthread.so.0 => /lib64/power9/libpthread.so.0 (0x0000200000ad0000)
	libstdc++.so.6 => /sw/summit/gcc/9.3.0-2/lib64/libstdc++.so.6 (0x0000200000b20000)
	libm.so.6 => /lib64/power9/libm.so.6 (0x0000200000db0000)
	libgcc_s.so.1 => /sw/summit/gcc/9.3.0-2/lib64/libgcc_s.so.1 (0x0000200000ee0000)
	libc.so.6 => /lib64/power9/libc.so.6 (0x0000200000f20000)
	/lib64/ld64.so.2 (0x0000200000000000)
	libopen-rte.so.3 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/lib/libopen-rte.so.3 (0x0000200001130000)
	libopen-pal.so.3 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/lib/libopen-pal.so.3 (0x0000200001250000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00002000013b0000)
	libhwloc_ompi.so.15 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/lib/libhwloc_ompi.so.15 (0x00002000013e0000)
	libevent_core-2.1.so.6 => /lib64/libevent_core-2.1.so.6 (0x0000200001470000)
	libevent_pthreads-2.1.so.6 => /lib64/libevent_pthreads-2.1.so.6 (0x00002000014e0000)
	libz.so.1 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/zlib-1.2.11-mtrlilqrptmy22npaixqqnlkx7xxog4t/lib/libz.so.1 (0x0000200001510000)
	libadios2_core_mpi.so.2 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/adios2-2.7.1-co24zackzpgozynhz4otsmkjnjh3dsah/lib64/../lib64/libadios2_core_mpi.so.2 (0x0000200001550000)
	libadios2_core.so.2 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/adios2-2.7.1-co24zackzpgozynhz4otsmkjnjh3dsah/lib64/../lib64/libadios2_core.so.2 (0x00002000016e0000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x0000200001df0000)
	libadios2_taustubs.so => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/adios2-2.7.1-co24zackzpgozynhz4otsmkjnjh3dsah/lib64/../lib64/../lib64/libadios2_taustubs.so (0x0000200002180000)
	libblosc.so.1 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/c-blosc-1.21.0-gudk3tcyn3yx4tqqmjsxlbmazftvhbve/lib/libblosc.so.1 (0x00002000021b0000)
	libbz2.so.1.0 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/bzip2-1.0.8-vcz235ujehmimlpu27gwschyoqebkvks/lib/libbz2.so.1.0 (0x00002000021e0000)
	libzfp.so.0 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/zfp-0.5.5-26vburu25anpyqvt2hvltlghxjfphnvw/lib64/libzfp.so.0 (0x0000200002220000)
	libSZ.so => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/sz-2.1.12-k6odztibd7wk5f6ufrejuzioixzymkuq/lib64/libSZ.so (0x0000200002280000)
	libpng16.so.16 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/libpng-1.6.37-b3eabpbe7nbq7t3ze4pz5opftpge7m55/lib/libpng16.so.16 (0x0000200002390000)
	libfabric.so.1 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/libfabric-1.13.1-z6jtacev7haqsemzvetrtr6h6k7pz3pr/lib/libfabric.so.1 (0x0000200002400000)
	libadios2_evpath.so => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/adios2-2.7.1-co24zackzpgozynhz4otsmkjnjh3dsah/lib64/../lib64/../lib64/libadios2_evpath.so (0x0000200002510000)
	libadios2_ffs.so.1 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/adios2-2.7.1-co24zackzpgozynhz4otsmkjnjh3dsah/lib64/../lib64/../lib64/libadios2_ffs.so.1 (0x00002000025c0000)
	libadios2_atl.so.2 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/adios2-2.7.1-co24zackzpgozynhz4otsmkjnjh3dsah/lib64/../lib64/../lib64/libadios2_atl.so.2 (0x0000200002660000)
	libzstd.so.1 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/zstd-1.5.0-nyznyntrichkgdzue3lceevqqgvyzcau/lib/libzstd.so.1 (0x0000200002690000)
	liblz4.so.1 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/lz4-1.9.3-qhyu6rexybbh4j76duzr4zwo4lvlclw4/lib/liblz4.so.1 (0x0000200002800000)
	librdmacm.so.1 => /lib64/librdmacm.so.1 (0x0000200002860000)
	libibverbs.so.1 => /lib64/libibverbs.so.1 (0x00002000028a0000)
	libatomic.so.1 => /sw/summit/gcc/9.3.0-3/lib/../lib64/libatomic.so.1 (0x00002000028e0000)
	libadios2_dill.so.2 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/adios2-2.7.1-co24zackzpgozynhz4otsmkjnjh3dsah/lib64/../lib64/../lib64/../lib64/libadios2_dill.so.2 (0x0000200002910000)
	libnl-route-3.so.200 => /lib64/libnl-route-3.so.200 (0x0000200002970000)
	libnl-3.so.200 => /lib64/libnl-3.so.200 (0x0000200002a40000)
	libffi.so.7 => /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/libffi-3.3-cmsfkmxgdmhr6vb2l4fxfxexsvnmcc4s/lib64/libffi.so.7 (0x0000200002a90000)
```

**Comment by ax3l** [comment]
Thank you @cyrush :tada: 

As discussed on Slack:
- [x] Cyrus did a 1 node, 6 GPU test [with our CI example](https://github.com/ECP-WarpX/WarpX/blob/c8e49fb7ee15dd876e6c53eab13a48863d46c073/.github/workflows/insitu.yml#L60-L64)
- [x] I did  the following 4 node test:
[ascent_actions.yaml.txt](https://github.com/ECP-WarpX/WarpX/files/8557574/ascent_actions.yaml.txt) [inputs_3d.txt](https://github.com/ECP-WarpX/WarpX/files/8557576/inputs_3d.txt) [summit_v100.bsub.txt](https://github.com/ECP-WarpX/WarpX/files/8557577/summit_v100.bsub.txt)

ey_contour_pc_1000
ey_volrend_1000
uz_pc_1000

**Pull request merged**
