### PR TITLE
[Do not merge] Single Precision Debugging

### PR DESCRIPTION
**Pull request by Yin-YinjianZhao**
This is PR is for the convenience of debugging a single precision run.
Some tests that have been done will be commented as a reference for future debugging.

### CODE REVIEW

**Comment by Yin-YinjianZhao** [comment]
A typical input file is attached here.
[inputs.txt](https://github.com/ECP-WarpX/WarpX/files/4624972/inputs.txt)

**Comment by Yin-YinjianZhao** [comment]
One can compile with
```
make -j 4 DIM=2
```
for double precision (DP) and with
```
make -j 4 DIM=2 PRECISION=FLOAT USE_SINGLE_PRECISION_PARTICLES=TRUE
```
for single precision (SP).

**Comment by Yin-YinjianZhao** [comment]
Before running, one should make sure OpenMP is turned off. One way is to run `export OMP_NUM_THREADS=1` in the terminal.

**Comment by Yin-YinjianZhao** [comment]
It is found that when using `algo.current_deposition = direct`, SP is correct.
It is wrong when using `algo.current_deposition = esirkepov`.
For example, some Jz and Jy are missing for the SP case before time step 12.
Two gif are made to show the results.
plot_direct
plot_esirkepov

**Comment by Yin-YinjianZhao** [comment]
The above `gif` can be made using a script `plot.py`, and run with `python plot.py`.
(Rename the attached `plot.txt` as `plot.py`)
[plot.txt](https://github.com/ECP-WarpX/WarpX/files/4625027/plot.txt)
Some parameters are needed to be changed before running the script.
After running, there will be many `plot*.pdf` generated.
One can simply use `convert -delay 50 plot*.pdf plot.gif` to convert them into a `gif` file.

**Comment by Yin-YinjianZhao** [comment]
Some printing statements are added in the file `Source/Particles/Deposition/CurrentDeposition.H`.
First, it is found the indices look correct between SP and DP for both direct and esirkepov deposition.
Second, one mystery is that the Jy and Jz values printed are similar, as attached files, but in the diagnostic `gif` files they are different.
[outputs_d_direct.txt](https://github.com/ECP-WarpX/WarpX/files/4625069/outputs_d_direct.txt)
[outputs_d_esirkepov.txt](https://github.com/ECP-WarpX/WarpX/files/4625070/outputs_d_esirkepov.txt)
[outputs_s_direct.txt](https://github.com/ECP-WarpX/WarpX/files/4625072/outputs_s_direct.txt)
[outputs_s_esirkepov.txt](https://github.com/ECP-WarpX/WarpX/files/4625073/outputs_s_esirkepov.txt)

**Comment by Yin-YinjianZhao** [comment]
A uniform plasma test is done in 3D.
The input file is attached, which is modified based on `Examples/Physics_applications/uniform_plasma/inputs_3d`.
[inputs_3d.txt](https://github.com/ECP-WarpX/WarpX/files/4647120/inputs_3d.txt)
The results indicate large error for both direct and esirkepov depositions.
plot_direct
plot_esirkepov

**Comment by Yin-YinjianZhao** [comment]
A plotting comparison is done using both `plotfiles` and a customized way implemented in a branch https://github.com/Yin-YinjianZhao/WarpX/tree/diags_merge.

The input file used is based on `Examples/Physics_applications/laser_acceleration/inputs_3d`.
[inputs_laser.txt](https://github.com/ECP-WarpX/WarpX/files/4653759/inputs_laser.txt)

The plots using `plotfiles` are:
plot

We can see a non-zero Jy after 8 time step in DP, and after 11 time step in SP.

The plots using the customized way are:
plot_d
plot_s

We can see both non-zero Jy after 2 time step in DP and SP.

So, there may be indeed an issue in `plotfiles`? @MaxThevenet 

BTW, the magnitudes (and also shapes) of the two plotting methods are different for some reasons I don't know for now.

**Comment by ax3l** [comment]
Thanks again for sharing this!
@Yin-YinjianZhao @mrowan137 is it okay if I close this PR for now? :)

Superseeded by #1082 #1084

**Pull request closed without merging**
