### PR TITLE
Implemented query and getArrWithParser

### PR DESCRIPTION
**Pull request by dpgrote**
This is something I thought might be useful so I went ahead and implemented it, including updating a CI test to use it.

### CODE REVIEW

**Review by EZoni — COMMENTED** [review]
Thank you for the PR, Dave! It seems to me like a very useful feature!

One quick question:
Is it necessary to have two different functions `getArrWithParser`, with two different interfaces? In other words, would it work if we were to use only the function with the more general interface, to parse both an `AMREX_SPACEDIM`-dimensional array as well as a single value?

```
void
getArrWithParser (const amrex::ParmParse& a_pp, char const * const str, std::vector<amrex::Real>& val,
                  const int start_ix, const int num_val)
```
It seems to me like this function would cover also the special case of one single value parsed, which instead we handle with a separate interface (without `start_ix` and `num_val`).

Would it be just a matter of modifying the calls without `start_ix` and `num_val` by passing two extra arguments (`0` and `1`, if only a single value is expected), or even also by setting default values that cover the single-value case for those two arguments? Or are there other reasons why we want to use two separate functions?

**Comment by dpgrote** [comment]
@EZoni Thanks for reviewing this. Regarding `getArrWithParser`, I added the two versions of it since I was trying to avoid accessing internal defaults values defined in the `amrex::ParmParse` class. In the definition of `getarr`, `ParmParse` uses default values for `start_ix` and `num_val` so that they don't need to be supplied when it is called. Since `getArrWithParser` is short enough, I decided that it was simplest to have two versions of it, with the two different arg lists, rather that use the default values defined in ParmParse. This will make the code more future proof since it avoids a dependency on internal details in the `ParmParse` class that could possibly change.

Note that in the cases where the `start_ix` and `num_val` are not supplied when `getArrWithParser` is called, the number of elements in the array is unknown (not necessarily a single value).

**Comment by EZoni** [comment]
@dpgrote I see, thanks a lot for explaining. I did not have a clear and full picture of this indeed. Looks good to me, then! As soon as it is merged, we can start using this feature more in other input files among our examples. This way people can start getting used to it and using it themselves. It happens often that one needs to re-use a chosen numerical value (say for `xmin`, etc.) for different input parameters in the same input file, and this feature makes it much less error-prone. Thanks again!

**Review by EZoni — APPROVED** [review]

**Comment by dpgrote** [comment]
Thanks @EZoni! Your example of reusing xmin etc is exactly why I decided to implement this.

**Pull request merged**
