### PR TITLE
CI: Build EB

### PR DESCRIPTION
**Pull request by ax3l**
Perform compile tests with EB on.
This should help to ensure single-precision, CUDA, DPC++, HIP and Windows builds work with EB on the long-term.

### To Do

- [x] requires AMReX fix: https://github.com/AMReX-Codes/amrex/pull/2232
- [x] fix gamma implicit casts (HIP build) #2174
- [x] fix warnings in RZ build #2176
- [x] fix CUDA compile #2247

### CODE REVIEW

**Comment by ax3l** [comment]
Uh-oh, ICE-ICE :dancers: in `Intel / oneAPI DPC++ SP`: 

```
Src/EB/AMReX_EB2_3D_C.cpp
dpcpp: error: unable to execute command: Segmentation fault (core dumped)
dpcpp: error: clang frontend command failed due to signal (use -v to see invocation)
Intel(R) oneAPI DPC++/C++ Compiler 2021.3.0 (2021.3.0.20210619)
```

**Comment by ax3l** [comment]
DPC++ ICE probably solved together with the CUDA visibility of lambdas bug-fix from #2247

**Review by lgiacome — APPROVED** [review]
This looks great to me!

**Comment by ax3l** [comment]
Let me rebase one last time, just to make sure that after #1923 / #2164 this still passes: done - fails now :-S

**Comment by ax3l** [comment]
Progress posted on #bounday.

> Can reproduce with GCC single precision builds locally here with a single MPI rank and 1 OMP thread.
Issue resides in FiniteDifferenceSolver::EvolveBCartesian<CartesianCKCAlgorithm>
Segfault in accessing a amrex::FabArray<amrex::FArrayBox>::fabPtr, cannot yet spot which argument...
>
> Maybe the face_areas are not allocated.

**Comment by ax3l** [comment]
The DPC++ build ICE/segfault is back. Will disable for now and triage with Intel in a follow-up PR.
```
[ 50%] Building CXX object _deps/fetchedamrex-build/Src/CMakeFiles/amrex.dir/EB/AMReX_EB2_MultiGFab.cpp.o
cd /home/runner/work/WarpX/WarpX/build_sp/_deps/fetchedamrex-build/Src && /opt/intel/oneapi/compiler/2021.3.0/linux/bin/dpcpp -Damrex_EXPORTS -I/home/runner/work/WarpX/WarpX/build_sp/_deps/fetchedamrex-src/Src/Base -I/home/runner/work/WarpX/WarpX/build_sp/_deps/fetchedamrex-src/Src/Base/Parser -I/home/runner/work/WarpX/WarpX/build_sp/_deps/fetchedamrex-src/Src/Boundary -I/home/runner/work/WarpX/WarpX/build_sp/_deps/fetchedamrex-src/Src/AmrCore -I/home/runner/work/WarpX/WarpX/build_sp/_deps/fetchedamrex-src/Src/EB -I/home/runner/work/WarpX/WarpX/build_sp/_deps/fetchedamrex-src/Src/LinearSolvers/MLMG -I/home/runner/work/WarpX/WarpX/build_sp/_deps/fetchedamrex-src/Src/LinearSolvers/Projections -I/home/runner/work/WarpX/WarpX/build_sp/_deps/fetchedamrex-src/Src/Particle -I/home/runner/work/WarpX/WarpX/build_sp/_deps/fetchedamrex-build -Werror -O3 -DNDEBUG -fPIC -pthread -Wno-error=sycl-strict -Wno-pass-failed -fsycl -fsycl-device-code-split=per_kernel -mlong-double-64 -Xclang -mlong-double-64 -fno-sycl-early-optimizations -MD -MT _deps/fetchedamrex-build/Src/CMakeFiles/amrex.dir/EB/AMReX_EB2_MultiGFab.cpp.o -MF CMakeFiles/amrex.dir/EB/AMReX_EB2_MultiGFab.cpp.o.d -o CMakeFiles/amrex.dir/EB/AMReX_EB2_MultiGFab.cpp.o -c /home/runner/work/WarpX/WarpX/build_sp/_deps/fetchedamrex-src/Src/EB/AMReX_EB2_MultiGFab.cpp
dpcpp: error: unable to execute command: Segmentation fault (core dumped)
dpcpp: error: clang frontend command failed due to signal (use -v to see invocation)
Intel(R) oneAPI DPC++/C++ Compiler 2021.3.0 (2021.3.0.20210619)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2021.3.0/linux/bin
```

**Pull request merged**
