### PR TITLE
Fixed a bug where centering coefficients used in Magentostatic solver…

### LINKED ISSUE #5242: B=0 field output in magnetostatic mode
I get zero magnetic field in the field output running with the magnetostatic solver on.

I'm running in electromagnetostatic mode via PICMI. I setup the solver like this:
```py
solver = picmi.ElectrostaticSolver(
    grid=grid,
    method='Multigrid',
    required_precision=1e-6,
    warpx_self_fields_verbosity = 0,
    warpx_magnetostatic=True,
)
```
And I install the field diagnostic like this:
```py
field_diag = picmi.FieldDiagnostic(write_dir = f'./diags/{diagdire}',
                                       warpx_file_prefix = 'field',
                                       grid = grid,
                                       period=100,
                                       warpx_openpmd_backend='h5',
                                       warpx_format='openpmd',
                                       data_list=['B', 'E', 'J', 'rho'])
    sim.add_diagnostic(field_diag)
```
This happens with both GPU and CPU runs.

Does anyone know what's going on? Let me know if other details are needed, such as the creation of `grid` or `sim`.

### PR DESCRIPTION
**Pull request by clarkse**
… were not being initialized when doing an energy-conserving field gather.

### CODE REVIEW

**Comment by clarkse** [comment]
This should resolve issue https://github.com/ECP-WarpX/WarpX/issues/5242

**Comment by EZoni** [comment]
To be rebased after #5296 is merged (will fix the `clang-tidy-3D` failure).

**Comment by roelof-groenewald** [comment]
I agree this will fix the B = 0 issue with non-Eb runs but the introduction of non-zero div B (as described in #5175) will still be there. We can merge this though and I'll try to get the follow-up PR cleaned up and ready to go over the next week or two.

**Comment by clarkse** [comment]
> I agree this will fix the B = 0 issue with non-Eb runs but the introduction of non-zero div B (as described in #5175) will still be there. We can merge this though and I'll try to get the follow-up PR cleaned up and ready to go over the next week or two.

This is meant to be a quick patch for the issue until the larger PR is fully tested.

**Comment by roelof-groenewald** [comment]
This looks good as an intermediate fix. @clarkse would you please rebase to `development` to sort out the merge conflict and we can merge this PR.

**Review by roelof-groenewald — APPROVED** [review]

**Pull request merged**
