### PR TITLE
Device version of field gather

### PR DESCRIPTION
**Pull request by atmyers**
This is the first step towards removing E and B from the particle data and going to just one kernel for the main PIC loop. 

So far this just adds and uses a device function version of the field gather. 

There are also a few style changes (some `using namespace amrex` for example) - sorry if that makes it hard to review. 

I will make a separate PR to fuse these into one kernel and remove E and B.

### CODE REVIEW

**Comment by atmyers** [comment]
GPU test results on Garuda: 

https://ccse.lbl.gov/pub/GpuRegressionTesting/WarpX/2020-05-08-002/index.html

**Comment by RemiLehe** [comment]
Thanks for this PR @atmyers !
Since it seems that the style changes (removing `amrex`, etc.) are isolated in the first 2 commits, would you mind doing a separate PR for these, maybe rebasing the current PR to remove those 2 commits? 
Sorry for being picky, but I think it would be convenient, esp. for future reference to this PR.

**Comment by atmyers** [comment]
See here: https://github.com/ECP-WarpX/WarpX/pull/997

**Comment by atmyers** [comment]
I will close this and reopen another pull request that doesn't include any style changes.

**Pull request closed without merging**
