### PR TITLE
QED example inputs: simplify initialization of product species

### PR DESCRIPTION
**Pull request by NeilZaim**
We now have the option to do `species.injection_style = "none"` to create a product species without initializing particles so we can use it to simplify the QED input files.

### CODE REVIEW

**Comment by lucafedeli88** [comment]
Thanks! Looks good to me... I will approve as soon as the tests pass

**Comment by lucafedeli88** [comment]
I am re-running the QED CI-test since I think that the failure was due to a random small fluctuation of some checksums

**Comment by NeilZaim** [comment]
Yes, looks like we'll probably have to reset the benchmarks. It seems that the random seed has changed or something like that. This is a bit surprising because in the failing test the 1 particle per cell that we created before should not even have their optical depth initialized (they should be discarded before due to 0 density) so I thought that we would do the exact same number of random calls now as we did before.

**Comment by NeilZaim** [comment]
Ah, in fact it was just the particle IDs that were failing in the benchmarks. This is because we were calling the function `ParticleType::NextID();` when pre-initializing 1 particle per cell for some species. So that will change the subsequent ids, and the benchmark change is expected. I've just reset the values.

**Review by lucafedeli88 — APPROVED** [review]
The QED tests have passed, so I can accept this PR!  Thanks @NeilZaim

**Pull request merged**
