### PR TITLE
Do Not Fill Guard Cells with Inverse FFTs, Unless for Field Damping

### LINKED ISSUE #2035: Instability when Filling Guard Cells with Inverse FFTs
The issue was originally reported by @NeilZaim.

There seem to be problems when we fill the guard cells with inverse FFTs in simulations using the PSATD solver. Here's a 2D input script that reproduces the issue: [inputs_2d.txt](https://github.com/ECP-WarpX/WarpX/files/6718612/inputs_2d.txt).

By replacing, on the current `development` branch (4e8eba636a354c5a83f6909e8081662e0082f488), `mf_box` with `mfi.validbox()` in
https://github.com/ECP-WarpX/WarpX/blob/0b6ddad4ce039277025b80ba81ff2692b3a80724/Source/FieldSolver/SpectralSolver/SpectralFieldData.cpp#L317
one can see that the instability is fixed by not filling the guard cells with inverse FFTs (see figures below, standard diags and raw data with guard cells).

<p align="center">
    
    
</p>

<p align="center">
    
    
</p>

Additional observations: (i) the issue occurs also without PMLs and (ii) the issue does not occur with periodic boundary conditions.

A possible workaround for now is to make the feature of filling the guard cells with inverse FFTs (i) optional and (ii) OFF by default, unless with moving window and field damping.

### PR DESCRIPTION
**Pull request by EZoni**
Fixes #2035.

**Description**
I added a new static member to the WarpX class, the IntVect `fill_guards`. It is an `AMREX_SPACEDIM`-dimensional vector of integers (0 or 1 should be the only allowed values), to control whether to fill the guard cells when performing inverse FFTs, independently along each direction. When `fill_guards = 0` in some direction, the full box used for the loop in the inverse FFT is shrinked by the number of guard cells in that direction.

`WarpX::fill_guards` is currently set to `0` in each direction, unless the direction is non-periodic and field damping is applied (e.g. with a moving window).

### CODE REVIEW

**Comment by EZoni** [comment]
@RemiLehe I suggest to have a look here before I update the benchmarks, because the failing tests on Azure will print out the relative errors of each failing benchmark. This will help us get an idea of which tests fail and how much they fail. So I will commit the update of the benchmarks after all CI checks have finished, following the last commit I just pushed (https://github.com/ECP-WarpX/WarpX/pull/2045/commits/b85faab34368c4ad9466e1f700ff58d868611893).

**Review by ax3l — APPROVED** [review]
Following our discussions and looking at the code, the current solutions looks good to me.

I'll let @RemiLehe take the final look.

**Review by NeilZaim — APPROVED** [review]
That looks good to me, thanks!

If we wanted to be more general, we could consider having a `fill_guards_lo` and a `fill_guards_hi` but I don't know if there are situations where that would be useful. (e.g., if there's a scenario where `field_boundary_lo[dir]` is `Damped` and `field_boundary_hi[dir]` isn't)

**Review by RemiLehe — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
