### PR TITLE
Add laser phase to gaussian profile

### PR DESCRIPTION
**Pull request by hightower8083**
Hi,
For one study I've a need to vary laser CEP, and this argument is missing. 
I've added and checked it -- seems working fine
If you think its generally useful (I think it is) you can merge this PR.

### CODE REVIEW

**Review by RemiLehe — CHANGES_REQUESTED** [review]
Thanks for this PR!
Would you mind adding the description of the new laser parameters to the Sphinx documentation?
This simply involves modifying this file:
https://github.com/ECP-WarpX/WarpX/blob/development/Docs/source/running_cpp/parameters.rst
(see where the other laser parameters are defined)

**Comment by hightower8083** [comment]
btw, are you fine with naming `phi0` or you prefer to call it `cep_phase` as [in here](https://github.com/fbpic/fbpic/blob/a3349a31111b0dd650ef1c7262c862a51a24f633/fbpic/lpa_utils/laser/laser.py#L162) ?
I've also added it to `Python/pywarpx/picmi.py`, but this might be misleading since it is not included into the base class `picmistandard.PICMI_GaussianLaser` -- probably we should also add it [there](https://github.com/ECP-WarpX/WarpX/blob/af7144301bf0d6bbc2263ef389c321cb0cb6fe40/Python/pywarpx/picmi.py#L509-L511) (for my use I've fixed this locally).

**Review by RemiLehe — APPROVED** [review]

**Comment by hightower8083** [comment]
Hi @RemiLehe 

Since, travis fails specifically `PICMI_inputs_laser_acceleration.py` shouldn't it be passing now after [this PR](https://github.com/picmi-standard/picmi/pull/27#issue-458314542) is merged? It seems this feature is already included into the recent `PyPI` repos for `picmistandard`.  Could you please force it to re-check and merge if its fine, so i could get rid of my branch? (our cluster restricts git access so its easier to have this feature directly at `development`..)

**Comment by RemiLehe** [comment]
@hightower8083 Thanks for the reminder!

**Pull request merged**
