### PR TITLE
Partial refactoring of the utils directory

### PR DESCRIPTION
**Pull request by lucafedeli88**
This PR is an attempt to a partial refactor of th Utils directory, which has become a bit "messy" ;-) .

In particular:

- I have created a subfolder "Algorithms", where I put the algorithms is_in (which I have improved), linear_interpolation (bilinear and trilinear as well), and
upper_bound. Those algorithms are inside a namespace called utils::algorithms

- I have created a subfolder "Physics", where I put stuff related to ionization tables. Those functions are inside the namespace utils::physics

- I have created the subfolder "Strings", where I put the split function and the automatic_text_wrap function

- I have created the subfolder "Parser", where I put the interval parser and the utility functions related to the amrex::Parser. These functions are inside the utils::parser namespace.

All the other changes in the code are a consequence of these changes.

### CODE REVIEW

**Comment by ax3l** [comment]
Thanks a lot!

How many of those are independent of WarpX?
We could use the `algorithms/`, `strings/` and `parser/` dirs and move them to ABLASTR as a follow-up PR.

(I suggest a separate PR, because we will change name spaces, proper docs strings and potentially spellings to be more uniform once things go to ABLASTR.)

**Comment by ax3l** [comment]
Test that fails is:
```
...
   mpiexec -n 2 ./BTD_ReducedSliceDiag.ex inputs_3d_slice  diag1.file_prefix=BTD_ReducedSliceDiag_plt   amrex.abort_on_unused_inputs=1 amrex.fpe_trap_invalid=1 amrex.fpe_trap_zero=1 amrex.fpe_trap_overflow=1 warpx.always_warn_immediately=1 warpx.abort_on_warning_threshold=low
   Execution time: 9.077 s
   WARNING: unable to open the job_info file
   doing the analysis...
   WARNING: analysis failed...
./analysis_3Dbacktransformed_diag.py  BTD_ReducedSliceDiag_plt000069
F.shape  (32, 32, 49)
Fs.shape (32, 2, 49)
error_rel    : 5.517171255272299
tolerance_rel: 1e-15
Traceback (most recent call last):
  File "./analysis_3Dbacktransformed_diag.py", line 45, in <module>
    assert( error_rel < tolerance_rel )
AssertionError

   Analysis time: 0.136 s
   WARNING: unable to copy analysis image
   archiving the output...
   creating problem test report ...
   BTD_ReducedSliceDiag FAILED
```

**Comment by lucafedeli88** [comment]
> Thanks a lot!
> 
> How many of those are indendent of WarpX? We could use the `algorithms/`, `strings/` and `parser/` dirs and move them to ABLASTR as a follow-up PR.
> 
> (I suggest a separate PR, because we will change name spaces, proper docs strings and potentially spellings to be more uniform once things go to ABLASTR.)

I think that at least `algorithms` and `strings` could end up in `ABLASTR` . Maybe also `parser`, but I don't know if what these functions do would be useful for other codes...

I'll do some separate PRs to do that, anyway...

**Comment by lucafedeli88** [comment]
> Test that fails is:
> 
> ```
> ...
>    mpiexec -n 2 ./BTD_ReducedSliceDiag.ex inputs_3d_slice  diag1.file_prefix=BTD_ReducedSliceDiag_plt   amrex.abort_on_unused_inputs=1 amrex.fpe_trap_invalid=1 amrex.fpe_trap_zero=1 amrex.fpe_trap_overflow=1 warpx.always_warn_immediately=1 warpx.abort_on_warning_threshold=low
>    Execution time: 9.077 s
>    WARNING: unable to open the job_info file
>    doing the analysis...
>    WARNING: analysis failed...
> ./analysis_3Dbacktransformed_diag.py  BTD_ReducedSliceDiag_plt000069
> F.shape  (32, 32, 49)
> Fs.shape (32, 2, 49)
> error_rel    : 5.517171255272299
> tolerance_rel: 1e-15
> Traceback (most recent call last):
>   File "./analysis_3Dbacktransformed_diag.py", line 45, in <module>
>     assert( error_rel < tolerance_rel )
> AssertionError
> 
>    Analysis time: 0.136 s
>    WARNING: unable to copy analysis image
>    archiving the output...
>    creating problem test report ...
>    BTD_ReducedSliceDiag FAILED
> ```

I see... I don't understand why  but I am trying to fix it

**Comment by lucafedeli88** [comment]
> > Test that fails is:
> > ```
> > ...
> >    mpiexec -n 2 ./BTD_ReducedSliceDiag.ex inputs_3d_slice  diag1.file_prefix=BTD_ReducedSliceDiag_plt   amrex.abort_on_unused_inputs=1 amrex.fpe_trap_invalid=1 amrex.fpe_trap_zero=1 amrex.fpe_trap_overflow=1 warpx.always_warn_immediately=1 warpx.abort_on_warning_threshold=low
> >    Execution time: 9.077 s
> >    WARNING: unable to open the job_info file
> >    doing the analysis...
> >    WARNING: analysis failed...
> > ./analysis_3Dbacktransformed_diag.py  BTD_ReducedSliceDiag_plt000069
> > F.shape  (32, 32, 49)
> > Fs.shape (32, 2, 49)
> > error_rel    : 5.517171255272299
> > tolerance_rel: 1e-15
> > Traceback (most recent call last):
> >   File "./analysis_3Dbacktransformed_diag.py", line 45, in <module>
> >     assert( error_rel < tolerance_rel )
> > AssertionError
> > 
> >    Analysis time: 0.136 s
> >    WARNING: unable to copy analysis image
> >    archiving the output...
> >    creating problem test report ...
> >    BTD_ReducedSliceDiag FAILED
> > ```
> 
> I see... I don't understand why but I am trying to fix it

I may have found the bug...

**Comment by ax3l** [comment]
@lucafedeli88 sorry, it looks like something collided here with another merge. Can you please update the PR?

**Comment by lucafedeli88** [comment]
@ax3l , I should have fixed the merge conflicts

**Comment by ax3l** [comment]
@lucafedeli88 sorry, a few more kicked in...
```
Conflicting files
Source/Initialization/PlasmaInjector.cpp
Source/Utils/WarpXUtil.H
Source/Utils/WarpXUtil.cpp 
```

**Comment by lucafedeli88** [comment]
> @lucafedeli88 sorry, a few more kicked in...
> 
> ```
> Conflicting files
> Source/Initialization/PlasmaInjector.cpp
> Source/Utils/WarpXUtil.H
> Source/Utils/WarpXUtil.cpp 
> ```

I'll fix them immediately...

**Comment by lucafedeli88** [comment]
I should have fixed the conflicts. I've renamed the `WarpXUtilSafeCast` namespace: since it only appears in a cpp file I've transformed it into an unnamed namespace

**Review by ax3l — APPROVED** [review]

**Pull request merged**
