### PR TITLE
Add a notebook for developers to interactively use AMReX

### PR DESCRIPTION
**Pull request by RemiLehe**
This adds a notebook in `Tools` for developers to interactively use AMReX.

Caveat: I have not been able to use it on MacOS, because I failed to compile AMReX as a library in that case (using CMake) ; but that might be a limitation of my own setup...

### CODE REVIEW

**Comment by RemiLehe** [comment]
This notebook is now available in a pre-build Binder.org instance:
https://github.com/RemiLehe/amrex-testbed/blob/master/README.md

Therefore, I'll close this PR as it is not very useful anymore.

**Comment by ax3l** [comment]
Really awesome, should we link somewhere in the docs that this exists?

**Comment by RemiLehe** [comment]
Sure, maybe we could add it here:
https://warpx.readthedocs.io/en/latest/developers/amrex_basics.html

@MaxThevenet Any opinion?

**Comment by MaxThevenet** [comment]
Yep, I agree it's a good location. Thanks for making this available!

**Pull request closed without merging**
