### PR TITLE
[WIP] Function to check if particle is too close from boundary

### PR DESCRIPTION
**Pull request by MaxThevenet**
Add an inline function in `Utils/CheckDistanceFromBoundary.H` that checks if a particle is too close to a boundary. This is a temporary fix, until this is handles by AMReX. This fixes issues #942 and #625, as the code shouldn't segfault randomly or run without injecting a laser pulse after this PR, but will print a meaningful message instead.

### CODE REVIEW

**Review by atmyers — APPROVED** [review]

**Comment by MaxThevenet** [comment]
Hm, not sure why the TravisCI tests fail, I haven't been able to reproduce the crash so far.

**Comment by ax3l** [comment]
To do: let's double-check the relation to #830

**Review by Yin-YinjianZhao — APPROVED** [review]
Thanks for the PR.

**Comment by RemiLehe** [comment]
This PR was discussed at meeting on last Friday. 
I think we decided to use a different solution, based on a function to be provided by the `amrex` team. As a consequence, I will close the current PR.

**Pull request closed without merging**
