### PR TITLE
Rename PSATD Classes

### PR DESCRIPTION
**Pull request by EZoni**
Follow up on #2748 and rename our PSATD classes similarly to what was suggested in https://github.com/ECP-WarpX/WarpX/pull/2748#issuecomment-1023526266:
- Cartesian:
  - `PsatdAlgorithmMultiJ` -> `PsatdAlgorithmJLinearInTime`
  - `PMLPsatdAlgorithm` -> `PsatdAlgorithmPml`
  - `ComovingPsatdAlgorithm` -> `PsatdAlgorithmComoving`
- RZ:
  - `PMLPsatdAlgorithmRZ` -> `PsatdAlgorithmPmlRZ`
  - `GalileanPsatdAlgorithmRZ` -> `PsatdAlgorithmGalileanRZ`

### CODE REVIEW

**Comment by dpgrote** [comment]
For my 2 cents, I don't like this name change. This seems fairly disruptive to save 5 characters in the names. It is always more clear to spell out words and I would much rather have a long name than a short one with abbreviations.

**Comment by EZoni** [comment]
@dpgrote What triggered this was that we need to change the current name `PsatdAlgorithmMultiJ` into something containing `JLinear` or `JLinearInTime`, because that is more correct.

@RemiLehe suggested in his review of #2748 that `PsatdAlgorithmJLinearInTime` would be too long, and that's how I came up with the idea of using `Algo` instead of `Algorithm` (for all classes) and removing the `InTime` part (for the one class that uses that). I'm fine with all options, as long as they are consistent (in addition, I would personally prefer that they also all start with `PsatdAlgorithm` -- or `PsatdAlgo`, whatever we choose -- and then add specific tags such as `Pml` or `Galilean` or `Comoving` afterwards, but I'm fine with keeping them as they are now as well).

@RemiLehe Would either `PsatdAlgorithmJLinearInTime` or `PsatdAlgorithmJLinear` (not sure if without `InTime` it is clear enough) work for you instead, despite what you mentioned in #2748? If so, I can keep `Algorithm` instead of `Algo` as @dpgrote suggests.

**Comment by dpgrote** [comment]
Either `PsatdAlgorithmJLinearInTime` or `PsatdAlgorithmJLinear` is fine with me and neither are too long.

Having the file names all start with `PsatdAlgorithm` is a good idea for consistency.

I do note that `Psatd` is an acronym but in this case it is fine since it is readily understood and this would be too long `PseudoSpectralAnalyticTimeDomainAlgorithmCurrentDensityLinearInTime` :)

**Comment by EZoni** [comment]
@RemiLehe @dpgrote Let me know what you think of the new names after the latest commit. Also, @RemiLehe let me know if `PsatdAlgorithmJLinear` is clear enough in your opinion, or if you would like it to read `PsatdAlgorithmJLinearInTime` instead. Thanks!

**Comment by dpgrote** [comment]
To be pedantic, should the acronyms be capitalized, i.e. `PSATD` and 'PML`? I'm fine either way.

Otherwise, this change looks good to me.

**Comment by EZoni** [comment]
Thank you, Dave. Regarding the acronyms, I personally find it a bit less readable if we capitalize them in this case. For instance, I would find `PsatdAlgorithmPmlRZ` more readable than `PSATDAlgorithmPMLRZ`, but may be just me so I'm also fine with both solutions.

**Comment by RemiLehe** [comment]
Sorry for the late reply. 
In light of the above discussion, I think I am fine with `PsatdAlgorithmJLinearInTime`. I think the `InTime` part is important here. Using ony `JLinear` might be confusing.

**Comment by EZoni** [comment]
@RemiLehe Thank you, sounds good, I'll update that name in the next commit!

**Review by RemiLehe — APPROVED** [review]

**Pull request merged**
