### PR TITLE
Azure CI: Cache

### PR DESCRIPTION
**Pull request by ax3l**
Try to use caching for as much as possible on Azure.
This might help to reuse AMReX objects between our weekly updates.
It might also be just way too large and get evicted quickly.

Docs:
- https://docs.microsoft.com/en-us/azure/devops/pipelines/release/caching

### CODE REVIEW

**Comment by ax3l** [comment]
Cannot see a caching effect/speedup yet for Ccache; Python installs are found.

Maybe worth trying again after #2556 ...

Ah, found the likely reason:
- [x] random tmp path in `run_tests.sh` will interfere with cached paths, maybe overwrite for CI to a fixed path
- [x] unclear why openPMD/BLAS++/LAPACK++ installs in dependency install seem to not speed up
  - ah, also creates a tmp directory: https://github.com/ax3l/cmake-easyinstall/blob/bc96f34acfe67a6523190d44475f3fcc8b9a123b/cmake-easyinstall#L48-L54
  - https://github.com/ax3l/cmake-easyinstall/pull/10

**Comment by ax3l** [comment]
Only blocked by https://github.com/ECP-WarpX/WarpX/pull/2624 now

**Comment by ax3l** [comment]
@RemiLehe ready for merge :)

**Review by RemiLehe — APPROVED** [review]

**Comment by ax3l** [comment]
Wuhu, in the best case a >3x speedup 
Before:
Screenshot from 2021-12-03 12-02-12

After:
Screenshot from 2021-12-03 12-21-15

**Pull request merged**
