### PR TITLE
CI: Reduce Runtime of Some Galilean Tests

### PR DESCRIPTION
**Pull request by oshapoval**
In this PR, I modified 3D averaged Galilean PSATD regression test for uniform plasma (`averaged_galilean_3d_psatd`) in order to lower its run time. In the new test case,  `dz/dx = 3`, `cfl=3` and `max_step = 160`. Reference energy (calculated via standard Galilean PSATD) also was recalculated and changed in `/WarpX/Examples/Tests/galilean/analysis_3d.py`.

### CODE REVIEW

**Review by ax3l — APPROVED** [review]
Thanks a lot, Olga! :)

**Review by EZoni — COMMENTED** [review]
Thank you, Olga! Looks good to me, we probably just need to reset the checksum benchmarks in averaged_galilean_3d_psatd.json (path: Regression/Checksum/benchmarks_json/).

**Comment by ax3l** [comment]
@oshapoval, I see this already improves
- [x] 80s: averaged_galilean_3d_psatd

can you also check if we can reduce the runtime of:
- [x] 80s: comoving_2d_psatd_hybrid
- [x] 83s: galilean_2d_psatd_hybrid

? :-)

**Comment by EZoni** [comment]
Thank you, Olga! So, here's the new runtimes I'm seeing in the last CI log:
- `averaged_galilean_3d_psatd`: 33.6 s
- `comoving_2d_psatd_hybrid`: 24.9 s
- `galilean_2d_psatd_hybrid`: 25.2 s

**Comment by EZoni** [comment]
Have you had the chance to check how the wakefields look like at the final time step of the new test? Some of the benchmark changes are quite large, I'm just curious to see if the wakefield is still well developed or not. I guess it's fine even if it's not as well developed as before, since we're mainly interested in testing regressions here.

**Comment by oshapoval** [comment]
> Have you had the chance to check how the wakefields look like at the final time step of the new test? Some of the benchmark changes are quite large, I'm just curious to see if the wakefield is still well developed or not. I guess it's fine even if it's not as well developed as before, since we're mainly interested in testing regressions here.

@EZoni Thanks a lot for reviewing this PR! Yes, I did. Wakefield looks good for the CI test. I am attaching the snapshots of the `Ez` field at timestep `step=400` for both 2D Galilean PSATD (hybrid) and comoving PSATD (hybrid). Please see below. 
2d_comoving_and_gal_psatd_hybrid

**Review by EZoni — APPROVED** [review]
Awesome! Looks good to me, I'll merge.

**Comment by ax3l** [comment]
I saw in recent CI that `averaged_galilean_3d_psatd` still runs around 45seconds.

Do you think we can tune it slightly more?

**Pull request merged**
