### PR TITLE
Removed const modifier from LPInfo object on stack that was causing a…

### PR DESCRIPTION
**Pull request by clarkse**
… warning from not being initialized properly.

### CODE REVIEW

**Review by lucafedeli88 — COMMENTED** [review]
Hi @clarkse ,
thank you for your contribution.
Could you please provide some more details on the configuration in which you saw a warning about this variable? In principle, the `amrex::MLEBNodeFDLaplacian` constructor takes `info` as a constant reference, so it should be OK to have `const amrex::LPInfo info;` here.

**Comment by clarkse** [comment]
This is the error I am getting building with GCC 9.4.0:

/home/st247c@HE.local/src/WarpX/Source/ablastr/fields/VectorPoissonSolver.H(133): warning #811-D: const variable "info" requires an initializer -- class "amrex::LPInfo" has no user-provided default constructor
      const amrex::LPInfo info;

I checked in PoissonSolver.H and it appears that the const is not in front of the amrex::LPInfo instantiation in that case.  I traced the addition of the const modifier to:
https://github.com/ECP-WarpX/WarpX/pull/3921

In this PR it was added to VectorPoissonSolver, but not PoissonSolver. I was just getting annoyed at seeing the compile time warning, so if we want to use the const then the default constructor for amrex::LPInfo should have a default constructor.

**Comment by clarkse** [comment]
@lucafedeli88 does this work for you?  It appears consistent with usage in AMReX.

**Review by lucafedeli88 — APPROVED** [review]
Looks OK to me. Thanks!

**Pull request merged**
