### PR TITLE
Remove Recursive Function from Parser

### PR DESCRIPTION
**Pull request by WeiqunZhang**
Replace recursive function in Parser with templates.  This makes it work with DPC++.  And we no longer need to adjust cuda stack size.  The warning message on CUDA stack size at the end of compilation is gone.

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
@ax3l Could you modify the cmake system to do something similar to the following change in gnu make.
```
ifdef MAX_RECURSION_DEPTH                                                                                                                                                                                 
  DEFINES += -DWARPX_MAX_RECURSION_DEPTH=\"$(MAX_RECURSION_DEPTH)\"                                                                                                                                       
else                                                                                                                                                                                                       
  DEFINES += -DWARPX_MAX_RECURSION_DEPTH=16                                                                                                                                                                
endif
```

**Comment by WeiqunZhang** [comment]
I have tested it on v100.  The new Parser is the same as the current one in terms of performance.  The maximum depth does not seem to affect the performance.

**Comment by ax3l** [comment]
@WeiqunZhang sorry, your ping has slipped me! Will do, yep!

**Comment by ax3l** [comment]
Updated!

@WeiqunZhang do we want, for simplicity, call this `WARPX_PARSER_DEPTH` (e.g. in the user-facing naming)?

**Comment by WeiqunZhang** [comment]
This PR is ready for review.  I have tested it on Nvida and AMD GPUs.

@ax3l I made the change to the name as you suggested.

**Review by atmyers — APPROVED** [review]

**Review by ax3l — APPROVED** [review]
Thanks a lot, this is really great! :rocket: :sparkles:

**Pull request merged**
