### PR TITLE
CI: NVHPC 24.1

### PR DESCRIPTION
**Pull request by ax3l**
Update NVHPC from 21.11 to 24.1.

Needed for int128 from https://github.com/AMReX-Codes/amrex/pull/3742 in #4678

### CODE REVIEW

**Comment by ax3l** [comment]
```
"/home/runner/work/WarpX/WarpX/build/_deps/fetchedpybind11-src/include/pybind11/pybind11.h", line 102: error: expected a ")"
  initialize(std::forward< Func> (f), (detail::function_signature_t< Func>  *)nullptr, extra...); 
                                                                                                ^
```

Reported as Nvidia bug no. 4491413
The issue seems to be part of HPC SDK since 23.9.

**Review by WeiqunZhang — APPROVED** [review]

**Comment by ax3l** [comment]
Uff, final NVHPC link:
```
/usr/bin/ld: lib/libwarpx.3d.MPI.CUDA.DP.PDP.OPMD.PSATD.EB.QED.a(BTD_Plotfile_Header_Impl.cpp.o): in function `BTDPlotfileHeaderImpl::BTDPlotfileHeaderImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/runner/work/WarpX/WarpX/Source/Diagnostics/BTD_Plotfile_Header_Impl.cpp:26: undefined reference to `amrex::Vector<std::array<double, 3ul>, std::allocator<std::array<double, 3ul> > >::~Vector()'
```

**Comment by ax3l** [comment]
Looks like an issue with the members
```C++
    /** Lower corner physical coordinates of each fab in the plotfile. */
    amrex::Vector<amrex::Array<amrex::Real, AMREX_SPACEDIM> > m_glo {{AMREX_D_DECL(0.,0.,0.)}};
    /** Upper corner physical coordinates of each fab in the plotfile. */
    amrex::Vector<amrex::Array<amrex::Real, AMREX_SPACEDIM> > m_ghi {{AMREX_D_DECL(1.,1.,1.)}};
```

**Comment by ax3l** [comment]
Ok, that last push fixed it: `Move m_glo/m_ghi init to .cpp`

**Comment by ax3l** [comment]
For the above NVCC + NVHPC (host-side) issue, I got a notification this week that this might be fixed in the next release of CUDA SDK and/or the NVIDIA HPC SDK.

**Pull request merged**
