### PR TITLE
[WIP] Do special FFT without guard cells in the case of periodic, single box PSATD

### PR DESCRIPTION
**Pull request by RemiLehe**

### CODE REVIEW

**Comment by EZoni** [comment]
Hi Rémi, I report some preliminary results on the test **Langmuir_multi_2d_psatd_nodal** using the current correction implemented in #675 (already merged in your branch `periodic_single_proc`) and the special FFT implemented in this PR:
- run:
`$ OMP_NUM_THREADS=1 mpirun -np 1 <path_to_exec>/main2d.gnu.TPROF.MPI.OMP.PSATD.ex <path_to_inputs>/inputs.txt >output.txt`
- inputs: [inputs.txt](https://github.com/ECP-WarpX/WarpX/files/4377217/inputs.txt) (compare with `Examples/Tests/Langmuir/inputs_2d_multi_rt`: the additional input parameters should match the runtime parameters set in `Regression/WarpX-tests.ini` for the test considered here)
- output: [output.txt](https://github.com/ECP-WarpX/WarpX/files/4377218/output.txt) (1 MPI process, 1 OMP thread, 1 grid)
- plot of `|rho/epsilon_0-div(E)|/|rho/epsilon_0|` on the `(x,y)` plane:
rho_divE

The minimum value is still quite larger than what I would expect (order `1e-1`), but there seem to appear even larger values at the corners of the domain.

**Comment by EZoni** [comment]
> Hi Rémi, I report some preliminary results on the test **Langmuir_multi_2d_psatd_nodal** using the current correction implemented in #675 (already merged in your branch `periodic_single_proc`) and the special FFT implemented in this PR:
> 
> * run:
>   `$ OMP_NUM_THREADS=1 mpirun -np 1 <path_to_exec>/main2d.gnu.TPROF.MPI.OMP.PSATD.ex <path_to_inputs>/inputs.txt >output.txt`
> * inputs: [inputs.txt](https://github.com/ECP-WarpX/WarpX/files/4377217/inputs.txt) (compare with `Examples/Tests/Langmuir/inputs_2d_multi_rt`: the additional input parameters should match the runtime parameters set in `Regression/WarpX-tests.ini` for the test considered here)
> * output: [output.txt](https://github.com/ECP-WarpX/WarpX/files/4377218/output.txt) (1 MPI process, 1 OMP thread, 1 grid)
> * plot of `|rho/epsilon_0-div(E)|/|rho/epsilon_0|` on the `(x,y)` plane:
>   rho_divE
> 
> The minimum value is still quite larger than what I would expect (order `1e-1`), but it seems that even larger values appear at the corners of the domain.

@RemiLehe Short follow-up: I obtain similar results by running the same test above with staggered fields instead of nodal fields.

**Comment by RemiLehe** [comment]
@EZoni Thanks a lot for the update.
I found one small bug, related to the order in which the guard cells exchange and current correction are done. (It is maybe not trivial, but in the case of the FFT without guard cells, the correction should be done *after* exchanging guard cells.)
I also added a flag, so that even in the case of a periodic, single-box simulation, the user can control whether or not to use this "special fft" (it is off by default).

Thus, in order to run the 2D Langmuir test, I use the following command:
```
./main2d.gnu.TPROF.MPI.OMP.PSATD.ex inputs_2d_multi_rt warpx.fields_to_plot=rho divE Ex Ey Ez warpx.do_current_correction=1 psatd.periodic_single_box_fft=1 amr.max_grid_size=128
```

This improves the results, but still the `div(E)-rho` is not zero.

**Comment by EZoni** [comment]
@RemiLehe Thank you for the update. The last commit seems indeed to fix the issue. I attach below the new plot obtained in the setup described in the initial message. The error is now of order `1e-1` uniformly in the domain. As you say, whether this is too large or not is a separate issue that has to do with the current correction itself (hence with #675).
rho_divE

**Comment by RemiLehe** [comment]
This PR is obsolete and is now replaced by #881

**Pull request closed without merging**
