### PR TITLE
[WIP] Reduce size of CI tests

### PR DESCRIPTION
**Pull request by MaxThevenet**

### CODE REVIEW

**Comment by MaxThevenet** [comment]
@dpgrote is the `coarsening_ratio` option for diagnostics available from PICMI?

**Comment by dpgrote** [comment]
@MaxThevenet Yes, it is indirectly. One can set the number_of_cells parameter when setting up a FieldDiagnostic. The coarsening_ratio will then be calculated as:
`coarsening_ratio = (np.array(self.grid.number_of_cells)/np.array(self.number_of_cells)).astype(int)`

**Comment by MaxThevenet** [comment]
Sounds good, thanks.

**Comment by lucafedeli88** [comment]
I will close this PR, since it has been inactive for a very long time and since it seems that we don't have significant issues with the size of CI tests rights now.

**Pull request closed without merging**
