### PR TITLE
[WIP] Updated proton-boron cross section

### PR DESCRIPTION
**Pull request by PhysicsDan**
Hello,

I have updated the proton-Boron cross section to use the analytical fit described in [A. Tentori & F. Belloni, Nuclear Fusion, 63, 086001 (2023)](https://doi.org/10.1088/1741-4326/acda4b) for the [Sikora & Wellar cross section dataset](https://doi.org/10.1007/s10894-016-0069-y).

Below is a plot of the analytical cross-section for both Tentori (2023) included in this pull request and Nevins (2000) which is currently implemented in WarpX.
image

Tests still need to be updated for the new cross section.

Thanks,
Daniel

### CODE REVIEW

**Comment by RemiLehe** [comment]
Hi @PhysicsDan,
Sorry that we did not get the time to review this PR in the last few days. 
I saw that you just closed it: Do you think that it should not be merged in the end? (After taking a quick look, the code does seem correct and worth incorporating in WarpX.)

**Comment by PhysicsDan** [comment]
Hi @RemiLehe,
No problem it was some poor GitHub management from my side and I had to remove my fork! I've updated the python analysis test too and will reopen the PR.
Cheers,
Daniel

**Comment by RemiLehe** [comment]
OK, great!
Thanks a lot for contributing these changes to WarpX. This looks very useful :)

**Comment by PhysicsDan** [comment]
No problem! :)

Opened a PR here https://github.com/ECP-WarpX/WarpX/pull/4377#issue-1945707158
I'll not delete my fork this time...

**Pull request closed without merging**
