### PR TITLE
LoadBalanceCosts reduced diagnostic set spatial indices to zero depending on dims

### PR DESCRIPTION
**Pull request by mrowan137**
This PR sets spatial components of LoadBalanceCosts reduced diagnostic to 0.0 depending on spatial dimensions of the problem.

### CODE REVIEW

**Review by RevathiJambunathan — APPROVED** [review]
Thank you @mrowan137 for fixing this!

**Comment by ax3l** [comment]
Thank you @mrowan137 !

Can you please summarize for me what it did before this patch? Undefined values?

**Comment by mrowan137** [comment]
> Thank you @mrowan137 !
> 
> Can you please summarize for me what it did before this patch? Undefined values?

I believe it was an undefined value, recorded as some constant number that we do not specify.  @eloisejyang  might also be able to comment.

[Edited] @RevathiJambunathan Thanks! I checked with some old 2D `LoadBalanceCosts` reduced diagnostics data I have lying around, that is indeed what is recorded for the 3rd index in 2D.

**Comment by RevathiJambunathan** [comment]
It was actually taking the next value in memory, i.e., index from the next box, from what I recall.

**Comment by mrowan137** [comment]
@ax3l any advice about the failing OneAPI DPC++ build?  this is the error (I did not get it the previous commit, which is pretty much the same as the current):
`/usr/bin/ld: final link failed: No space left on device`

**Comment by ax3l** [comment]
DPC++ fixed with  #1813 :)

**Review by ax3l — APPROVED** [review]

**Pull request merged**
