### PR TITLE
Added B field to plasma lens

### PR DESCRIPTION
**Pull request by dpgrote**
Added B field to the plasma lens. The input parameters for the lens strengths are now particles.repeated_plasma_lens_strengths_E and particles.repeated_plasma_lens_strengths_B. To apply E and B fields both of these are needed, `particles.E_ext_particle_init_style = repeated_plasma_lens` and `particles.B_ext_particle_init_style = repeated_plasma_lens`.

### CODE REVIEW

**Comment by ax3l** [comment]
LGTM, thank you!
Do you want to add a test that runs the newly added B-field option to have it covered?

**Comment by dpgrote** [comment]
@ax3l I was afraid you were going to ask that :). I don't know if there is an exact analytic solution to the particle motion when there is a B field with this dependency. Though, it would be the same as with the E field if one ignores the change in Vz. I'll try something.

**Comment by dpgrote** [comment]
@ax3l I've updated the test (and fixed a bug that was applying the wrong B field).

**Comment by ax3l** [comment]
Awesome, glad we covered it with a test :)

The checksum of `Plasma_lens` changed with the new inputs - don't forget to reset it as a last step, please.

**Review by ax3l — APPROVED** [review]
Thanks a lot! :tada:

**Comment by ax3l** [comment]
oneAPI CI partitioning today is stronger than my patience ;-) Will merge
https://github.com/ECP-WarpX/WarpX/pull/1566#issuecomment-893876401

**Pull request merged**
