### PR TITLE
Initial work to integrate a new QED library with WarpX

### PR DESCRIPTION
**Pull request by lucafedeli88**
Dear all,

as agreed, I've started the integration of the QED module of PICSAR into WarpX. 
At the moment the code compiles, but it crashes right after the initialization.

In order to compile:
switch to the QED branch in picsar
make sure that the GNUmakefile includes the line
QED = TRUE

These are the main things that I've done:
>>I've added a photon pusher (this does not require QED=TRUE).
PhotonParticleContainer::PushPX now calls a new function  warpx_particle_pusher_positions,
which is a wrapper around a new Fortran  subroutine warpx_particle_pusher_positions
in WarpX_picsar.f90

>>I've added a new folder, QED, in the source tree
This folder will contain wrappers and helper functions to manage the integration between
Warpx and the new QED library. In particular, amrex_rng_wrapper is a wrapper around
the RNG provided by warpx (it should be provided to the engines), while breit_wheeler_engine_wrapper
is just an alias plus a helper function. 

>>I've added a breit wheeler engine as a public member of MultiParticleContainer.
This class is in charge of the initialization of the lookup tables.

>>I've added a new component (tau) to the PhotonParticleContainer
with the following lines 
    AddRealComp("tau");
    plot_flags.resize(PIdx::nattribs + 1, 1);

>>I have added a function to initialize the optical depths of a PhotonParticleContainer
void PhotonParticleContainer::InitOpticalDepth(
    WarpXParIter& pti,
    warpx_breit_wheeler_engine& engine)
The idea is that MultiParticleContainer should call this function for all the "QED species"
(photons and, in the future, leptons).

At the moment the code compiles, but I get the following error when it runs:

MPI initialized with 1 MPI processes
OMP initialized with 8 OMP threads
AMReX (19.05.1-229-gae4807a4a2e3) initialized
0::Assertion `index < NReal + m_runtime_rdata.size()' failed, file "../amrex/Src/Particle/AMReX_StructOfArrays.H", line 37 !!!
SIGABRT

### CODE REVIEW

**Comment by atmyers** [comment]
Hi Luca,

The problem was that, although the extra "tau" field was requested, the initial conditions for those components weren't being added, resulting in a size mismatch in the vectors. I made it so that whenever a particle is added in WarpX, if additional runtime particle components have been added to that container, the component will be sized appropriately and initialized to zero by default. The component will still need to be filled with the real initial data later.  

The code makes it past the assertion failure now.

**Comment by lucafedeli88** [comment]
Hi Andrew,

thank you very much!

Unfortunately, I am still getting an error. I've synced my fork to the qed_playground branch 
of ECP-WarpX/WarpX. When I run the code now I get the (new) following error:

 Writing plotfile diags/plotfiles/plt00000
0::Assertion `real_comp_names.size() == NumRealComps() + NStructReal' failed, file "../amrex/Src/Particle/AMReX_ParticleContainerI.H", line 2827 !!!
SIGABRT

Do you have any idea of the possible cause?

**Comment by atmyers** [comment]
I think this is a separate issue that is fixed in PR #174. Let me merge that int `dev`, then merge dev into `qed_playground`, and then can you see if that fixes the problem?

**Comment by atmyers** [comment]
Actually, I think this is another, related issue. We the PhotonParticleContainer needs to specify the "tau" field when writing the plotfile.

**Comment by lucafedeli88** [comment]
Thanks for the information.  I've modified Source/Diagnostics/ParticleIO.cpp , adding the following lines  

`        #ifdef WARPX_QED
            auto temp_names = real_names;
            if(species_types[i] == PCTypes::Photon)                
                temp_names.push_back("tau");

            pc->WritePlotFile(dir, species_names[i],
                                 pc->plot_flags, int_flags,
                                 temp_names, int_names);
        #else

            pc->WritePlotFile(dir, species_names[i],
                              pc->plot_flags, int_flags,
                              real_names, int_names
        #endif
`

in

`
MultiParticleContainer::WritePlotFile (const std::string& dir,
                                       const Vector<std::string>& real_names) const
`

Now the code does not crash anymore. Do you think that this is a reasonable solution? 
Am I breaking other stuff if I do this?

When the QED library will be fully coupled with WarpX, photon, electron and positron species could have a "tau" field (if QED effects are enabled for those species). Ion species won't have it.

**Comment by lucafedeli88** [comment]
Thank you very much,
In my fork I have added 

`
#ifdef WARPX_QED
            //If the species is a photon, add the tau field 
            if(species_types[i] == PCTypes::Photon)
                real_names.push_back("tau");
#endif
`
to the 
`
void
MultiParticleContainer::WritePlotFile (const std::string& dir) const
`
method  in the Diagnostics/ParticleIO.cpp file

**Pull request merged**
