### PR TITLE
Make BeamRelevant reduced diagnostic doable for RZ

### PR DESCRIPTION
**Pull request by Yin-YinjianZhao**
This PR makes the BeamRelevant reduced diagnosis doable for RZ coordinate.
All changes are made in BeamRelevant.cpp.
This reduced diagnosis will be tested in the PR #1135 .

### CODE REVIEW

**Review by LDAmorim — COMMENTED** [review]
Thanks for this PR @Yin-YinjianZhao !
All looks good to me.

I was wondering if for the purpose of making the code faster (i.e. not computing the division by `c` so many times) it would be worth it to work with `gamma beta` instead of `u = gamma beta c`.
What do you think?

**Comment by Yin-YinjianZhao** [comment]
> Thanks for this PR @Yin-YinjianZhao !
> All looks good to me.
> 
> I was wondering if for the purpose of making the code faster (i.e. not computing the division by `c` so many times) it would be worth it to work with `gamma beta` instead of `u = gamma beta c`.
> What do you think?

Thanks!
For this calculation, `PhysConst::c` is only divided at the end outside of the loops I believe. For the `inv_c2`, we have to use it since the `u` in the code is with `c`.
For general purpose in the code, I'd say yes if we change all equations and let `u` absorbs `c`. Or using a normalization such that `c=1`, so it can be discarded. But since we are using SI units without normalization and keeping equations their original form, for the purpose of generalization, we probably have to loos some efficiency.

**Comment by dpgrote** [comment]
Thanks for making this change!

I was going to ask if you could use the `GetParticlePosition` routine instead of referring directly to the p.pos. This will do the handling of converting to x, y, z (including in RZ) so don't need to have that in your code and might be cleaner. But I don't see how that would work because of the way you are using the ReduceSum routine, looping over each quantity separately. Something to think about though.

Also, can you use "(defined WARPX_DIM_3D)" instead of "(AMREX_SPACEDIM == 3)"?

Hope that I didn't jump in too early with my comments.

**Comment by Yin-YinjianZhao** [comment]
> Thanks for making this change!
> 
> I was going to ask if you could use the `GetParticlePosition` routine instead of referring directly to the p.pos. This will do the handling of converting to x, y, z (including in RZ) so don't need to have that in your code and might be cleaner. But I don't see how that would work because of the way you are using the ReduceSum routine, looping over each quantity separately. Something to think about though.
> 
> Also, can you use "(defined WARPX_DIM_3D)" instead of "(AMREX_SPACEDIM == 3)"?
> 
> Hope that I didn't jump in too early with my comments.

Thanks! Just replaced them.

**Comment by LDAmorim** [comment]
Thanks for the reply @Yin-YinjianZhao !
But we also use the division to compute gamma.
Maybe it doesn't make sense to create alternative variables for your function, memory wise.
And since this is just during diagnostics, I agree with you that

> But since we are using SI units without normalization and keeping equations their original form, for the purpose of generalization, we probably have to loos some efficiency.

**Comment by Yin-YinjianZhao** [comment]
This PR should work since it is tested here https://github.com/ECP-WarpX/WarpX/pull/1135#issuecomment-669257804.

**Comment by ax3l** [comment]
restarting CI

**Review by ax3l — APPROVED** [review]

**Pull request merged**
