### PR TITLE
[min-PR] QED module: use function provided by PICSAR  to calculate gamma factor for photons

### PR DESCRIPTION
**Pull request by lucafedeli88**
Inside `BreitWheelerEngineWrapper.H` we need to calculate the gamma factor for photons to decide if their optical depth changes.
Indeed, if gamma < 2 the optical depth should not be evolved and pair generation should not take place (if pair production is called with gamma < 2, it leads to electrons and positrons having NaN as momentum components).
With this PR, gamma is calculated with a function provided by PICSAR. This ensures that the result is identical to what is calculated internally in PICSAR, preventing possible issues to due machine-precision errors.

### CODE REVIEW

**Review by NeilZaim — APPROVED** [review]
Thanks for this PR!

**Comment by EZoni** [comment]
Note that the PICSAR commit changes you made here have just been merged independently in `development` through #1931 (May release).

**Comment by lucafedeli88** [comment]
> Note that the PICSAR commit changes you made here have just been merged independently in `development` through #1931 (May release).

Oh, I see! Anyway, I've just merged the development branch into my branch...

**Review by EZoni — APPROVED** [review]
Thank you for this PR, looks good to me. I'll merge now.

**Pull request merged**
