### PR TITLE
bug fixes for some refactored GPU filter code

### PR DESCRIPTION
**Pull request by atmyers**

### CODE REVIEW

**Comment by MaxThevenet** [comment]
Thanks for this PR @atmyers.
Could you run the automated test for Bilinear filter on GPU to check for the results?
The script and input file are in https://github.com/ECP-WarpX/WarpX/tree/dev/Examples/Tests/SingleParticle
and here is how the reg test entry looks:
```
[bilinear_filter]
buildDir = .
inputFile = Examples/Tests/SingleParticle/inputs
runtime_params = warpx.use_filter=1 warpx.filter_npass_each_dir=1 5
dim = 2
addToCompileString =
restartTest = 0
useMPI = 1
numprocs = 2
useOMP = 1
numthreads = 2
compileTest = 0
doVis = 0
analysisRoutine = Examples/Tests/SingleParticle/bilinear_filter_analysis.py
```
Thanks!

**Comment by RemiLehe** [comment]
@MaxThevenet I think that the above mentioned test was run as part of the Travis tests, no?
https://travis-ci.org/ECP-WarpX/WarpX/jobs/539399275

**Comment by RemiLehe** [comment]
Ah, sorry, you meant on GPU.

**Comment by atmyers** [comment]
I verified that the CPU and GPU versions of that test give the same results on Summit. However, the analysis script actually fails for both runs on Summit, with a relative error of `0.08397485283107826`. There seems to be something funny going on with the filter, as shown by the CCSE test failures last night.

**Comment by atmyers** [comment]
False alarm - the CPU and GPU versions are fine if I run with Esirkopov, which is what the analysis script excepts.

**Pull request merged**
