### PR TITLE
Cleanup picsar references, algorithm choices, and unused fortran references

### PR DESCRIPTION
**Pull request by RemiLehe**
This cleans up the code that used to be associated with fortran:

- The code for the fortran current deposition is removed.
- A number of references to PICSAR are removed. Right now, PICSAR is only used in WarpX for the MPI-hybrid spectral solver (which is *not* the default spectral solver) and for generating the documentation.
- A number of Fortran interface were removed, since the corresponding functions had been removed in previous PRs.
- Because we are not using the PICSAR code anymore for deposition and gather, the number of algorithmic options is reduced (e.g. we do not have the choice between `direct` and `direct-vectorized` anymore). This PR makes the corresponding changes in the documentation, and in the code.

### CODE REVIEW

**Comment by dpgrote** [comment]
Thanks for this PR! I was also going to do some of this clean up, removing references to picsar routines, but you beat me to it.

**Comment by dpgrote** [comment]
Can the file WarpX_picsar.F90 be deleted?

**Comment by dpgrote** [comment]
I see a few more changes needed.

A comment in Source/Utils/WarpXAlgorithmSelection.cp references PICSAR.
There are a number of references to picsar in the Docs, including the file called picsar_theory.rst.

**Comment by RemiLehe** [comment]
OK, thanks for reviewing!
I remove the file that you mentioned, as well as the additional reference to PICSAR.
Regarding: I think I'll update it in another PR. I think that we do not want to suppress the reference to PICSAR there: it would still be needed when using the hybrid spectral solver, and in the future for QED modules.

**Comment by dpgrote** [comment]
Once it passes the checks, I'll merge.

**Pull request merged**
