### PR TITLE
[WIP] Update AMReX

### PR DESCRIPTION
**Pull request by ax3l**
I want to pull in a new feature to ABLASTR for inputs control that just landed in AMReX. Needed for ImpactX Python:
- https://github.com/AMReX-Codes/amrex/pull/2842

### CODE REVIEW

**Review by WeiqunZhang — APPROVED** [review]

**Comment by ax3l** [comment]
Oh, checksum change from the update?

**Comment by EZoni** [comment]
If it helps, these are the tests that failed:
- `background_mcc_dp_psp` ("cartesian2d")
- `reduced_diags_single_precision` ("single_precision")

@PhilMiller Could these checksum changes be related to https://github.com/AMReX-Codes/amrex/pull/2814?

**Comment by ax3l** [comment]
Might need https://github.com/AMReX-Codes/amrex/pull/2839 ?

I will try to run with that commit.

**Comment by ax3l** [comment]
CI of this current PR is now running on https://github.com/AMReX-Codes/amrex/pull/2839

PR #3192 will replace this PR once the above AMReX PR is merged.

**Comment by ax3l** [comment]
Replaced by #3192

**Pull request closed without merging**
