### PR TITLE
AMReX/PICSAR: Weekly Update

### PR DESCRIPTION
**Pull request by ax3l**
Weekly update to latest AMReX.
Weekly update to latest PICSAR (no changes).

```console
./Tools/Release/updateAMReX.py
./Tools/Release/updatePICSAR.py
```

### CODE REVIEW

**Review by EZoni — APPROVED** [review]

**Comment by ax3l** [comment]
@WeiqunZhang @atmyers this week's update of AMReX changes WarpX checksums. Do you have time to investigate this?

- 2D: background_mcc_dp_psp (position)
- 3D: pml_psatd_dive_divb_cleaning (rho)
- SP: reduced_diags_single_precision (momentum)

**Comment by ax3l** [comment]
@atmyers @PhilMiller looking at the changes, I think you know this best:
https://github.com/AMReX-Codes/amrex/compare/9aa23c202a13eee489a06030b9aeda6b89856944...826cd378f8ba0d844c64e1029f7914c3b066debd

Likely in this PR:
- https://github.com/AMReX-Codes/amrex/pull/2950

**Comment by WeiqunZhang** [comment]
The failure of `3D: pml_psatd_dive_divb_cleaning (rho)` was due to the change in `amrex::Geometry::outsideRoundOffDomain`.

**Review by WeiqunZhang — APPROVED** [review]

**Comment by ax3l** [comment]
2D: background_mcc_dp_psp (position) - @peterscherpelz:
```
That seems fine to me, I don't have any reason a small change like that would matter. Thanks for checking 
```

SP: reduced_diags_single_precision (momentum) - @RemiLehe:
```
I think that we can also reset the test reduced_diags_single_precision:
the errors are consistent with potentially having a slightly different number of particles in the box, due to the change in the condition that removes particles.
```

3D: pml_psatd_dive_divb_cleaning (rho) - @EZoni:
```
That test has three different lasers, polarized in three different directions, and I think it was added to show that using div cleaning in the PML (together with div cleaning in the valid domain) helps mitigate some instability that was otherwise growing at the domain-PML interface. This is described in more detail in PR [#1600](https://github.com/ECP-WarpX/WarpX/pull/1600), where the test was originally introduced.
```
-> @RemiLehe & @EZoni : ok to update checksum

**Comment by ax3l** [comment]
I did reset the three checksums with AMReX from a week ago. This passed locally.

After that, I pushed the latest AMReX change from this week on the PR.

**Pull request merged**
