### PR TITLE
amrex::Interpolater::interp has changed its interface

### PR DESCRIPTION
**Pull request by WeiqunZhang**
WarpX uses AMReX's nodal interpolater.  Its interface has changed in the latest development branch.

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
Other WarpX branches need to be merged to have this change as well, if it uses AMReX development.

**Comment by RemiLehe** [comment]
@WeiqunZhang Any idea why the automated tests are failing?

**Comment by WeiqunZhang** [comment]
I think it was because I pushed the warpx change two days ago when the amrex change was not on development branch yet.

Is there a way to rerun the CI test?

**Comment by RemiLehe** [comment]
Yes, I just restarted the Travis CI tests.

**Comment by RemiLehe** [comment]
They passed. I'll merge.

**Pull request merged**
