### PR TITLE
Always compile with QED support

### PR DESCRIPTION
**Pull request by lucafedeli88**
Warning: depends on https://github.com/ECP-WarpX/WarpX/pull/1198

### CODE REVIEW

**Comment by ax3l** [comment]
@lucafedeli88 can you please also update the documentation of the new PICSAR branch in `Docs/source/building/summit.rst` (and `juwels.rst`), `Docs/source/running_cpp/parameters.rst`, `WarpX-tests.ini`? #1359

Are we able to simplify some tests in Travis-CI, by always building QED and avoiding some re-builds?

**Comment by lucafedeli88** [comment]
> @lucafedeli88 can you please also update the documentation of the new PICSAR branch in `Docs/source/building/summit.rst` (and `juwels.rst`), `Docs/source/running_cpp/parameters.rst`, `WarpX-tests.ini`? #1359
> 
> Are we able to simplify some tests in Travis-CI, by always building QED and avoiding some re-builds?

@ax3l , thanks a lot for #1359 ! I have just approved it ( I have suggested a very minor amendment) .

For what concerns your question: yes, if we always compile with QED support we won't need to recompile the code twice (2D and 3D) for the QED tests. The QED tests themselves only require few seconds each, so they could be easily grouped with other tests...

**Comment by ax3l** [comment]
@lucafedeli88 do you like to rebase this PR, now that #1198 and #1359 are merged? :)

**Comment by lucafedeli88** [comment]
I will close and re-open this PR with another branch, since I made a mess with `git merge`

**Pull request closed without merging**
