### PR TITLE
Simplify  overwrite_amrex_parser_defaults WarpXAMReXInit.cpp

### PR DESCRIPTION
**Pull request by lucafedeli88**
`overwrite_amrex_parser_defaults` in `WarpXAMReXInit.cpp` does several different things. This PR subdivides what `overwrite_amrex_parser_defaults` into smaller functions that are called sequentially in order to improve readability.

### CODE REVIEW

**Comment by ax3l** [comment]
Restarting CI

**Comment by ax3l** [comment]
Is that truly simpler? :D
Or more structured/readable?

**Review by ax3l — APPROVED** [review]
OK with me :)

**Comment by lucafedeli88** [comment]
> Is that truly simpler? :D Or more structured/readable?

you are right... "simplifying" is misleading here. It is just more readable.

**Pull request merged**
