### PR TITLE
Replace an always false test with an abort

### PR DESCRIPTION
**Pull request by lucafedeli88**
I am not completely sure about replacing an `assert(false, msg)` with `abort(msg)`. However, adding `#else ... #endif` also fixes a `potential null pointer dereference` warning

### CODE REVIEW

**Comment by dpgrote** [comment]
Where does the `potential null pointer deference` happen?

**Comment by lucafedeli88** [comment]
> Where does the `potential null pointer deference` happen?

here: 

```
./Source/Utils/WarpXUtil.cpp: In function ‘void CheckGriddingForRZSpectral()’:
./Source/Utils/WarpXUtil.cpp:299:24: warning: potential null pointer dereference [-Wnull-dereference]
  299 |     max_grid_size_x[0] = n_cell[0];
```

I compiled with `make QED=TRUE DIM=2 COMP=llvm`

**Comment by dpgrote** [comment]
Does it also complain about line 298?

The change looks good - I'll approve it.

**Review by dpgrote — APPROVED** [review]
Thanks for making the change!

**Pull request merged**
