### PR TITLE
Fix some double-->float warnings in NCIGodfrey table

### PR DESCRIPTION
**Pull request by lucafedeli88**
This PR fixes some warnings related to double-->float casts when WarpX is compiled in single precision. 

This time I used `sed` and regex ;-):
```
sed -i.bak -r 's/(\-?[0-9]+\.[0-9]+)/amrex::Real(\1)/g' NCIGodfreyTables.H
```
**Update:** now using `_rt` instead of `amrex::Real`. However the tables had to be placed in a dedicated namespace (see discussion below).

### CODE REVIEW

**Comment by RemiLehe** [comment]
Thanks for this PR @lucafedeli88 
Would it be possible to use `_rt` here? If yes, I guess it would be slightly more compact.

**Comment by lucafedeli88** [comment]
> Thanks for this PR @lucafedeli88
> Would it be possible to use `_rt` here? If yes, I guess it would be slightly more compact.

Unfortunately, I don't think that using `_rt` is possible here: I would need to add `using namespace amrex` (`_rt` is defined in the inlined`namespace literals` in `namespace amrex` ), but `NCIGodfreyTables.H` is a header file...

**Comment by ax3l** [comment]
Oh that's true, it's a header file.
You could scope it with namespaces, e.g.
```C++
namespace warpx
{
    namespace nci_godfrey
    {
        using amrex::literals;
        // constants defined here
    }
}
```

But even then it would propagate if a user decided to call `using namespace warpx::nci_godfrey;`. Nonetheless, this would (hopefully) happen in a function body, so we would be quite safe. Or they use `constexpr auto x = warpx::nci_godfrey::table_nci_godfrey_galerkin_Ex_Ey_Bz[42][42];` What do you think?

**Comment by RemiLehe** [comment]
I like @ax3l's suggestion.
@lucafedeli88 Any preference?

**Comment by lucafedeli88** [comment]
I like @ax3l 's suggestion too! I'll do that...

**Comment by lucafedeli88** [comment]
I should have implemented @ax3l 's suggestion...

**Review by RemiLehe — APPROVED** [review]

**Pull request merged**
