### PR TITLE
Azure: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by ax3l**
Update to the latest Ubuntu LTS release (20.04) on our Azure CI tests.

The system compiler updates from 7.4.0 to 9.3.0

Follow-up to #1558

### CODE REVIEW

**Comment by ax3l** [comment]
Ahhhh:
```
There are not enough slots available in the system to satisfy the 4
slots that were requested by the application:

  ./main2d.gnu.TEST.TPROF.MTMPI.OMP.QED.OPMD.PSATD.GPUCLOCK.ex

Either request fewer slots for your application, or make more slots
available for use.

A "slot" is the Open MPI term for an allocatable unit where we can
launch a process.  The number of slots available are defined by the
environment in which Open MPI processes are run:

  1. Hostfile, via "slots=N" clauses (N defaults to number of
     processor cores if not provided)
  2. The --host command line parameter, via a ":N" suffix on the
     hostname (N defaults to 1 if not provided)
  3. Resource manager (e.g., SLURM, PBS/Torque, LSF, etc.)
  4. If none of a hostfile, the --host command line parameter, or an
     RM is present, Open MPI defaults to the number of processor cores

In all the above cases, if you want Open MPI to default to the number
of hardware threads instead of the number of processor cores, use the
--use-hwthread-cpus option.

Alternatively, you can use the --oversubscribe option to ignore the
number of available slots when deciding the number of processes to
launch.
```

```
[leveling_thinning]
numprocs = 4

[Python_pass_mpi_comm]
numprocs = 3

[Python_particle_attr_access]
numprocs = 3
```

**Comment by ax3l** [comment]
`multi_J_rz_psatd`:
```
piexec -n 2 ./main2d.gnu.TEST.TPROF.MTMPI.OMP.QED.OPMD.PSATD.RZ.GPUCLOCK.ex inputs_rz  diag1.file_prefix=multi_J_rz_psatd_plt   amrex.abort_on_unused_inputs=1
MPI initialized with 2 MPI processes
MPI initialized with thread support level 3
OMP initialized with 1 OMP threads
AMReX (21.09-32-g350a3efc2c64) initialized
WarpX (Unknown)
PICSAR (a78be127f66a)
Level 0: dt = 5.993729836e-15 ; dx = 3.125e-06 ; dz = 1.796875e-06
[11c77c5bcb32:29340] Read -1, expected 57190912, errno = 1
[11c77c5bcb32:29340] Read -1, expected 57190912, errno = 1

Grids Summary:
  Level 0   2 grids  8192 cells  100 % of domain
            smallest grid: 64 x 64  biggest grid: 64 x 64

[11c77c5bcb32:29340] Read -1, expected 8192, errno = 1
[11c77c5bcb32:29339] Read -1, expected 8192, errno = 1
[11c77c5bcb32:29340] Read -1, expected 8192, errno = 1
[11c77c5bcb32:29340] Read -1, expected 8192, errno = 1
[11c77c5bcb32:29340] Read -1, expected 8192, errno = 1
[11c77c5bcb32:29339] Read -1, expected 8192, errno = 1
[11c77c5bcb32:29339] Read -1, expected 8192, errno = 1
[11c77c5bcb32:29339] Read -1, expected 8192, errno = 1
[11c77c5bcb32:29339] Read -1, expected 8192, errno = 1
[11c77c5bcb32:29340] Read -1, expected 8192, errno = 1
[11c77c5bcb32:29340] Read -1, expected 8192, errno = 1
[11c77c5bcb32:29339] Read -1, expected 8192, errno = 1
[11c77c5bcb32:29340] Read -1, expected 5920, errno = 1
[11c77c5bcb32:29339] Read -1, expected 5920, errno = 1
[11c77c5bcb32:29339] Read -1, expected 5920, errno = 1
[11c77c5bcb32:29340] Read -1, expected 5920, errno = 1
[11c77c5bcb32:29339] Read -1, expected 5920, errno = 1
[11c77c5bcb32:29340] Read -1, expected 5920, errno = 1
[11c77c5bcb32:29339] Read -1, expected 5920, errno = 1
[11c77c5bcb32:29340] Read -1, expected 5920, errno = 1
  Writing plotfile multi_J_rz_psatd_plt00000

STEP 1 starts ...
[11c77c5bcb32:29339] Read -1, expected 8192, errno = 1
...
```
(with OpenMPI 4.0.3)

**Comment by ax3l** [comment]
Hello old friend: https://github.com/open-mpi/ompi/issues/4948 (when reproducing on Docker - not visible in Azure Pipelines as a problem at the moment).

Work-around:
```bash
export OMPI_MCA_btl_vader_single_copy_mechanism=none
```

Does not solve the main issue with different simulation values at step 50 that we are looking  for here, though.

**Comment by ax3l** [comment]
Let's see if the discrepancy in the current (~2x off) in `multi_J_rz_psatd` is solved with #2404

**Review by EZoni — APPROVED** [review]
Thank you for the update and for fixing the failing tests in #2404, Axel! Looks good to me!

**Pull request merged**
