### PR TITLE
Added `none` as an option for fields_to_plot

### PR DESCRIPTION
**Pull request by dpgrote**
This option allows turning off all field diagnostics, if for example the user only wants particle output.

This change was causing problems in AMReX, producing divide by zero errors or failed assertions. ~~It is likely that this can't be done (at least for plot files) without changes in AMReX.~~ The problems were avoided by skipping the call to the AMReX routine that would write out the fields, and skipping the creation of the MultiFab that would contain the fields.

### CODE REVIEW

**Comment by ax3l** [comment]
Thank you!
I tried this in #1559 already and found it does not work easily in practice. Can you add a (few) test(s)? I wonder if this still crashes.

**Comment by ax3l** [comment]
Let's also double-check that users cannot deactivate field output for checkpoints as in:
https://github.com/ECP-WarpX/WarpX/pull/1559/files

**Comment by ax3l** [comment]
@dpgrote can you add to one of the existing examples a few lines in the inputs file that:
- add an additional diagnostics that turns field output off?

Please add this for plotfiles and openPMD, e.g., fine to add in the `laser_ion` example or other physics example. See also https://github.com/ECP-WarpX/WarpX/pull/1559/files where I added an example to CI (that then uncovered crashes at the time).

**Comment by dpgrote** [comment]
Here is the output when running a test case (with DEBUG=TRUE). The error seems to result from creating a MultiFab with zero components.

MPI initialized with 1 MPI processes
MPI initialized with thread support level 3
OMP initialized with 16 OMP threads
AMReX (21.10-24-gb60a773d6c87) initialized
WarpX (19.08-3935-g0cc5eb030f4c-dirty)
PICSAR (c16b642e3dcf)
Level 0: dt = 1.203645751e-15 ; dx = 6.25e-07 ; dy = 6.25e-07 ; dz = 6.25e-07
[gettysburg:54256] *** Process received signal ***
[gettysburg:54256] Signal: Floating point exception: 8 (8)
[gettysburg:54256] Signal code: Integer divide-by-zero (7)
[gettysburg:54256] Failing at address: 0x1080975f5
[gettysburg:54256] [ 0] 0   libsystem_platform.dylib            0x00007fff71dd35fd _sigtramp + 29
[gettysburg:54256] [ 1] 0   ???                                 0x000000020e504268 0x0 + 8830075496
[gettysburg:54256] [ 2] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x0000000108096d56 _ZN5amrex7BaseFabIdEC2ERKNS_3BoxEibbPNS_5ArenaE + 200
[gettysburg:54256] [ 3] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x00000001080919bc _ZN5amrex9FArrayBoxC1ERKNS_3BoxEibbPNS_5ArenaE + 72
[gettysburg:54256] [ 4] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x0000000107ad3de7 _ZNK5amrex17DefaultFabFactoryINS_9FArrayBoxEE6createERKNS_3BoxEiRKNS_7FabInfoEi + 95
[gettysburg:54256] [ 5] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x0000000107db807f _ZN5amrex8FabArrayINS_9FArrayBoxEE9AllocFabsERKNS_10FabFactoryIS1_EEPNS_5ArenaERKNS_6VectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISF_EEE + 387
[gettysburg:54256] [ 6] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x0000000107db5e1c _ZN5amrex8FabArrayINS_9FArrayBoxEE6defineERKNS_8BoxArrayERKNS_19DistributionMappingEiRKNS_7IntVectERKNS_6MFInfoERKNS_10FabFactoryIS1_EE + 1068
[gettysburg:54256] [ 7] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x00000001080a81fa _ZN5amrex8FabArrayINS_9FArrayBoxEEC2ERKNS_8BoxArrayERKNS_19DistributionMappingEiRKNS_7IntVectERKNS_6MFInfoERKNS_10FabFactoryIS1_EE + 358
[gettysburg:54256] [ 8] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x00000001080a39b0 _ZN5amrex8MultiFabC1ERKNS_8BoxArrayERKNS_19DistributionMappingEiRKNS_7IntVectERKNS_6MFInfoERKNS_10FabFactoryINS_9FArrayBoxEEE + 76
[gettysburg:54256] [ 9] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x00000001080a38a4 _ZN5amrex8MultiFabC1ERKNS_8BoxArrayERKNS_19DistributionMappingEiiRKNS_6MFInfoERKNS_10FabFactoryINS_9FArrayBoxEEE + 92
[gettysburg:54256] [10] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x000000010794350a _ZN15FullDiagnostics25InitializeFieldBufferDataEii + 4478
[gettysburg:54256] [11] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x00000001079387cc _ZN11Diagnostics8InitDataEv + 156
[gettysburg:54256] [12] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x0000000107932ea4 _ZN16MultiDiagnostics8InitDataEv + 90
[gettysburg:54256] [13] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x0000000107c61e3f _ZN5WarpX15InitDiagnosticsEv + 41
[gettysburg:54256] [14] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x0000000107c61be9 _ZN5WarpX8InitDataEv + 609
[gettysburg:54256] [15] 0   main3d.gnu.DEBUG.TPROF.MTMPI.OMP.QE 0x00000001078cf396 main + 210
[gettysburg:54256] [16] 0   libdyld.dylib                       0x00007fff71bdacc9 start + 1
[gettysburg:54256] [17] 0   ???                                 0x0000000000000002 0x0 + 2
[gettysburg:54256] *** End of error message ***
Floating point exception: 8

**Comment by dpgrote** [comment]
If I make the hack so that there is one component when creating the MultiFab for `m_mf_output`, I get the following:

  Writing plotfile diags/diag100000
0::Assertion `mf[0]->nComp() == varnames.size()' failed, file "../amrex/Src/Base/AMReX_PlotFileUtil.cpp", line 194 !!!
SIGABRT

**Comment by dpgrote** [comment]
Or, if I skip the setup of the `m_mf_output` MultiFab, I get the following:

  Writing plotfile diags/diag100000
0::Assertion `getBDKey() == m_bdkey' failed, file "../amrex/Src/Base/AMReX_FabArrayBase.cpp", line 2100 !!!
SIGABRT

**Comment by ax3l** [comment]
@atmyers @WeiqunZhang that seems to be a bug in AMReX directly.
Do you know if we can we relax this constrain? We often want to write particles only in full diagnostics.

**Review by RemiLehe — APPROVED** [review]

**Pull request merged**
