### PR TITLE
RZ k-space filtering for spectral solver

### PR DESCRIPTION
**Pull request by dpgrote**
This adds k-space binomial filtering to the RZ spectral solver.

NOTE: This PR includes by necessity all of PR #816 and so should only be merged after then one.

### CODE REVIEW

**Comment by ax3l** [comment]
@dpgrote can you please merge and resolve the latest code conflicts? :)

**Comment by MaxThevenet** [comment]
Oops there are some more conflicts. Could you merge master in there again, please? Thanks!

**Comment by dpgrote** [comment]
@MaxThevenet Done

**Comment by MaxThevenet** [comment]
Thanks for this PR @dpgrote! The implementation of the filter itself looks good, I just have a few questions about the role of each class. If I understand correctly, 
```
class SpectralFieldDataRZ   has a member   BinomialFilter
class SpectralSolverRZ      has a member   SpectralFieldDataRZ
```
and then `PushPSATDSinglePatch` calls `SpectralSolverRZ::ApplyFilter` if `WarpX::use_kspace_filter`.

1. Could all the filter properties be part of the `BinomialFilter` class (is filter ON? is compensation ON?)? This helps encapsulation.
2. Do classes `SpectralFieldDataRZ` and `SpectralSolverRZ` need an `InitFilter` and `ApplyFilter`, or could we delete these and put all of the implementation in `BinomialFilter`? I personally find the chains
   ```
   SpectralSolverRZ::ApplyFilter calls SpectralFieldDataRZ::ApplyFilter
   SpectralFieldDataRZ::ApplyFilter calls BinomialFilter::getFilterArrayR and actually does the filtering
   ```
   a bit difficult to follow. For instance, could we directly call `solver.field_data.ApplyFilter();`, of even something like `solver.field_data.binomial_filter.Apply();`?
3. When is `SpectralSolverRZ::InitFilter` called? I may have missed it.
4. Could you add a test for this feature, or at least call the filter in an existing PSATD test?

@ax3l I would be interested in your opinion on points 1. and 2.

**Comment by dpgrote** [comment]
@MaxThevenet and @ax3l Here are my responses:

1. I was more of less modeling this on how the FDTD filtering is done. There, the filtering flag is in WarpX, `WarpX::use_filter`, as well as a controlling parameter, currently only `WarpX::filter_npass_each_dir`. I think that it is good as it is, that the filter flag is in WarpX and that the filter is only called when it is true. Always calling the filter and having the filter check whether or not it is being applied to me seems awkward and harder to follow. The WarpX::use_filter_compensation could be moved to the BinomialFilter class, but would that mean querying the parameter from the class? Also, the FDTD could use the same parameter, though compensation is not now implemented.

2. My intent was to write the code so that additional similar filters could be easily implemented. Now, the BinomialFilter class only generates the filter profiles. SpectralFieldDataRZ applies the filter since it know about the structure of the fields. Perhaps a more general way to do this is to have the BinomialFIlter do the PARALLELFOR over the FAB and have SpectralFieldDataRZ call that in a loop over the MultiFabs. Note that the SpectralFieldDataRZ needs to have an InitFilter routine since it needs to do the loop over the MultiFabs. As it is now, the SpectralSolver class already has pass through calls to SpectralFieldDataRZ for the transforms. This follows that pattern.

3. The filter is supposed to be initialized in WarpX.cpp right after the spectral solver instance is created. Those lines got deleted in one of the many conflict fixes that happened around those lines. I'll fix this (but see my comment below).

4. I need to do the first part yet, add a test for the PSATD. It's on the todo list but is complicated because of the need of blas++ and lapack++ packages. Does travis know about spack, which would presumably make is easier to install blas++ and lapack++?

NOTE: I'm going to close this PR and open a new, clean one. There were multiple merge conflict fixes and there is a long list of commits listed above not related to this commit. I don't trust that there might be something corrupted here.

**Pull request closed without merging**
