### PR TITLE
Cleanup binary collision

### PR DESCRIPTION
**Pull request by dpgrote**
This is a small cleanup, removing duplicated code in the binary collision code.

### CODE REVIEW

**Comment by mhaseeb123** [comment]
Hi folks, I am out of state until Wednesday for a funeral. I will take a look at this on return.

**Comment by ax3l** [comment]
Hi Haseeb, I am so sorry to hear. Take the time you need please.

**Comment by JustinRayAngus** [comment]
This PR looks good to me.

**Review by JustinRayAngus — APPROVED** [review]

**Review by ax3l — APPROVED** [review]
Took a look on my laptop now. This looks good to me, thanks Dave! :sparkles:

**Pull request merged**
