### PR TITLE
AMReX/pyAMReX/PICSAR: weekly update

### PR DESCRIPTION
**Pull request by EZoni**
- Weekly update to latest AMReX:
```console
./Tools/Release/updateAMReX.py
```
- Weekly update to latest pyAMReX:
```console
./Tools/Release/updatepyAMReX.py
```
- Weekly update to latest PICSAR (no changes):
```console
./Tools/Release/updatePICSAR.py
```

### CODE REVIEW

**Review by WeiqunZhang — APPROVED** [review]

**Comment by WeiqunZhang** [comment]
Looks like WarpX's NamedComponentParticleContainer needs an update. AddRealComp(const std::string& name, ...) exists now in AMReX.

**Comment by EZoni** [comment]
@atmyers 

I renamed the WarpX functions `AddIntComp` and `AddRealComp`, defined in `Source/Particles/NamedComponentParticleContainer.H`, as `NewIntComp` and `NewRealComp`, respectively, in order to avoid confusion with the AMReX functions of the same name, defined in `Src/Particle/AMReX_ParticleContainer.H`.

Does this look good to you? There are only two instances left where we are directly calling the AMReX functions from WarpX, without wrapping them in WarpX functions.

It's not clear to me whether the goal of recent PRs such as https://github.com/AMReX-Codes/amrex/pull/4163 was to remove the WarpX functions and use directly the AMReX ones.

**Comment by EZoni** [comment]
@atmyers 

Also, in WarpX's newly renamed functions `NewIntComp` and `NewRealComp` we call the AMReX functions `AddIntComp` and `AddRealComp` by passing only the boolean `comm` flag. I have not changed this in this PR. However, I'm wondering if we are supposed to be passing also the name strings when we call those AMReX functions.

**Comment by EZoni** [comment]
Discussed on Slack: 
@atmyers will open a PR to call the new AMReX functions and remove `NamedComponentParticleContainer` from WarpX.

**Comment by EZoni** [comment]
Rebase after #5399 to pass the `macOS / AppleClang` check.

**Review by atmyers — APPROVED** [review]

**Comment by EZoni** [comment]
@dpgrote
 
I just disabled auto-merge here, please feel free to review and suggest further changes as in #5401 if you see that something is missing.

Here we decided to rename the WarpX functions, since we thought it creates less confusion with the AMReX functions, until the permanent change (which will remove the WarpX functions) is implemented.

**Review by dpgrote — APPROVED** [review]
This looks good, thanks!
Changing the names of the routines is fine since this is only a temporary fix until they are ultimately removed.

**Pull request merged**
