### PR TITLE
Adding Amrex Bucket into WarpX Python interface.

### PR DESCRIPTION
**Pull request by clarkse**
This PR adds the Amrex bucket into the Python WarpX interface to allow setting of Amrex parameters from the PICMI input scripts.

- [x] PICMI-like options used
- [x] user-facing documentation

### CODE REVIEW

**Comment by dpgrote** [comment]
Which amrex parameters do you need to set?

**Comment by clarkse** [comment]
> 

In WSL, I need to set amrex.the_arena_is_managed=0, and amrex.the_arena_init_size, as when the arena is not managed, the default arena memory allocation oversubscribes the GPU if using more than one MPI process/GPU.

**Comment by dpgrote** [comment]
Ok. It would be more PICMI like if these were added as arguments to the `Simulation` class in `picmi.py`. See for example how the argument `warpx_amr_check_input` is setup. You would add arguments `warpx_amrex_the_arena_is_managed` and `warpx_amrex_the_arena_init_size`.

**Comment by clarkse** [comment]
@dpgrote I have added the PICMI like interface.

**Review by dpgrote — APPROVED** [review]
This looks good to me. Thanks!

**Review by ax3l — DISMISSED** [review]
Awesome!

As a last step, can you please add the new options in the user-facing docs?
`Docs/source/usage/python.rst` builds the page https://warpx.readthedocs.io/en/latest/usage/python.html

**Comment by ax3l** [comment]
(oops, did not mean to approve yet)

**Comment by clarkse** [comment]
> (oops, did not mean to approve yet)

@ax3l It appears the docs pull from the inline comments in picmi.py.  I do see anything that I should be changing in the python.rst file.  I built the docs locally and they appear to have updated appropriately.  

image

**Comment by ax3l** [comment]
Oh, cool! That makes sense :)

**Review by ax3l — APPROVED** [review]

**Pull request merged**
