### PR TITLE
template Parser so that it works for any number of variables

### PR DESCRIPTION
**Pull request by WeiqunZhang**
`GpuParser` and its' wrapper `ParserWrapper` are now templated with the number of variables.  They now work with any number of variables.  `ParallelFor` that uses the parser no longer needs to use GPU shared memory.

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
All regression tests on battra and garuda have passed.

**Comment by WeiqunZhang** [comment]
We could make `InjectorDensity` and `InjectorMomentum` take x, y, z, and t.  But then the question is what we should do to ParmParse parameters like `parse_density_function`.

```
    } else if (rho_prof_s == "parse_density_function") {
        Store_parserString(pp, "density_function(x,y,z)", str_density_function);
        // Construct InjectorDensity with InjectorDensityParser.
        inj_rho.reset(new InjectorDensity((InjectorDensityParser*)nullptr,
                                          makeParser(str_density_function,{"x","y","z"})));
```

Should this be changed to

```
    } else if (rho_prof_s == "parse_density_function") {
        Store_parserString(pp, "density_function(x,y,z)", str_density_function);
        // Construct InjectorDensity with InjectorDensityParser.
        inj_rho.reset(new InjectorDensity((InjectorDensityParser*)nullptr,
                                          makeParser(str_density_function,{"x","y","z","t"})));
```

or 

```
    } else if (rho_prof_s == "parse_density_function") {
        Store_parserString(pp, "density_function(x,y,z,t)", str_density_function);
        // Construct InjectorDensity with InjectorDensityParser.
        inj_rho.reset(new InjectorDensity((InjectorDensityParser*)nullptr,
                                          makeParser(str_density_function,{"x","y","z","t"})));
```

The latter is more consistent.  But it will break a lot of inputs files.

**Comment by MaxThevenet** [comment]
Is there difference between the second and the third code snippet?

**Comment by WeiqunZhang** [comment]
Mabye we can do that in a separate pull-request.

**Comment by MaxThevenet** [comment]
agreed.

**Comment by RevathiJambunathan** [comment]
Thank you @WeiqunZhang :)

**Pull request merged**
