### PR TITLE
Minor bugfix for photon push

### PR DESCRIPTION
**Pull request by atmyers**
In case we ever want to do QED + BTD + subcycling.

### CODE REVIEW

**Comment by atmyers** [comment]
I don't understand the CI failure - it seems to have something to do with openPMD?

**Comment by MaxThevenet** [comment]
Maybe @ax3l has an idea. It would probably affect all PRs.

**Comment by ax3l** [comment]
Upsi, I merged a upgrade today and did not run ICC yet on it. Thx, fixed!

**Comment by ax3l** [comment]
Hm, that's an ICC bug. Reported as bug number 04651484 in the Intel Developer Zone... Will update soon.

**Comment by ax3l** [comment]
ICC work-around applied. Will restart the CI jobs in open PRs now (again) :)
https://github.com/openPMD/openPMD-api/pull/744

**Pull request merged**
