### PR TITLE
CI: build tests with `-g1` compile option

### PR DESCRIPTION
**Pull request by EZoni**
Build and run CI tests with more debug information by adding the `-g1` compile option.

### CODE REVIEW

**Comment by EZoni** [comment]
I injected manual crashing and tested that the backtrace files display line numbers as expected. For example, see logs at https://dev.azure.com/ECP-WarpX/WarpX/_build/results?buildId=19698&view=results.

**Comment by EZoni** [comment]
Note that #2979 attempted to do the same a couple of years ago, but ran into problems related to cache size. 

We might be close to the limit here too (see screenshot), but let's see if we can go ahead as is for now.

Screenshot from 2024-11-06 15-41-20

**Comment by WeiqunZhang** [comment]
We could use `-g1`.

**Comment by EZoni** [comment]
@WeiqunZhang 

Thanks, using `-g1` seems to have resolved the cache size issue and it should still print out file names and line numbers in backtrace files. I think this PR is ready to review/merge.

**Review by WeiqunZhang — APPROVED** [review]

**Pull request merged**
