### PR TITLE
Crash if deprecated input parameters are used.

### PR DESCRIPTION
**Pull request by MaxThevenet**
This PR proposes to query deprecated input parameters from the input file, and return a useful message when found (typically: this option is deprecated, please use ...).

### CODE REVIEW

**Review by ax3l — APPROVED** [review]
Great approach, thank you! :sparkles:

**Comment by ax3l** [comment]
@dpgrote @MaxThevenet is PICMI still using some of the old arguments (see CI crash)?

**Comment by MaxThevenet** [comment]
I do not know why tests fail, I think pywarpx shouldn't use old arguments but there seems to be a hiccup somewhere.

**Comment by MaxThevenet** [comment]
Just merged master in here, again, but I don't see how it could fix the issue. Maybe last time tests ran, `pip install picmi` provided an outdated version that should be fixed now... Just speculating.

**Comment by dpgrote** [comment]
This will need PR #984 to work. That PR is updating the PICMI interface for the diagnostics for particles and removes the old input parameters. It is having it's own problems however, but I'm not sure what's happening yet.

**Pull request merged**
