### PR TITLE
[WIP] Reduce python regression sizes

### PR DESCRIPTION
**Pull request by dpgrote**
This PR reduces the sizes of the resulting plot files to around 10 MB or smaller, while still passing the regression tests.

Related to #855

### CODE REVIEW

**Review by MaxThevenet — APPROVED** [review]

**Comment by MaxThevenet** [comment]
Great, thanks for this PR! Before merging it, could you make sure that all Python tests that it touches are currently passing on Battra? Of one is failing, let us first address it and then merge this PR (as this PR will break them anyway), so that we're sure there's no bug slipping through our fingers.

**Comment by dpgrote** [comment]
I checked Python_LaserAcceleration and it is Ok. The errors are machine precision. The relative error of one of the B fields is large, but this is ignorable since that field should be near zero. I've updated the input file to not write out the small fields. I did the same for the MR test.

There is a bug that is causing Python_Langmuir_rz_multimode to fail. However, I have this fixed in the RZ spectral PR. Should I submit a separate PR or wait until the spectral is merged in?

**Comment by MaxThevenet** [comment]
Thanks for checking this!
The best thing would be to extract the bug fix from the spectral RZ PR. If this is doable, we could merge the small bug fix first and then this one. Otherwise, we could merge this PR soon I think.

**Comment by dpgrote** [comment]
Unfortunately, the fix was made in a commit with many other changes. Presumably, I could still submit a separate PR and then have to merge that into the RZ spectral PR.

**Comment by MaxThevenet** [comment]
Ok sounds good, let' not modify the RZ spectral PR for external reasons now that Rémi has reviewed it.
So if we assume the current benchmark is correct for Python_Langmuir_rz_multimode, I feel like if we merge this PR we will never be able to check if the RZ spectral PR does fix the test on Battra.
One way to go would be to merge the RZ spectral PR, make sure that the Battra tests pass again, and then merge this PR (which will break the Battra tests, but is simple enough that we can make sure it dpesn't break the code, so we can safely reset the benchmark). Does this make sense? As much as possible, let's try to make PRs as small as possible, with 1 topic per PR, as it greatly simplifies both the review and this kind of gymnastic.

**Comment by dpgrote** [comment]
I think it would be simplest for me to submit a mini-PR to fix the bug. It will be easier to verify that things are working probably one step at a time. Once the bug fix is merged in, I can merge it into the RZ spectral PR and fix any conflicts. I'll do that.

**Comment by MaxThevenet** [comment]
Thanks, is this #866?

**Comment by dpgrote** [comment]
Yes, #866

**Comment by MaxThevenet** [comment]
DO NOT MERGE until reg tests pass on master.

**Comment by dpgrote** [comment]
This is out of date and no longer needed with the new use of checksums.

**Pull request closed without merging**
