### PR TITLE
Plot raw fields: fix bugs for rho and F data

### PR DESCRIPTION
**Pull request by EZoni**
I believe this fixes a bug for the raw rho data, when `<diag_name>.plot_raw_fields = 1`. The function `getF_fp` was used instead of `getrho_fp`.

### CODE REVIEW

**Comment by dpgrote** [comment]
Good catch! This definitely looks like an error. This seems to follow Axel's dictum from this morning's meeting - if it is not tested, assume it is buggy.

**Comment by EZoni** [comment]
Question:

I think the user cannot control the output of raw rho data with the current implementation. The default is assigned here
https://github.com/ECP-WarpX/WarpX/blob/c43b49c74a2c0740fd35cba39e49411a3115c6bd/Source/Diagnostics/FullDiagnostics.H#L20-L21
but the value of `m_plot_raw_rho` is not read, hence possibly overwritten, through the parser. The place where this should be done is probably here
https://github.com/ECP-WarpX/WarpX/blob/c43b49c74a2c0740fd35cba39e49411a3115c6bd/Source/Diagnostics/FullDiagnostics.cpp#L61-L62

Do we want to set `m_plot_raw_rho = true` by default, or do we want to keep the current default but add an input parameter `<diag_name>.plot_raw_rho`? I would be fine with setting `m_plot_raw_rho = true` by default, since this is anyways a feature used mainly for development and debugging purposes.

**Comment by dpgrote** [comment]
The OpenPMD writer does an assert that plot_raw_rho is false, so it shouldn't default to true. I would add a pp.query for it so that the user can set it.

Note that rho_fp is not always allocated so the Plotfile writer should check that rho_fp is allocated before trying to write it.

**Comment by EZoni** [comment]
@dpgrote Thanks for pointing out that `m_plot_raw_rho` cannot default to `true`, in order to be compatible with the openPMD writer. I added a query for it. Regarding the suggestion to check that `rho_fp` is allocated before writing it, wouldn't it make more sense, from a software design perspective, to perform such a check in the getter `getrho_fp` itself? It would seem reasonable to me that a getter returns the reference to a given object if the object exists or throws an error if the object does not exist.

**Comment by dpgrote** [comment]
I see your point. The check can go in either place. Do you think the code should exit if plot_raw_rho is true and rho_fp is not allocated? I think it would be ok to silently ignore that case. But a check is needed to avoid a segfault.

While looking into this, I noticed another small possible error, in the routine FlushFormatPlotfile::WriteAllRawFields. At the end of the routine, there is an if (lev > 0), but there are calls to write the coarse F and rho outside the if block. It seems like they should be inside the if block.

**Comment by EZoni** [comment]
@dpgrote Thank you for your comments. I fixed the error with the coarse patch and added locally the checks that we discussed. The code now ignores silently the case where `plot_raw_rho` is `true` but `rho_fp` is not allocated, and writes a warning to the standard output. Whether the getters in our `WarpX` class should throw an error if their objects are not allocated is something that should probably be discussed in our developers meeting.

**Comment by dpgrote** [comment]
@EZoni Thanks for making the updates! For completeness, the same changes can be made for plot_raw_F as well. It has the same issue that F_fp is not always allocated.

**Review by dpgrote — APPROVED** [review]
Thanks for the fixes!

**Pull request merged**
