### PR TITLE
Fix to RZ scalar moving window

### PR DESCRIPTION
**Pull request by LDAmorim**
Hi all,
I am not sure if this is the smartest way to solve the incompatibility between codes and PICMI  in the definition of the moving window velocity.
But I decided to already prepare this PR in case you think it is a good approach.
Please feel free to ask for changes to/delete this PR if you don't think so.

With this PR, WarpX users can follow the PICMI standard instructions in:
https://picmi-standard.github.io/standard/grid.html#picmistandard.PICMI_CylindricalGrid
regarding the ***scalar*** parameter `moving_window_velocity` that is described in the Cylindrical geometry section as:
```
moving_window_velocity: Moving frame Z velocity [m/s]
```

Then WarpX uses the PICMI variable to determine the input parameters:
```
warpx.do_moving_window = 1
warpx.moving_window_dir = z
warpx.moving_window_v = moving_window_velocity/c
```

The code breaks with an error message if the user sets the PICMI `moving_window_velocity` parameter as a ***vector*** (instead of a ***scalar***).

### CODE REVIEW

**Comment by dpgrote** [comment]
Thanks for pointing this out. I think it would be ok to assume that a scalar was input, so there's no need to check isscalar. Perhaps the picmi standard should be changed and the name made more precise to be moving_window_zvelocity.

**Comment by LDAmorim** [comment]
Thanks for the comment @dpgrote!
I was thinking of a user who was using a script in 3D and then passing it to RZ. In that case `moving_window_velocity` should be changed from ***vector*** to ***scalar***, but the user might not notice it.
Changing the name is also an option, but I think only necessary for RZ.

**Comment by dpgrote** [comment]
Changing the name for RZ makes it clear that this argument is different than the arguments in 2D and 3D. I'll go ahead and suggest the change in PICMI.

**Comment by LDAmorim** [comment]
The latest commits allow the users to run a picmi script in RZ geometry with the parameter `moving_window_zvelocity` set by the  PICMI standard as a scalar (corresponding to the velocity in z direction).

**Comment by dpgrote** [comment]
This looks good.

**Comment by RemiLehe** [comment]
Thanks for this PR! Could you please fix the style error (end-of-line whitespace)?

**Comment by RemiLehe** [comment]
Actually, nevermind: I just did it.

**Comment by LDAmorim** [comment]
Thank you Rémi!
And sorry for the EOL whitespace error.

**Pull request merged**
