### PR TITLE
Compile-time option to use `algo.load_balance_costs_update = gpuclock` 

### PR DESCRIPTION
**Pull request by mrowan137**
This PR introduces a compile-time option `USE_GPUCLOCK` that must be active to enable use of the option `algo.load_balance_costs_update = gpuclock`.  This can relieve register pressure in the current deposition functions when not using `gpuclock`.  We see e.g. in the function 
```
_ZN5amrex13launch_globalIZNS_11ParallelForIlZ27doEsirkepovDepositionShapeNILi3EEvRK19GetParticlePositionPKdS7_S7_S7_PKiRKNS_6Array4IdEESD_SD_ldRKSt5arrayIdLm3EESF_NS_4Dim3EdiPdlEUllE_vEENSt9enable_ifIXsr5amrex19MaybeDeviceRunnableIT0_vEE5valueEvE4typeERKNS_3Gpu10KernelInfoET_OSM_EUlvE_EEvST_
```
that compiling with `KernelTimer`s can increase register usage:
```
No KnlTimer:
    (Esirkepov) ptxas info    : Used 72 registers, 736 bytes cmem[0], 24 bytes cmem[2]
Yes KnlTimer
    (Esirkepov) ptxas info    : Used 76 registers, 760 bytes cmem[0], 24 bytes cmem[2]
```

This change requires that if using the option `algo.load_balance_costs_update = gpuclock`, the code should be compiled with `USE_GPUCLOCK=TRUE` (info which is now included in documentation).  If a `KernelTimer` object is constructed without `USE_GPUCLOCK=TRUE` the code aborts with an instructive error message.

### CODE REVIEW

**Review by ax3l — APPROVED** [review]
LGTM. We were still unsure if we should disable those again by default, as proposed in the current state of this PR.

We will base it on the performance of @atmyers's KPP runs (which in current `development` include the new GPU timers that add 4 registers to each instrumented kernel), if we should deactivate them by default.

In our extensive tests on the laser-ion acceleration example, we did not see a significant performance penalty.

**Comment by ax3l** [comment]
@mrowan137 this needs a little rebase because of #1856

**Comment by mrowan137** [comment]
@ax3l This was rebased!

**Comment by ax3l** [comment]
I just saw the latest FOM from @atmyers and it looks like we got faster again.
Assuming @atmyers used a very recent version of WarpX (can you confirm that? which commit did you run for the FOM? :) ), I would say we keep the option here to ON by default.

**Comment by atmyers** [comment]
I used the following versions:

AMReX (21.03-68-g92945ad3a356) initialized
WarpX (21.03-79-g106a228725cc)
PICSAR (b35f07243c51

**Comment by ax3l** [comment]
Thank you, with 106a228725cc6398b0b86e92027e53546d9b26db we have essentially all the new instrumentation included. Cool!

**Pull request merged**
