### PR TITLE
Release 24.05

### PR DESCRIPTION
**Pull request by ax3l**
Prepare the May release of WarpX:
```bash
# update dependencies
./Tools/Release/updateAMReX.py
./Tools/Release/updatePICSAR.py  # no changes, still 23.09
./Tools/Release/updatepyAMReX.py
# bump version number
./Tools/Release/newVersion.sh
```

Following this workflow: https://warpx.readthedocs.io/en/latest/maintenance/release.html

### CODE REVIEW

**Comment by ax3l** [comment]
The `Python_restart_eb` test shows a different checksum as we pull in AMReX `24.05`.
To clarify tomorrow if that comes from a expected upstream fix/change in AMReX and is safe to reset or if it is a regression.

**Comment by WeiqunZhang** [comment]
I believe it's expected due to AMReX changes in 3D EB generation.

**Comment by ax3l** [comment]
Agreed, could be from https://github.com/AMReX-Codes/amrex/pull/3912 and related changes.

**Review by lucafedeli88 — APPROVED** [review]
If the small changes in the Python restart EB checksum are expected I think that this PR can be accepted.

**Pull request merged**
