### PR TITLE
Synchronize GPU before stopping profile timer

### PR DESCRIPTION
**Pull request by AlexanderSinn**
This PR fixes the `WARPX_PROFILE()` macros to also call `amrex::Gpu::synchronize()` before exiting a profiled section of code. 

Previously it was only called before entering, leading to inaccurate measurements for functions launching GPU kernels without synchronizing.

The name of the option was updated accordingly from `warpx.do_device_synchronize_before_profile` to:
```
warpx.do_device_synchronize = 1
```
Test:
` ~/WarpX/build/bin/warpx.3d.MPI.CUDA.SP.QED ~/WarpX/Examples/Physics_applications/plasma_acceleration/inputs_3d_boost warpx.do_device_synchronize = 1`

[old_synchronize_0.txt](https://github.com/ECP-WarpX/WarpX/files/7339106/old_synchronize_0.txt)
[old_synchronize_1.txt](https://github.com/ECP-WarpX/WarpX/files/7339107/old_synchronize_1.txt)
[new_synchronize_0.txt](https://github.com/ECP-WarpX/WarpX/files/7339104/new_synchronize_0.txt)
[new_synchronize_1.txt](https://github.com/ECP-WarpX/WarpX/files/7339105/new_synchronize_1.txt)

1. The behavior between the old `warpx.do_device_synchronize_before_profile = 0` and new `warpx.do_device_synchronize = 0` is unchanged (no calls of `amrex::Gpu::synchronize()`).
2. The old `warpx.do_device_synchronize_before_profile = 1` underreports the time for e.g. `Filter::ApplyStencil(FArrayBox)`. With the new `warpx.do_device_synchronize = 1` it is profiled as 1.467s instead of 0.2812s.

If synchronizing is known to take a significant amount of time for a particular function, the `WARPX_DETAIL_PROFILE()` macros can be used. These only synchronize if  `warpx.do_device_synchronize = 2` or greater. This is currently not used as I didn't know where this would be applicable.

### CODE REVIEW

**Review by MaxThevenet — APPROVED** [review]
Thanks for this PR! In your example `PhysicalParticleContainer::Evolve` was the 2nd most time-consuming function (2.1 s) with the old implementation with and without the `device_synchronize`, while it ranks 6th (1.2 s) in the new implementation with `device_synchronize`, so indeed there are several large differences, at least in this small example.

**Comment by ax3l** [comment]
@AlexanderSinn @MaxThevenet thanks a lot for this!

With the old (fragile/incorrect) implementation, we know that the overhead from all the additional syncs is quite minimal/negligible. Did you do a runtime test over a few GPU nodes to check the impact on a production simulation from having this default-on option modified to sync more by now?

What I mean is overall runtime (walltime or time-to-solution) of the simulation.

**Comment by ax3l** [comment]
Discussed via Slack: we have not yet done a performance test on this. On a small test, the overhead was 6-7% but not systematically tested yet.

I think we should double check this with our KPP to see if the assumption

> * ``warpx.do_device_synchronize`` (`int`) optional (default `1`)
    When running in an accelerated platform, whether to call a deviceSynchronize around profiling regions.
    This allows the profiler to give meaningful timers, but (hardly) slows down the simulation.

is still true.

**Comment by ax3l** [comment]
@atmyers on Slack:
> I re-ran the KPP with the PR, on 320 nodes. The result was basically the same (to within 1%) as the last time I ran it, on 9/2/2021

**Comment by MaxThevenet** [comment]
Very interesting, thanks for the large test! Does it mean that the runtime is the same within 1%, or that the TinyProfiler time in each function is the same to within 1%?

**Comment by atmyers** [comment]
I mean that the total runtime is the same, I didn't compare individual timers.

**Comment by kngott** [comment]
Actually, that's a interesting question: does this change alter any of the profiling in the KPP? If not, we might have a correct synching pattern for this and no overall effect, but the discrepancy is appearing in other situations and we need to test on one of those.

**Pull request merged**
