### PR TITLE
Reorganize examples

### PR DESCRIPTION
**Pull request by MaxThevenet**
In this PR we do some more cleaning on the Example files, mostly in `Examples/Physics_applications/`.

Each folder now contains at least one 2d and one 3d input file that are physically meaningful. Overall, there should be at least one input file in `Examples/Physics_applications/` for each feature presented in `Examples/Modules/`.

The regression tests run using these input files. In order them not to take too much time, more parameters are passed at execution in `Regression/WarpX-tests.ini`, like `runtime_params = warpx.do_dynamic_scheduling=0 amr.n_cell=32 32 256 max_step=100 electrons.zmin=0.e-6`.

### CODE REVIEW

**Comment by RemiLehe** [comment]
Thanks for this PR @MaxThevenet!
If this is ready to merge, could you remove the `[WIP]` flag and add a quick description?

**Comment by MaxThevenet** [comment]
Sure, I'll add a 2d example for uniform plasma, write a short description for this PR and remove the [WIP] flag.

**Comment by MaxThevenet** [comment]
The PR is ready for review.

**Comment by RemiLehe** [comment]
Thanks a lot for cleaning this up @MaxThevenet! ✨  
I just updated the documentation accordingly.

**Pull request merged**
