### PR TITLE
Add UB sanitizer CI test

### PR DESCRIPTION
**Pull request by lucafedeli88**
This PR adds an Undefined Behavior sanitizer test in CI (see https://releases.llvm.org/15.0.0/tools/clang/docs/UndefinedBehaviorSanitizer.html for more details).

The PR also fixes a bug found with the UB sanitizer.

### CODE REVIEW

**Review by roelof-groenewald — COMMENTED** [review]
It's cool that the new check found a possible bug in execution here. I wonder, though, if it wouldn't make more sense to add
```
if (np == 0) { return; }
```
at line 79 of `FieldProbeParticleContainer.cpp` instead of skipping over the part that creates new particles.

**Comment by lucafedeli88** [comment]
> It's cool that the new check found a possible bug in execution here. I wonder, though, if it wouldn't make more sense to add
> 
> ```
> if (np == 0) { return; }
> ```
> 
> at line 79 of `FieldProbeParticleContainer.cpp` instead of skipping over the part that creates new particles.

I agree with you. However, we still need to call `Redistribute();`, since it is a collective operation.
I've added these lines:

```
    if (np <= 0){
        Redistribute();
        return;
    }
```

**Review by roelof-groenewald — APPROVED** [review]
Thanks for updating!

**Comment by ax3l** [comment]
Cool, thx! :)

**Pull request merged**
