### PR TITLE
rocFFT support

### PR DESCRIPTION
**Pull request by WeiqunZhang**

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
@ax3l Could you add cmake support either to this PR or with another PR?

**Comment by ax3l** [comment]
Thank you for the ping!
I will do the CMake update once we merged https://github.com/AMReX-Codes/amrex/pull/1316 - this one should be soon ready :)

I can do this in a follow-up PR.

**Review by ax3l — APPROVED** [review]
Thanks a lot!
(Little CI hickup with the latest CUDA release.)

**Comment by dpgrote** [comment]
Thanks for the new capability! Can you make the same changes in the RZ spectral solver? The changes would be in Source/FieldSolver/SpectralSolver/SpectralFieldDataRZ.cpp. The fft calls there were not added to the AnyFFT since the structure is quite different.

**Comment by WeiqunZhang** [comment]
@dpgrote Will do it.

**Comment by WeiqunZhang** [comment]
I have modified the 2d RZ spectral solver for rocfft.  It passes the Langmuir_multi_rz_psatd test.

**Review by ax3l — APPROVED** [review]
Thanks a lot, looks great!

**Comment by ax3l** [comment]
re-starting CI on Azure

**Review by RemiLehe — APPROVED** [review]

**Pull request merged**
