### PR TITLE
Refactor Current Correction Functions

### PR DESCRIPTION
**Pull request by EZoni**
In order to implement the current correction for the formulation of the PSATD equations with the assumption that J is linear in time and rho quadratic (see #2730), we cannot use the old interface of the function `CurrentCorrection`, which was getting as inputs the current and charge arrays in real space and performing ad hoc FFTs before applying the correction. When J is linear in time and rho is quadratic, we do not store three components of rho in real space, but only in spectral space. On the contrary, when J is constant in time and rho is linear, we do store two components of rho both in real space and spectral space. I think this refactoring should allow us to handle this inconsistency (due to the fact that the two versions of the PIC loop were implemented at different times).

With this PR we do the current correction right before pushing the fields in spectral space, the FFTs of J and rho have been already performed outside of the current correction kernel, and the backward FFT of J is performed outside as well, with a new function `PSATDBackwardTransformJ` (similar to other exisiting functions for the E and B fields). This should allow us to implement the `CurrentCorrection` kernel (with the new interface coded here) for the derived class `PsatdAlgorithmJLinearInTime` using the three components of rho in spectral space that already exist right before the field solve.

### CODE REVIEW

**Comment by EZoni** [comment]
The reason why the RZ test `galilean_rz_psatd_current_correction` fails, while `Langmuir_multi_rz_psatd_current_correction` passes, is that the former has filtering while the latter doesn't.

With filtering, the old and new codes compare as follows.

Old code:
- Deposit J
- `PsatdAlgorithmGalileanRZ::CurrentCorrection`:
  - FFT of J **without** filtering
  - Correct J in Fourier space
  - FFT^(-1) of J (so that the current correction is reflected in the diags)
- `PSATDForwardTransformJ`:
  - FFT of J **with** filtering
- Push fields in Fourier space

New code:
- Deposit J
- `PSATDForwardTransformJ`:
  - FFT of J **with** filtering
- `PsatdAlgorithmGalileanRZ::CurrentCorrection`:
  - Correct J in Fourier space
- `PSATDBackwardTransformJ`:
  - FFT^(-1) of J (so that the current correction is reflected in the diags)
- Push fields in Fourier space

So in the old code there were two FFTs of J and the filtering was done after the current correction in Fourier space, while in the new code there is only one FFT of J and the filtering is done before the current correction in Fourier space. This does not seem to affect charge conservation, since the physics check on that passes in the Python analysis (only the checksum values are different for J, because of the differences just described here).

@dpgrote Do you have objections against the new version of the code?

**Review by RemiLehe — APPROVED** [review]

**Comment by EZoni** [comment]
@RemiLehe @dpgrote After a discussion with Remi regarding the failing test `galilean_rz_psatd_current_correction`, I can confirm that if I turn filtering off there is no difference between the checksums produced by this branch and the checksums produced by the `development` branch (as there is no difference for the test `Langmuir_multi_rz_psatd_current_correction`, where filtering is also off). It's still not fully clear why doing current correction on J and rho unfiltered and the filtering is not equivalent to doing current correction on J and rho filtered, but I think the observation I reported here is anyways pointing towards the fact that filtering is what's causing the discrepancy here.

**Comment by EZoni** [comment]
@RemiLehe @dpgrote Another confirmation that this is about filtering (whether it's done before or after the current correction). The code pasted below, extracted from a local modification of WarpXPushFieldsEM.cpp, reproduces the behavior of the old code, before this PR: the final lines commented out are the actual new lines introduced in this PR, and the `true`/`false` additional arguments passed to the forward FFTs control whether filtering is done or not for that particular FFT. In other words, this mimics the old code but using the new functions introduced in this PR. Such code makes the Galilean test pass without checksum changes.
```cpp
    PSATDForwardTransformJ(false);
    PSATDForwardTransformRho(0,0,false); // rho old
    PSATDForwardTransformRho(1,1,false); // rho new
    PSATDCurrentCorrection();
    PSATDBackwardTransformJ();

    PSATDForwardTransformEB();
    PSATDForwardTransformJ(true);

    // Do rho FFTs only if needed
    if (WarpX::update_with_rho || WarpX::current_correction || WarpX::do_dive_cleaning)
    {
        PSATDForwardTransformRho(0,0,true); // rho old
        PSATDForwardTransformRho(1,1,true); // rho new
    }

    //// Correct the current in Fourier space so that the continuity equation is satisfied, and
    //// transform back to real space so that the current correction is reflected in the diagnostics
    //if (WarpX::current_correction)
    //{
    //    PSATDCurrentCorrection();
    //    PSATDBackwardTransformJ();
    //}
```
At this point I think we should just decide whether we agree or not on the fact that the new code of this PR (see description in https://github.com/ECP-WarpX/WarpX/pull/2839#issuecomment-1035434335, not the code pasted above!) does what we believe is correct. Which I think is the case, since I do not see reasons for the current correction to be done necessarily on the unfiltered J and rho, as in the old code. Any thoughts on your side?

**Review by dpgrote — APPROVED** [review]
The changes look good.

**Pull request merged**
