### PR TITLE
[mini-PR] Bug fix in ApplyInverseVolumeScalingToCurrentDensity

### PR DESCRIPTION
**Pull request by dpgrote**
A bug was added in the previous change that generalized the centering for the routine applying the inverse volume scaling to the current.

### CODE REVIEW

**Comment by MaxThevenet** [comment]
A weird error occurs for the checks. The raw log shows
```
2020-03-30T16:37:37.8667492Z Resolving deltas: 100% (27539/27539), done.
2020-03-30T16:37:38.9382236Z From https://github.com/ECP-WarpX/WarpX
2020-03-30T16:37:38.9383930Z  * [new branch]      master     -> origin/master
2020-03-30T16:37:38.9401406Z  * [new tag]         18.11      -> 18.11
2020-03-30T16:37:38.9415036Z  * [new tag]         19.02      -> 19.02
2020-03-30T16:37:38.9415796Z  * [new tag]         19.04      -> 19.04
2020-03-30T16:37:38.9416313Z  * [new tag]         19.05      -> 19.05
2020-03-30T16:37:38.9416770Z  * [new tag]         19.06      -> 19.06
2020-03-30T16:37:38.9417228Z  * [new tag]         19.08      -> 19.08
2020-03-30T16:37:38.9417683Z  * [new tag]         19.10      -> 19.10
2020-03-30T16:37:38.9418130Z  * [new tag]         20.01      -> 20.01
2020-03-30T16:37:38.9418733Z  * [new tag]         20.02      -> 20.02
2020-03-30T16:37:38.9419169Z  * [new tag]         20.03      -> 20.03
2020-03-30T16:37:38.9533815Z ##[command]git checkout --progress --force dd7dcfbe08f798f657361bfea30f76766d6f4100
2020-03-30T16:37:38.9559416Z ##[error]fatal: reference is not a tree: dd7dcfbe08f798f657361bfea30f76766d6f4100
2020-03-30T16:37:38.9582321Z Removed matchers: 'checkout-git'
2020-03-30T16:37:38.9583142Z ##[error]Git checkout failed with exit code: 128
2020-03-30T16:37:38.9879929Z ##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.165.2/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
2020-03-30T16:37:39.0178958Z Cleaning up orphan processes
```
Do you know what's happening? Is this branch still valid on your fork?

**Comment by ax3l** [comment]
just for tracking: can you mention the PR number that introduced the bug? #... is enough

**Comment by dpgrote** [comment]
The bug was introduced in PR #772

**Comment by MaxThevenet** [comment]
Was this a fix to Battra test `Python_Langmuir_rz_multimode`? If so, could you check that it did? I do not see a difference in the last Battra runs https://ccse.lbl.gov/pub/RegressionTesting/WarpX/

**Comment by dpgrote** [comment]
Yes, this was supposed to fix that test. I'll look into it.

**Pull request merged**
