### PR TITLE
Fix Race condition in GetParticleSlice for BTD

### LINKED ISSUE #1095: Back transformed diagnostic with particles out of box
Hi all,

I decided to open this issue to keep a record of it and of the tests done for it.

I had 2 2D runs in the boosted frame with the option to store back transformed diagnostics.
One using the PSATD+Galilean and the other FDTD methods.
Although the results made sense in the plotfiles (i.e. in the boosted frame), there were particles (just very few) with positions that did not fit inside the simulation box in the snapshots (lab frame).

The plots below illustrate this issue for those runs, showing the propagation direction position of particles in two consecutive snapshots (from top to bottom rows). Left column PSATD, right one is for the FDTD run.

image

As we discussed in the WarpX meeting, this issue could result from the diagnostics being done after the particle push, but before the redistribution (were particles outside the boundaries are excluded).

The boundaries for this case were:
```vim
geometry.prob_lo = -0.000242 -0.000161
geometry.prob_hi =  0.000242  0.0
```

@RevathiJambunathan  has been helping me out with this issue and next I will post here the results of testing her branch.

Here are the input and bash script of the run with PSATD prepared for Summit @ OLCF GPUs.
[inputs2d.txt](https://github.com/ECP-WarpX/WarpX/files/4787598/inputs2d.txt)
[script.txt](https://github.com/ECP-WarpX/WarpX/files/4787599/script.txt)

Cheers,
Diana

### PR DESCRIPTION
**Pull request by RevathiJambunathan**
This PR fixes a race condition in GetParticleSlice called for BTD, and  fixes the out-of-box problems mentioned in Issue #1095

Below is the input file used to reproduce the error and test the fix. Compared to the input file attached in #1095 , `v_galilean = 0. 0. 0.` for the test cases performed in this PR.
[inputs_2d_boostedFrame.txt](https://github.com/ECP-WarpX/WarpX/files/4802467/inputs_2d_boostedFrame.txt)

For a 2D PSATD simulation on the development branch, the back-transformed position was out of the box and the velocities were not gaussian in the first snapshot as shown below.
Screenshot from 2020-06-18 21-51-35

After fixing this, the 2D PSATD GPU simulation results in the following lab-frame position and velocity
Screenshot from 2020-06-18 21-51-51

I also got the same results for the following tests using the same input file (attached above in the PR)

- FDTD 2D simulation on the GPU
- FDTD 2D simulation on the CPU
- PSATD 2D simulation on the CPU.

### CODE REVIEW

**Review by LDAmorim — COMMENTED** [review]
Hi @RevathiJambunathan thank you so much for this PR!

**Comment by LDAmorim** [comment]
Could you please post here the different tests you did (with all the inputs we discussed) and results you got before and after this PR?

**Comment by RevathiJambunathan** [comment]
@LDAmorim Thank you for the discussion offline on generating the lab-frame velocities and for the suggestion to document the results here. I performed four 2D simulations
1. psatd_cpu
2. psatd_gpu
3. fdtd_gpu
4. fdtd_cpu
All these simulations produce the same results within machine precision. Please let me know if there is any another test to be performed/included to further verify the modification made in the PR.

**Comment by LDAmorim** [comment]
Hi @RevathiJambunathan ! This is great news. Thank you!

**Review by LDAmorim — APPROVED** [review]
Thanks @RevathiJambunathan !

**Review by ax3l — APPROVED** [review]
Thanks a lot for debugging and testing this! :sparkles:

**Review by RemiLehe — APPROVED** [review]

**Pull request merged**
