### PR TITLE
Avoid an NaN in collision module

### PR DESCRIPTION
**Pull request by Yin-YinjianZhao**
This PR is made for solving the NaNs reported in #2205 .
Because the occurred NaNs in the collision module does not actually affecting anything, a simple `if` is used to avoid NaNs.

### CODE REVIEW

**Comment by Yin-YinjianZhao** [comment]
@EZoni Hi Edoardo, could you please try this PR and see if it gets rid of the NaNs in the collision module you reporeted at #2205 ?
Thanks.

**Comment by EZoni** [comment]
Thank you, Yin! I just tested the PR by running the two CI tests **collisionXZ** and **collisionXYZ** with the additional runtime option `amrex.fpe_trap_invalid=1`, and they pass, so the bug seems to be fixed properly!

**Review by EZoni — APPROVED** [review]

**Comment by EZoni** [comment]
By the way, not sure what happened with the commit history here (30 commits on August 17, 2020 and 3 commits on May 19??), but the git diff seems fine.

**Comment by Yin-YinjianZhao** [comment]
> By the way, not sure what happened with the commit history here (30 commits on August 17, 2020 and 3 commits on May 19??), but the git diff seems fine.

@ax3l Do you know how to get rid of these old commits? I believe I messed up the development branch on my fork.

**Comment by RemiLehe** [comment]
Regarding the commits: it does not really matter ; these commits will get squashed anyway when merging the PR.

**Comment by ax3l** [comment]
Try this, assuming
  git remote -v
shows mainline as our mainline name locally:

git fetch mainline
git rebase mainline/development
git push -f

If things go south, do
  git rebase --abort
and we zoom later (currently at lunch).

**Pull request merged**
