### PR TITLE
Remove calls to WarpX::GetInstance() in PEC class and cleaning

### PR DESCRIPTION
**Pull request by lucafedeli88**
This PR removes calls to `WarpX::GetInstance()` and to other static functions of the WarpX class from `WarpX_PEC.H/cpp`. It also performs a cleaning of the `PEC` class. The changes are summarized below:

### Changes:

- Move `enum struct PatchType` from `WarpX.H` to `WarpXAlgorithmSelection.H`. This allows us to include just the lightweight `WarpXAlgorithmSelection.H` header instead of the huge `WarpX.H` header when we need just  `PatchType`

- Remove calls to `WarpX::GetInstance()` and to other static functions of the WarpX class from `WarpX_PEC.cpp`. Required variables are now passed as parameters.

- Several functions originally in `WarpX_PEC.H` are now inside an unnamed namespace in  `WarpX_PEC.cpp` since they are essentially auxiliary functions used only in that file. This allows us to move a lot of include directives into the `.cpp` file

- The functions `PEC::isAnyBoundaryPEC()` and `PEC::isAnyParticleBoundaryReflecting()` ... are now in an unnamed namespace inside `WarpXFieldBoundaries.cpp`. In order to avoid unnecessary code duplication we actually use the following template functions:

```
    /** Returns true if any field boundary is set to FieldBoundaryType FT, else returns false.*/
    template <FieldBoundaryType FT>
    [[nodiscard]]
    bool isAnyBoundary (const amrex::Vector<FieldBoundaryType>& field_boundary_lo,
        const amrex::Vector<FieldBoundaryType>& field_boundary_hi)
    {
        const auto isFT = [](const auto& b){
            return b == FT;};
        return std::any_of(field_boundary_lo.begin(), field_boundary_lo.end(), isFT) ||
               std::any_of(field_boundary_hi.begin(), field_boundary_hi.end(), isFT);
    }

    /** Returns true if any particle boundary is set to ParticleBoundaryType PT, else returns false.*/
    template <ParticleBoundaryType PT>
    [[nodiscard]]
    bool isAnyBoundary (const amrex::Vector<ParticleBoundaryType>& particle_boundary_lo,
        const amrex::Vector<ParticleBoundaryType>& particle_boundary_hi)
    {
        const auto isPT = [](const auto& b){
            return b == PT;};
        return std::any_of(particle_boundary_lo.begin(), particle_boundary_lo.end(), isPT) ||
               std::any_of(particle_boundary_hi.begin(), particle_boundary_hi.end(), isPT);
    }
```

- `WarpX::field_boundary_lo` and `WarpX::field_boundary_hi` are now `amrex::Vector<FieldBoundaryType>` instead of `amrex::Vector<int>`.

### CODE REVIEW

**Review by ax3l — APPROVED** [review]
Thank you! :tada:

**Comment by ax3l** [comment]
@lucafedeli88 Thank you for the PR, can you please rebase? :)

**Comment by ax3l** [comment]
Oh no, more merge conflicts

**Comment by lucafedeli88** [comment]
@ax3l , I should have fixed the merge conflicts.

In order to avoid code duplication these functions are used inside `WarpXFieldBoundaries.cpp`:

```
    /** Returns true if any field boundary is set to FieldBoundaryType FT, else returns false.*/
    template <FieldBoundaryType FT>
    [[nodiscard]]
    bool isAnyBoundary (const amrex::Vector<FieldBoundaryType>& field_boundary_lo,
        const amrex::Vector<FieldBoundaryType>& field_boundary_hi)
    {
        const auto isFT = [](const auto& b){
            return b == FT;};
        return std::any_of(field_boundary_lo.begin(), field_boundary_lo.end(), isFT) ||
               std::any_of(field_boundary_hi.begin(), field_boundary_hi.end(), isFT);
    }

    /** Returns true if any particle boundary is set to ParticleBoundaryType PT, else returns false.*/
    template <ParticleBoundaryType PT>
    [[nodiscard]]
    bool isAnyBoundary (const amrex::Vector<ParticleBoundaryType>& particle_boundary_lo,
        const amrex::Vector<ParticleBoundaryType>& particle_boundary_hi)
    {
        const auto isPT = [](const auto& b){
            return b == PT;};
        return std::any_of(particle_boundary_lo.begin(), particle_boundary_lo.end(), isPT) ||
               std::any_of(particle_boundary_hi.begin(), particle_boundary_hi.end(), isPT);
    }

```

**Pull request merged**
