### PR TITLE
Automated tests for rigid injection

### PR DESCRIPTION
**Pull request by MaxThevenet**
Propagate a beam rigidly for 20 microns, then let it widen.
Compare beam width with theory.

### CODE REVIEW

**Comment by dpgrote** [comment]
Thanks for this test! I have a couple of general comments.

I would suggest expanding the lf and bf in the input file names to something like labframe and boostedframe for clarity.

Can you add a few sentences (presumably in the analysis files) about what the simulation is of and what is being tested?

This is for 2D. Can the same tests be done in 3D?

**Comment by MaxThevenet** [comment]
@dpgrote thanks for your comments, I updated the PR accordingly.
I will keep the `[WIP]` tag until we are sure these tests work properly (not that they should fail until PR https://github.com/ECP-WarpX/WarpX/pull/272 is merged).

**Comment by MaxThevenet** [comment]
As for the 3D tests, this could be the object of another PR.

This PR is ready for review.

**Comment by MaxThevenet** [comment]
I don't know why the push test fails, but the PR test pass, so I think this is ready for review.

**Pull request merged**
