### PR TITLE
fix types, amrex::Real and amrex::ParticleReal

### PR DESCRIPTION
**Pull request by WeiqunZhang**
Compiling with `PRECISION=[DOUBLE|FLOAT] USE_SINGLE_PRECISION_PARTICLES=[FALSE|TRUE]` has been partially fixed.  It compiles if `Source/Python/WarpXWrappers.cpp` is commented out.  I will leave this to Dave to fix it.

Currently it has a lot of narrowing warnings, and I haven't tried to run to see if single precision actually works.  But since a ton of places have to been touched and it's very unlikely it breaks the default build with double precision, I think we should merge.  Otherwise  the conflicts will be hard to fix.

### CODE REVIEW

**Comment by dpgrote** [comment]
Is there a way at runtime to know which precision is being used? The Python interface needs to know whether the field and particle data are single or double.

**Comment by ax3l** [comment]
Yes, at runtime the value `sizeof(Real)` can be checked (4 bytes or 8).

**Comment by ax3l** [comment]
Shall we merge? :)

**Comment by dpgrote** [comment]
Merging is fine with me, though updating the Python wrapper will be in a separate PR

**Comment by ax3l** [comment]
@WeiqunZhang do you want to add a compile or regression test that runs on single precision, so we can ensure that functionality stays intact?

**Comment by WeiqunZhang** [comment]
That can be done after the python interface is updated.  Right now it doesn't compile in single precision mode (unless I don't include that file.)

**Pull request merged**
