### PR TITLE
AMReX/PICSAR: Weekly Update

### PR DESCRIPTION
**Pull request by ax3l**
Weekly update to latest AMReX.
Weekly update to latest PICSAR (no changes).

```console
./Tools/Release/updateAMReX.py
./Tools/Release/updatePICSAR.py
```

## Notes

- regressions from https://github.com/AMReX-Codes/amrex/pull/3199 https://github.com/AMReX-Codes/amrex/pull/3243
- need fix from https://github.com/AMReX-Codes/amrex/pull/3247

### CODE REVIEW

**Review by WeiqunZhang — APPROVED** [review]

**Comment by ax3l** [comment]
a few checks that raise checksum differences:
- hard_edged_quadrupoles (3D)
```
Benchmark: [lev=0,Ex] 9.882421125782868e-06
Plotfile : [lev=0,Ex] 9.882421146615367e-06
Benchmark: [lev=0,Ey] 1.044026102498192e-05
Plotfile : [lev=0,Ey] 1.044026104671425e-05
Benchmark: [lev=0,Ez] 1.003739698556440e-05
Plotfile : [lev=0,Ez] 1.003739697324731e-05
```
- pml_psatd_dive_divb_cleaning (3D)
```
Benchmark: [lev=0,Bx] 1.482006333945839e-07
Plotfile : [lev=0,Bx] 1.240175732139287e-06
Benchmark: [lev=0,By] 1.482051585061588e-07
Plotfile : [lev=0,By] 1.219308776050087e-06
Benchmark: [lev=0,Bz] 1.495470407235984e-07
Plotfile : [lev=0,Bz] 1.229402125805917e-06
Benchmark: [lev=0,Ex] 1.178979338985698e+01
Plotfile : [lev=0,Ex] 6.142609646226940e+02
Benchmark: [lev=0,Ey] 1.178688476447710e+01
Plotfile : [lev=0,Ey] 6.224773198394323e+02
Benchmark: [lev=0,Ez] 1.177011081446856e+01
Plotfile : [lev=0,Ez] 6.135902829786862e+02
Benchmark: [lev=0,rho] 4.903696256562049e-05
Plotfile : [lev=0,rho] 4.903696525896805e-05
```
- background_mcc_dp_psp (2D)
```
Benchmark: [electrons,particle_momentum_z] 2.810005821001351e-19
Plotfile : [electrons,particle_momentum_z] 2.810005842534688e-19
Benchmark: [electrons,particle_position_y] 9.356698625905589e+02
Plotfile : [electrons,particle_position_y] 9.356698666088197e+02
```
- reduced_diags_single_precision (SP)
also very small stuff...

**Comment by ax3l** [comment]
@WeiqunZhang I don't understand the relatively large changes in `pml_psatd_dive_divb_cleaning`... This test does not even have particles.

**Comment by RemiLehe** [comment]
@ax3l This test does have particles, I think, since the laser is emitted by an antenna made of macroparticles with a prescribed motion.

**Comment by ax3l** [comment]
Oh I forgot again, ok that makes sense (including the rho).

Should we print the fields before and after to see it still makes sense? There is a significantly larger change in the fields for this one, concerning me the antenna might have changed now or the box might be too small of the initialized laser in the test.

**Comment by ax3l** [comment]
Updating once more to include https://github.com/AMReX-Codes/amrex/pull/3248

**Comment by ax3l** [comment]
That test with the larger change in checksum (`pml_psatd_dive_divb_cleaning`) has a couple of warnings
```
* --> [!  ] [Algorithms] [raised once]
*     The chosen current deposition algorithm does not guarantee charge
*     conservation, and no additional current correction algorithm is activated
*     in order to compensate for that. Lack of charge conservation may
*     negatively affect the results of the simulation.
*     @ Raised by: ALL
*
* --> [!  ] [PML] [raised once]
*     Using PSATD together with PML may lead to instabilities if the plasma
*     touches the PML region. It is recommended to leave enough empty space
*     between the plasma boundary and the PML region.
*     @ Raised by: ALL
```

and might be too small for the sim box.

Don't really know what to make of it.
[Untitled.zip](https://github.com/ECP-WarpX/WarpX/files/11209069/Untitled.zip)


@EZoni as main author of the test, what is the expected output it checks? :) https://github.com/ECP-WarpX/WarpX/commits/development/Examples/Tests/pml/inputs_3d

**Comment by ax3l** [comment]
In order to go forward, I would merge w/o the `pml_psatd_dive_divb_cleaning` test being fully understood. We thing the laser antenna is too wide but have not a lot of time to dig deeper into it rn.

**Pull request merged**
