### PR TITLE
Move sensei to new diagnostics

### PR DESCRIPTION
**Pull request by MaxThevenet**
MERGE ONLY AFTER #1038.

Similar to PR #1038, except for Sensei.

@burlen could you check that this is working? I have not tried to compile with Sensei, because it is not installed on my local computer. Actually, I am pretty sure it won't compile because I replaced
```c++
insitu_bridge->update(istep[0], t_new[0],
         dynamic_cast<amrex::AmrMesh*>(const_cast<WarpX*>(this)),
         {&mf_avg}, {varnames})
```
with
```c++

insitu_bridge->update(iteration, time,
         dynamic_cast<amrex::AmrMesh*>(const_cast<WarpX*>(this)),
         {&mf}, {varnames})
```
but `mf_avg` and `mf` do not have the same type.

All changes relevant to Sensei should be in commit https://github.com/ECP-WarpX/WarpX/commit/9f93195a4b24b6f096f11ec6a86413cc8c2aed13

@burlen Several files contain
```c++
#ifdef BL_USE_SENSEI_INSITU
#   include <AMReX_AmrMeshInSituBridge.H>
#endif
```
Is this required, or could we clean that?

### CODE REVIEW

**Comment by burlen** [comment]
@MaxThevenet if types passed into the method call changed it will obviously break. I can try to fix it.

The conditional includes would be needed where the warp specific data adaptors are defined, but probably not elsewhere. I will see what can be removed

**Comment by MaxThevenet** [comment]
Thanks!

**Comment by MaxThevenet** [comment]
@burlen does SENSEI currently works on Cori? If so, I can debug this PR on Cori, but it seems that the information at https://warpx.readthedocs.io/en/latest/visualization/sensei.html?highlight=sensei is outdated. It reads
```sh
module use /usr/common/software/sensei/modulefiles/
module load sensei/2.1.0-libsim-shared
source sensei_config
make -j8
```
Should I use a more recent version than `sensei/2.1.0-libsim-shared`? I tried
```sh
module use /usr/common/software/sensei/modulefiles/
module load sensei/3.1.0-libsim-shared
source sensei_config
make -j8
```
but them there's a compilation error in AMReX
```
Traceback (most recent call last):
  File "../amrex/Tools/F_scripts/dep.py", line 35, in <module>
    import io
  File "/usr/common/software/sensei/visit/2.13.2/linux-x86_64/lib/python/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: No module named _io
```
Note that I am doing this tests on WarpX master. Once this work, I should be able to debug this PR.

**Comment by MaxThevenet** [comment]
(@burlen note that I don't really need to run, I would just check that the code compiles)

**Comment by burlen** [comment]
@MaxThevenet The SENSEI API's changed in version 3.  Over the weekend I got the updates for the  SENSEI 3 into AMReX. Next step is to update the code that is in WarpX.

**Comment by burlen** [comment]
@MaxThevenet I also started a project to make it easier to build on Cori.
https://github.com/SENSEI-insitu/SENSEI_superbuild
so far I have Python working. Of course the warpx data adaptors need to be updated for sensei 3 first.

**Comment by MaxThevenet** [comment]
Thanks for looking into it @burlen!

**Comment by burlen** [comment]
@MaxThevenet One question about the new "WriteFile" API, it passes `Vector<const amrex::MultiFab *>`. I wonder about the const. While modifying the simulation state is generally not a good idea, there might be some cases where it's useful. for instance when using a surrogate model computed on the in situ side. We were talking about that kind of thing in the FARIS proposal.

**Comment by MaxThevenet** [comment]
@burlen If the new type is a problem, we can modify WarpX so that it passes the same type as before there. Basically we have a `amrex::Vector< amrex::MultiFab >`, and we call `WriteToFile(...,GetVecOfConstPtrs(m_mf_output),...)` so `WriteToFile` takes `amrex::Vector<const amrex::MultiFab* >`. 

I think we could modify it so `WriteToFile` takes `m_mf_output` directly. If you agree, I can do this right now.

**Comment by MaxThevenet** [comment]
Let me push 1 commit doing this, and we can revert it if we're not satisfied.

**Comment by MaxThevenet** [comment]
I tried this in commit 2d1dd3f2ec961cf5bb239380f6975601759d7912. Hopefully Sensei could work out-of-the-box now, please let me know.

**Comment by burlen** [comment]
OK, that certainly makes my life easier. But If there is some issue I think I can go the other way too and it will work for the other codes with some minor changes. As far as I know we only have 2 codes to worry about at the moment warpx and one miniapp that we use to test amrex, so we can change the api without too much concern of impacting others.

Another question: Will the cell centered data passed (m_mf_output) have ghost zones?  I know in the old code I had to generate them as I did the interpolation. It is important for cell centered data to have at least 1 layer of ghost zones to produce correct results in most vis operations.

**Comment by MaxThevenet** [comment]
Sounds good, so for this PR let's keep it this way then, and we're free to do some optimization later on, sorry I should have written it this way in the first place.

Looking at https://github.com/ECP-WarpX/WarpX/blob/b75932d3a1439f19d5b6b697c69fbe72cfb60044/Source/Diagnostics/Diagnostics.cpp#L404 I think `m_mf_output` has no guard cells. Is the machinery to add guard cells already implemented? If not, I could try to add 1 layer of guard cells. But I would have to make sure it doesn't break other diagnostics, because now all diagnostics share this MultiFab, so if we can avoid adding these it would be nice.

**Comment by burlen** [comment]
Ah, I see. This is a tricky bit when combining in situ and I/O. I think that usually writing to disk, folks don't include ghost zones because of the extra I/O cost and data is duplicated. With in situ it makes sense to send them, especially if the simulation has them because it enables zero copy exchange of data.

here is the old code that is in master
```
282 void
283 WarpX::UpdateInSitu () const
284 {
285 #if defined(BL_USE_SENSEI_INSITU)
286     WARPX_PROFILE("WarpX::UpdateInSitu()");
287 
288     // Average the fields from the simulation to the cell centers
289     const int ngrow = 1;
290     Vector<std::string> varnames; // Name of the written fields
291     // mf_avg will contain the averaged, cell-centered fields
292     Vector<MultiFab> mf_avg;
293     WarpX::AverageAndPackFields( varnames, mf_avg, ngrow );
294 
295 #   ifdef BL_USE_SENSEI_INSITU
296     if (insitu_bridge->update(istep[0], t_new[0],
297         dynamic_cast<amrex::AmrMesh*>(const_cast<WarpX*>(this)),
298         {&mf_avg}, {varnames}))
299     {
300         amrex::ErrorStream()
301             << "WarpXIO::UpdateInSitu : Failed to update the in situ bridge."
302             << std::endl;
303 
304         amrex::Abort();
305     }
306 #   endif
307 
308 #endif
309 }   
```
I had been explicitly adding them (line 293) as we converted from face or edge centering.

In our renewal proposal we are planning to support direct zero-copy passing of face and edge data, and assuming that those fields have some number of ghost values I think we would be all set when we get that change in assuming we can be passed the raw arrays. With native face and edge centering, if the tool on the receiving end didn't know how to deal with face or edge centering, the conversion could be done on our side easily. But if we have cell centered data without any ghost zones then it is harder because we need communication and exchange operations, that might require inter level exchange of data at corase fine interfaces, and we don't have any of those operations implemented on our side.

I can get what you have working now, but perhaps we should think about the ghost zone issue. I would be surprised if ascent produces correct results for cell centered data (eg iso surfacing) without a layer of ghost zones and I would be surprised if it had an amr aware implementation for generating them. I think it is something that will affect most in situ vis codes, although VisIt may have that capability as far as I know catalyst does not.

**Comment by MaxThevenet** [comment]
@burlen actually the current implementation should be flexible enough: I just added an if statement in commit https://github.com/ECP-WarpX/WarpX/pull/1040/commits/b0ba0b771f600c65cd0ac2d7e5833196b0bc3c9f that should fix the guard cell question. Hopefully, unless I made a typo, everything should work well with this.
Concerning Ascent, we could fix this in another PR.

**Comment by burlen** [comment]
@MaxThevenet thanks! I'll get this working

**Comment by MaxThevenet** [comment]
Sounds good, thanks! So, could we merge this PR or is there more tests required?

**Comment by burlen** [comment]
I will push some changes to you.

**Pull request merged**
