### PR TITLE
Fix particle injection position at restart

### LINKED ISSUE #1438: Issue of Restart: Particle Injection
Here I post my findings for the issue of restart.

I used an input script based on `Examples/Physics_applications/plasma_acceleration/inputs_3d_boost`.
[inputs_3d_boost.txt](https://github.com/ECP-WarpX/WarpX/files/5374560/inputs_3d_boost.txt)

My work flow is as follows.

- Directly run the attached input script, which leads to a simulation without restart.
- Rename the folder `diags` to `diags_no`.
- Modified the input from `max_step = 10` to `max_step = 5`, and run it.
- Modified the input from `max_step = 5` to `max_step = 10`, uncomment `amr.restart = diags/chk00005/`, and run it.
- Rename the folder `diags` to `diags_yes`.
- Run the python script to generate plots (*.png).
[plot.txt](https://github.com/ECP-WarpX/WarpX/files/5374562/plot.txt)
- Use the command `convert -delay 100 fig*.png fig.gif` to generate an animation named `fig.gif`.
fig

The number of particles for the two runs are:
```
Time step, number of particles without restart, with restart
0 588 588
1 980 980
2 1372 1372
3 1764 1764
4 2156 2156
5 2548 3136
6 2940 3528
7 3332 3920
8 3724 4312
9 4116 4704
```
We can see from the 5th time step, the number of particles changes.
Also, in the animation, we can see a shift of the positions of particles.

### PR DESCRIPTION
**Pull request by RevathiJambunathan**
This PR is to fix the issue mentioned in #1438 .
In this PR, similar to the variable `moving_window_x` which is written out in checkpoint and read during restart, 
the `current_injection_position` is also output now in the checkpoint file.

Here is the particle position of two simulations, without and with restart, following the steps mentioned in #1438.
We see that there is a shift at from the 5th timestep when the simulation is restarted.
fig_bug

After the fix in this PR, now the particles that are read in from a restarted simulation have the same injection position as the simulation without restart.

fig_fixed

**A note :**
In the PR, only for checkpoint format the current injection position is output in the `WarpXHeader` file.
When I add it for all formats, i.e., plotfile format, yt breaks since it does not expect an additional data in the WarpXHeader file and the mis-match leads to an error when loading the file using yt. So I just output this information for the checkpoint format.

### CODE REVIEW

**Review by Yin-YinjianZhao — COMMENTED** [review]
Thank you @RevathiJambunathan so much for the fix!

**Review by ax3l — APPROVED** [review]
Thank you @RevathiJambunathan! :rocket: :sparkles:

**Comment by ax3l** [comment]
@atmyers re: reva's note
>  In the PR, only for checkpoint format the current injection position is output in the WarpXHeader file.
When I add it for all formats, i.e., plotfile format, yt breaks since it does not expect an additional data in the WarpXHeader file and the mis-match leads to an error when loading the file using yt. So I just output this information for the checkpoint format.

Good switch, thank you!

Is this problematic that we cannot read checkpoint files in yt or is there a way to add additional information in it without breaking yt?

I am not sure if one can read checkpoints in the current `development` state with `yt` either, so it's probably no biggy to worry about (I am just curious).

**Comment by RevathiJambunathan** [comment]
I am not sure if we ever tried to visualize checkpoint file and if this is needed.
But, just to add to this discussion, here is the error I get when we dont have a switch for the checkpoint-versus-plotfile in the WarpXHeader, and the `current_injection_position` is added to the plotfile/WarpXHeader file.
```
Traceback (most recent call last):
  File "plot.py", line 22, in <module>
    ad_no = ds_no.all_data()
  File "/home/revanathan/Softwares/yt/yt/data_objects/static_output.py", line 1012, in all_data
    self.index
  File "/home/revanathan/Softwares/yt/yt/data_objects/static_output.py", line 509, in index
    self._instantiated_index = self._index_class(
  File "/home/revanathan/Softwares/yt/yt/frontends/boxlib/data_structures.py", line 1480, in __init__
    self.warpx_header = WarpXHeader(self.ds.output_dir + "/WarpXHeader")
  File "/home/revanathan/Softwares/yt/yt/frontends/boxlib/data_structures.py", line 1454, in __init__
    num_boxes = int(f.readline().strip().split()[0][1:])
ValueError: invalid literal for int() with base 10: '.00014999999999999999'
```

**Comment by atmyers** [comment]
What if you add it at the end of the expected entries?

**Comment by RevathiJambunathan** [comment]
@ax3l  and @atmyers ,
May be we can support this information from the yt side, if we add this line in the WarpXHeader class.
https://github.com/yt-project/yt/blob/df752d3707e15580e765de4e662c809bb3c0be9c/yt/frontends/boxlib/data_structures.py#L1424

**Comment by RevathiJambunathan** [comment]
> What if you add it at the end of the expected entries?

Ah. let me try that!!!

**Comment by atmyers** [comment]
We could definitely support this with changes to yt. Even better than adding the new entry would be to switch to some kind of self-describing format (without breaking reading old plotfiles) that would be more robust to read.

**Comment by RevathiJambunathan** [comment]
You mean computing this without writing the information. I tried, but the round-off errors between when the simulation was stopped and when we restart, gives a small shift. But, please let me know if there is a better way to do this. Adding a new entry was just easy to check if this indeed was the problem, and a better way of doing this would be great!

Writing the value at the end of the Header file works even without the switch. I will update the PR to reflect this

**Comment by atmyers** [comment]
What I mean is, currently we write a list of numbers in `WarpXHeader` that yt reads in a certain order and assigns hard-coded meanings to them. It would be better if the `WarpXHeader` file was `yml` or something that had names associated with each piece of data in there. Then yt could read that file and store it in a dictionary. Then adding a new entry in there would be less likely to break. 

But, I am glad writing it at the end works as a work-around!

**Comment by RevathiJambunathan** [comment]
@atmyers Thank you for the suggestion to add to the end of the file in WarpXHeader. 
This commit 5826c94 adds the new info to eof.
And there is no switch for plotfile and checkpoint format anymore :)

**Review by ax3l — APPROVED** [review]

**Review by RemiLehe — APPROVED** [review]

**Comment by RemiLehe** [comment]
Great! Thanks a lot for fixing this @RevathiJambunathan

**Pull request merged**
