### PR TITLE
AMReX/pyAMReX/PICSAR: Weekly Update

### PR DESCRIPTION
**Pull request by ax3l**
Weekly update to latest AMReX.
Weekly update to latest pyAMReX (no changes).
Weekly update to latest PICSAR (no changes).

```console
./Tools/Release/updateAMReX.py
./Tools/Release/updatepyAMReX.py
./Tools/Release/updatePICSAR.py
```

### CODE REVIEW

**Comment by lucafedeli88** [comment]
Tests are failing due to a recent change in the `regtest.py` script (https://github.com/AMReX-Codes/regression_testing/blame/c17887e4afabf83a56723d30899e13264439ba8b/regtest.py#L1213).  The new logic checks for files matching the pattern `re.match(f"{test.name}.*_(plt|chk)[0-9]+", pfile))` , and throws an error if no file is found. However, in WarpX tests, we don't always generate such files. In some cases the output consists in just reduced diagnostics, while in others it consists in OpenPMD files.

**Comment by ax3l** [comment]
Thanks, Luca!

@zingale is there a way we could control this via an option?

**Review by roelof-groenewald — COMMENTED** [review]
We should probably get the CI test failures sorted before merging this to make sure all the tests would actually still pass.

**Comment by roelof-groenewald** [comment]
It's interesting that the MacOS build isn't failing in this PR as it is for other PRs.

**Comment by ax3l** [comment]
Might be a half-propagated homebrew update that is still being rolled out.

**Review by roelof-groenewald — APPROVED** [review]
All the tests are passing so we're good to go 🎉

**Pull request merged**
