### PR TITLE
RZ: Add ASSERT for Lower Bound of Radial Coordinate

### LINKED ISSUE #1941: Add safe-guard against negative radial lower bound in RZ mode.
In RZ mode, it seems that the user can accidentally provide a negative value for the lower bound in RZ mode, like this:
```
geometry.prob_lo     =  -100.e-6   0.e-6
```
In this case, the code will run without any warning, but will generate incorrect result. We should probably add a safe-guard against this (e.g. an `amrex::Assert`)

### PR DESCRIPTION
**Pull request by EZoni**
Fix #1941 by adding an `AMREX_ALWAYS_ASSERT_WITH_MESSAGE` to check that the lower bound of the radial coordinate in RZ geometry (the first component of `geometry.prob_lo` in the input file) is non-negative.

### CODE REVIEW

**Comment by dpgrote** [comment]
This is a good idea. Another change that could be made is to add an assert that the lower bound be exactly 0 when using RZ with PSATD.

**Comment by EZoni** [comment]
Thank you, @dpgrote. I can add that. Why is there a difference between FDTD and PSATD in terms of the values of `r_min` permitted?

**Comment by dpgrote** [comment]
With the spectral solver, the Hankel transforms that are used only make sense with `r_min` == 0.

**Review by dpgrote — APPROVED** [review]
Thanks, this looks good to me.

**Pull request merged**
