### PR TITLE
PushP now uses FIeldGather

### PR DESCRIPTION
**Pull request by dpgrote**
Here it is. I tested with Langmuir/inputs.multi.rt and it passed.

### CODE REVIEW

**Comment by dpgrote** [comment]
Done

**Comment by dpgrote** [comment]
BTW, when I fix the RZ code, should I completely remove warpx_geteb_energy_conserving?

**Comment by MaxThevenet** [comment]
Yes, I think so! You are welcome to do it, or I can do it in a separate PR if you prefer, after RZ fix is merged.

**Comment by dpgrote** [comment]
Note that once warpx_geteb_energy_conserving and DepositCurrentFortran are removed, the change can be made getting rid of GetPosition since the the c++ routines can operate on the AoS. Though how much will that affect performance on the CPU? Does that matter anymore?

**Comment by MaxThevenet** [comment]
We suspect getting rid of `GetPosition`s (and `m_xp` vectors etc.) should accelerate both CPU and GPU codes, but I think we'll really know when we try. 
And performance on CPU are always welcome, but GPU remains the priority.

**Pull request merged**
