### PR TITLE
Fix NVCC Regression in Parser

### PR DESCRIPTION
**Pull request by ax3l**
Fix a regression with the recompilation of the parser that shows up with NVCC and GNUmake on Summit.

Follow-up to #1448
Similar to #1078

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
We probably will forget about it next time.  Maybe we should add make file rule to remove the line and rename the files.  If you don't mind, I can do it and push to your PR.

**Comment by ax3l** [comment]
Sounds great! Have to head off for groceries, feel free to push :)
Thanks!

**Comment by WeiqunZhang** [comment]
Both `bison` and `flex` have option to not printing `#line`.  The difference between cmake and gnumake systems is gnumake uses nvcc to do link.

**Comment by WeiqunZhang** [comment]
Most of the changes come from I am using different versions of bison and flex than @lucafedeli88.

**Review by WeiqunZhang — APPROVED** [review]

**Comment by WeiqunZhang** [comment]
It now compiles on both summit and my local machine.

**Comment by ax3l** [comment]
Thank you! :sparkles:

**Pull request merged**
