### PR TITLE
Adding additional check in addPlasma and addPlasmaFlux to respect the…

### PR DESCRIPTION
**Pull request by clarkse**
… random_theta flag, otherwise acts deterministically.

When generating benchmarks on Ubuntu 22.04 LTS in WSL, the random number generator does not generate the same numbers as in the Azure pipeline.  If using deterministic particle locations (e.g. a gridded layout) then in RZ it would be expected to have deterministic theta locations that do not rely on the random number generator package.  These cahnges in addPlasma and addPlasmaFlux would respect the <species>.random_theta flag and lay particles down deterministically.

### CODE REVIEW

**Review by ax3l — APPROVED** [review]
This LGTM, but I'll let @RemiLehe have the last look :)

**Comment by EZoni** [comment]
Just linking related issue #2132.

**Comment by EZoni** [comment]
@dpgrote
This PR looks good to me and I would be in favor of merging it.
Do you approve or do you see any issues with the code changes?
I could take care of fixing the CI failures and proceed with the merge.

**Comment by dpgrote** [comment]
@EZoni This PR looks good to me and I don't see any reason not to merge.

**Comment by EZoni** [comment]
Just copying here a comment I posted on Slack.

Even though the code looks good to me, I'm not sure I understand some of the benchmark changes reported on Azure.

For example, these are the benchmark changes for the test `Langmuir_multi_rz_psatd`:
```
Benchmark: [electrons,particle_momentum_x] 1.273602590274234e-20
Plotfile : [electrons,particle_momentum_x] 3.502576717735575e-36
Absolute error: 1.27e-20
Relative error: 1.00e+00
ERROR: Benchmark and plotfile checksum have different value for key [electrons,particle_momentum_y]
Benchmark: [electrons,particle_momentum_y] 1.267821665413735e-20
Plotfile : [electrons,particle_momentum_y] 1.995710600103566e-20
Absolute error: 7.28e-21
Relative error: 5.74e-01
ERROR: Benchmark and plotfile checksum have different value for key [electrons,particle_theta]
Benchmark: [electrons,particle_theta] 9.250629869360024e+04
Plotfile : [electrons,particle_theta] 9.248848772168353e+04
Absolute error: 1.78e+01
Relative error: 1.93e-04
ERROR: Benchmark and plotfile checksum have different value for key [ions,particle_momentum_x]
Benchmark: [ions,particle_momentum_x] 9.804388406594028e-22
Plotfile : [ions,particle_momentum_x] 2.400004392265497e-36
Absolute error: 9.80e-22
Relative error: 1.00e+00
ERROR: Benchmark and plotfile checksum have different value for key [ions,particle_momentum_y]
Benchmark: [ions,particle_momentum_y] 9.844558949583015e-22
Plotfile : [ions,particle_momentum_y] 1.542172086061871e-21
Absolute error: 5.58e-22
Relative error: 5.67e-01
ERROR: Benchmark and plotfile checksum have different value for key [ions,particle_theta]
Benchmark: [ions,particle_theta] 9.208914050622111e+04
Plotfile : [ions,particle_theta] 9.248848772168353e+04
Absolute error: 3.99e+02
Relative error: 4.34e-03
```
While I do expect benchmark changes in this test, due to the fact that the code now does something different than before, I'm not sure I fully understand why the discrepancy on `particle_momentum_x` specifically is so much larger than the errors on the other quantities.

If other developers familiar with the RZ code, e.g., @dpgrote or @RemiLehe, feel like this is expected and/or understood, I can go ahead and reset all benchmarks that need to be reset, most of which exhibit a behavior similar to the one reported above.

**Review by EZoni — APPROVED** [review]

**Pull request merged**
