### PR TITLE
Clang-Tidy: readability-isolate-declaration

### PR DESCRIPTION
**Pull request by WeiqunZhang**

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
I am actually not sure we should use this check. It seems unnecessary. I did this PR only because it could be fixed automatically by clang-tidy. So if we agree, we could close this PR.

**Comment by ax3l** [comment]
Thanks for the details. Yeah, it think it's ok to have some compact declarations here and there. Did this fix a bug?

**Comment by WeiqunZhang** [comment]
No, there were no bugs.

**Comment by WeiqunZhang** [comment]
Will not use this check.

**Pull request closed without merging**
