### PR TITLE
Fix spelling typos

### PR DESCRIPTION
**Pull request by mrowan137**
This PR fixes spelling typos in documentation.

### CODE REVIEW

**Comment by dpgrote** [comment]
Hi @mrowan137 While you are fixing typos, I noticed in parameters.rst the description of warpx.E_ext_grid_init_style mentions "magnetic" which should instead be "electric" (line 952).

**Comment by mrowan137** [comment]
Thanks @dpgrote I corrected the magnetic typo at line 952 of parameters.rst.

**Review by lucafedeli88 — APPROVED** [review]
Thanks for these fixes!

**Comment by EZoni** [comment]
Hi Michael, I just restarted the PSATD jobs on CI, which seemed to have failed due to some time-out issue that occurred also on other PRs yesterday (including a PR of mine, which is why I noticed the problem in the first place). Hopefully it will work fine this time. Thanks a lot for the PR, it's great to have the documentation fixed and improved.

**Review by ax3l — APPROVED** [review]
Thank you for carefully checking and fixing the docs! :sparkles:

**Pull request merged**
