### PR TITLE
[Mini-PR] Initialising the size BaseFab on Device

### PR DESCRIPTION
**Pull request by lgiacome**
As discussed offline we try to switch from `borrowing_z.size.setVal<amrex::RunOn::Host>(0)` to `borrowing_z.size.setVal<amrex::RunOn::Device>(0)`

### CODE REVIEW

**Comment by ax3l** [comment]
The `ionization_boost` test seems to crash at runtime at the moment.
Since this example uses CKC:
  https://github.com/ECP-WarpX/WarpX/blob/5685b012866ef63eb77783e1d1fc16532da1a04d/Examples/Modules/ionization/inputs_2d_bf_rt#L13

maybe rebasing (since #2254 was merged now) can help already.

**Comment by lgiacome** [comment]
@ax3l thanks for the suggestion. It passes all the tests now :)

**Review by ax3l — APPROVED** [review]

**Comment by ax3l** [comment]
LGTM - @lgiacome did you do a runtime test on an actual NVIDIA GPU? Our CI runs on CPU.

**Comment by lgiacome** [comment]
@ax3l 
> LGTM - @lgiacome did you do a runtime test on an actual NVIDIA GPU? Our CI runs on CPU.

From Slack
> Now I did :slightly_smiling_face: I tried the embedded_boundary_rotated_cube  test, which for sure covers this part of code. It works fine :tada:

**Review by RemiLehe — APPROVED** [review]

**Pull request merged**
