### PR TITLE
Fix python wrapper

### PR DESCRIPTION
**Pull request by dpgrote**
This fixes several issues with the Python interface, specifically with accessing the field and particle data.

For field data, this now allows differing number of guard cells along each axis.

For particles, this fixes the fetching of the particle's z position when using RZ.

### CODE REVIEW

**Comment by ax3l** [comment]
@dpgrote just pinging you to notify that some of the Python tests do not pass yet.

**Review by ax3l — APPROVED** [review]
I'll approve and merge this already since it is needed by people, just because we are a bit low on reviewer power this week.

I have to admit, it's hard for me to quickly see what's going on in the patch besides that is changes the guard growing and some int types that I am not familiar with.

@dpgrote do you want to add a few more in-code documentation steps, especially around the guard logic that sets vars like `ng` and `ngrowvect`?
Would it help to add a few tests/examples that use this functionality?

**Comment by dpgrote** [comment]
@ax3l Thanks for merging! Yes, I can add some code documentation. I'm apparently falling into the bad habit of not providing good documentation.

**Comment by ax3l** [comment]
@dpgrote no worries - just ping-ing you for a potential follow-up PR :)

**Pull request merged**
