### PR TITLE
Allow Neumann domain boundary conditions for the electrostatic potential

### PR DESCRIPTION
**Pull request by roelof-groenewald**
Support for Neumann boundary conditions on the domain boundary has been added for the solution of the electrostatic potential.

Testing of the functionality (with `USE_EB=FALSE`) against a benchmark simulation in Warp shows decent agreement as shown below. The difference between the Warp and WarpX results are likely due to slight differences in the grids and deposition algorithms used. I assert the differences are small enough that the test shows WarpX giving the expected result. The input script for the simulation has been attached as a text file for reference.
no_EB
[PICMI_inputs.txt](https://github.com/ECP-WarpX/WarpX/files/7232434/PICMI_inputs.txt)

### CODE REVIEW

**Comment by roelof-groenewald** [comment]
This PR should be merged after https://github.com/AMReX-Codes/amrex/pull/2371 is merged the AMReX version is updated to include the changes from that PR.

**Comment by ax3l** [comment]
Triggered CI

**Review by RemiLehe — APPROVED** [review]

**Comment by RevathiJambunathan** [comment]
Thank you for this PR @roelof-groenewald .
My comment below is only about documentation.


 For electrostatic solver, it seems as though `none` field boundary option is the same as Neumann Boundary condition. If so, can we also add this to the documentation.
 Currently for RZ, `none` is recommended for r=0, so does this mean that Neumann boundary condition is applied at r=0?

**Comment by roelof-groenewald** [comment]
Thanks for the review @RevathiJambunathan. I've added some documentation like you suggested.
The use of a Neumann boundary condition for `r=0` is actually hard-coded (and pre-dates this PR), so I've stuck with the approach there and added the option to use `none` for other domain boundaries as well. It would be a small change to add `neumann` as an option for PICMI input scripts (similar to how `dirichlet` is currently supported). If you'd like I can do that in a follow-up PR.

**Comment by RemiLehe** [comment]
I merged for now, but feel free to open a corresponding follow-up PR.

**Pull request merged**
