### PR TITLE
Weiqun/dimmacros

### PR DESCRIPTION
**Pull request by WeiqunZhang**
Define macros for selecting 3D/2D/RZ.

### CODE REVIEW

**Comment by dpgrote** [comment]
Is there a reason that you moved the setting of DIM=2 from Make.WarpX to GNUmakefile?

Otherwise this is fine.

**Comment by RemiLehe** [comment]
Thanks @WeiqunZhang 
I think that we also need to remove 
```
DEFINES += -DWARPX_RZ
```
around line 121 in `Make.WarpX`.

And then we would also need to search and replace `WARPX_RZ` by `WARPX_DIM_RZ` throughout the code.

**Comment by WeiqunZhang** [comment]
commit fdf640c9ab41b0907e66f30e06240f655b2369ae
Author: Weiqun Zhang <weiqunzhang@lbl.gov>
Date:   Mon Jul 8 15:51:06 2019 -0700

    To reset DIM to 2 for RZ, we have to do it before including AMReX's make files

**Comment by WeiqunZhang** [comment]
More specifically, `amrex/Tools/GNUMake/Make.defs` does

```ifndef DIM
  $(error DIM must be set)
else
  DIM := $(strip $(DIM))
endif
```

`DIM` is evaluated there immediately to stripe whitespaces.  This is done so that it works even if users set `DIM = 3___`, where `_` means whitespace.

**Comment by dpgrote** [comment]
It was already near the top of Make.WarpX for that reason. My preference would be to keep it in Make.WarpX since it keeps GNUmakefile cleaner and I think less prone to user error.

Re Remi's comment, I can make the changes and do a push to this branch.

**Comment by WeiqunZhang** [comment]
I was doing `make -j4 DIM=3 USE_RZ=TRUE print-DIM` to test it, I got `DIM = 3`.  So I thought the reason for that was the reset was too late.  But that was not actually the reason.  The command line option will always override what's set in file.  I can revert that change.

**Comment by dpgrote** [comment]
I see that this is from Weiqun's repo. When this PR is merged, I can make the change from WARPX_RZ to WARPX_DIM_RZ

**Pull request merged**
