### PR TITLE
CMake: Search rocFFT

### PR DESCRIPTION
**Pull request by ax3l**
Explicitly search for `rocFFT`.
Fix missing object in PSATD targets for HIP.

### CODE REVIEW

**Review by lucafedeli88 — COMMENTED** [review]
Thanks for this PR! I only have one question: shouldn't we compile WarpX with PSATD support when we test compilation with HIP now?

**Comment by ax3l** [comment]
That's a good catch, will push an update!

**Review by lucafedeli88 — DISMISSED** [review]
I think that you just need to add
```
elseif(WarpX_COMPUTE STREQUAL HIP)
    target_sources(WarpX
      PRIVATE
        WrapRocFFT.cpp
    )
```
in `WarpX/Source/FieldSolver/SpectralSolver/CMakeLists.txt` to make the test work.

**Review by lucafedeli88 — APPROVED** [review]
Great! Thanks for this PR!

**Review by EZoni — APPROVED** [review]
I'll merge this, since it's already been reviewed and approved by Luca. Thanks both!

**Pull request merged**
