### PR TITLE
AMReX/PICSAR: Weekly Update

### PR DESCRIPTION
**Pull request by ax3l**
Weekly update to latest AMReX.
Weekly update to latest PICSAR (no changes).

```
./Tools/Release/updateAMReX.py
./Tools/Release/updatePICSAR.py
```

### CODE REVIEW

**Comment by ax3l** [comment]
cc @WeiqunZhang @atmyers it looks like the latest AMReX update produces crashes in:
- 2D: `RigidInjection_BTD`
- 3D: `BTD_ReducedSliceDiag`

and changes checksums in:
- SP: `reduced_diags_single_precision`

**Comment by ax3l** [comment]
@atmyers:
> Will look in the periodic boundary SP changes from last week.

@RevathiJambunathan:
> BTD will check from latest changes

**Comment by ax3l** [comment]
@WeiqunZhang 
> Looks to me the checksum change in SP: reduced_diags_single_precision is probably OK.
> periodicShift: https://github.com/AMReX-Codes/amrex/pull/2679

I will reset the benchmark for this one.

The two crashes we need to still find out.

**Comment by RevathiJambunathan** [comment]
This PR https://github.com/ECP-WarpX/WarpX/pull/2986 will fix the BTD tests

I tested the CI tests locally and it passed.

Thank you @atmyers for your help!

**Pull request merged**
