### PR TITLE
Source subfolders

### PR DESCRIPTION
**Pull request by MaxThevenet**
Here is a first proposition for re-ordering the `WarpX/Source` directory (note that it won't compile, I did not modify the makefile for the moment, and will wait for approval before doing so).
`ls -l warpx/Source` returns:
ls_warpx_source

For the moment, the content of each file has not been modified (which makes it hard to create a subdirectory for field gather, particle pusher etc. because these are member functions of class `WarpXParticleContainer` for example). This can be subject to discussion.

Once we agree on the structure, I can do some changes in the file content for consistency (as an example, `EvolveES` and `EvolveEM` are not treated in the same way).

### CODE REVIEW

**Comment by jlvay** [comment]
Very nice. I concur with Rémi's comments.

**Comment by MaxThevenet** [comment]
Thank you for your suggestions, I followed most of them: 

- `WarpX` was removed from some file names, but not all: I kept it when the file actually contains functions that are member of class `WarpX` (when all declarations are `WarpX::[...]`). I also kept it for very general file names, like `WarpXUtil` and `WarpXConst` because I found it not very informative to have `#include <Util.H>` at the beginning of a file, since `Util.H` could be in AMReX, WarpX or PICSAR equivalently. Any opinion is welcome.
- Some file names were modified, including `WarpXMove.cpp`
- I moved `openbc_f.F90` to `Electrostatic/openbc_poisson_solver.F90`.

The code compiles and we'll see soon if the tests pass.

This PR is ready for review.

**Comment by MaxThevenet** [comment]
@WeiqunZhang @atmyers

**Comment by MaxThevenet** [comment]
Sorry for the spam, I closed this PR by mistake and reopened it just now.
It is ready for review. 
@atmyers @WeiqunZhang I added you as reviewers so that you can have a look before we merge, as this PR changes the hierarchy of the `Source` folder.

**Comment by MaxThevenet** [comment]
I merged PR#57 into this one. It implements the changes mentioned in this thread and offline by @RemiLehe and @jlvay. The structure is
screen shot 2019-02-21 at 1 53 25 pm
A summary of what this PR proposes:

- Split the source files into folders. For the moment, there is only one level or hierarchy (we can add more later easily, but for the moment I think it is simpler that way). Each folder contains a file `Make.package`, similar to what is done in AMReX.
- `WarpX::Evolve` calls `EvolveEM` or `EvolveES`. Previously, `Evolve` and `EvolveEM` were in `WarpXEvolve.cpp`, and `EvolveES` was in `WarpXElectrostatic.cpp`. This PR proposes to put the general function `Evolve` into `WarpX.cpp`, and `EvolveES` and `EvolveEM` in two different files in `Source/Evolve/`.
-  All steps of the electrostatic loop were gathered in the same file. It is now split for consistency with electromagnetic mode.

**Pull request merged**
