### PR TITLE
CMake: 3.20+

### PR DESCRIPTION
**Pull request by ax3l**
We already use this version in ImpactX. The main reason is a severe simplification of CMake CUDA search logic that we can rely on.

X-Ref.:
https://github.com/AMReX-Codes/amrex/blob/2d931f63cb4d611d0d23d694726889647f8a482d/Tools/CMake/AMReXParallelBackends.cmake#L55

### CODE REVIEW

**Comment by ax3l** [comment]
Likely needs https://github.com/AMReX-Codes/amrex/pull/2849

**Comment by RemiLehe** [comment]
@ax3l Would you have time to rebase this PR?

**Comment by ax3l** [comment]
Rebased now :)

**Review by EZoni — APPROVED** [review]
Thank you, @ax3l! Looks good to me.

**Pull request merged**
