### PR TITLE
Reduce time in CI tests

### PR DESCRIPTION
**Pull request by oshapoval**
Reduced time of several CI tests by reducing the resolution:

- test_3d_beam_beam_collision;
- inputs_test_rz_multiJ_psatd.

### CODE REVIEW

**Comment by aeriforme** [comment]
We're waiting to update the checksums, right?
Also, we might need to update the documentation of the beam-beam collision example.

**Comment by ax3l** [comment]
@aeriforme is this good to go from your end or does it need docs updates?

**Review by ax3l — APPROVED** [review]

**Comment by ax3l** [comment]
ping @aeriforme @EZoni

**Comment by EZoni** [comment]
> ping @aeriforme @EZoni

I'm not familiar with the beam-beam collision example, so I'm not sure what would need to be changed in the README/docs of the example, after the changes here. I would wait for more instructions from @aeriforme about this.

**Comment by oshapoval** [comment]
Note: in the input, we already mention the resolution needed for full-scale simulation: nx, ny, nz = 512, 512, 1024.

**Pull request merged**
