### PR TITLE
AMReX/PICSAR: Weekly Update

### PR DESCRIPTION
**Pull request by ax3l**
Weekly update to latest AMReX.
Weekly update to latest PICSAR (no changes).

```
./Tools/Release/updateAMReX.py
./Tools/Release/updatePICSAR.py
```

### CODE REVIEW

**Comment by RemiLehe** [comment]
Hm, it's strange that some of the tests are failing.
Should we discuss this at the next developer meeting?

**Comment by ax3l** [comment]
Yep, will add it for today already.

**Comment by atmyers** [comment]
Note, the tests that fail (a subset of those in #2665) are:

2D: SubcyclingMR, RepellingParticles
3d: PEC_particle

They all do look like roundoff-level difference. A glance through the pull requests merged to AMReX since the last update did not reveal to me what might have caused this...

**Comment by ax3l** [comment]
Thanks Andrew!

Just documenting the change set for this PR:
https://github.com/AMReX-Codes/amrex/compare/60fe729fe2ba65ebffc88c0af18743c254d3992c...9373709e34b23add981551d5446bc4810fd3b688

- Generalized Particle Interpolators: https://github.com/AMReX-Codes/amrex/pull/2475
- Bugfix - do we use this?: https://github.com/AMReX-Codes/amrex/pull/2523
- Bugfix - probably not used in WarpX: https://github.com/AMReX-Codes/amrex/pull/2477
- Bugfix EB `set_eb_data`: https://github.com/AMReX-Codes/amrex/pull/2519 - EB tests seem fine
- Probably not yet used (since for #2665):
  - https://github.com/AMReX-Codes/amrex/pull/2528
  - https://github.com/AMReX-Codes/amrex/pull/2526

Tests affected:
- [cartesian2d] RepellingParticles - slight difference in benchmarks
- [cartesian2d] subcyclingMR - large difference in benchmarks -> particle ordering
- [cartesian3d] PEC_particle - slight difference in benchmarks

**Comment by atmyers** [comment]
Actually, some of the changes to the `particle_cpu` (in `subcyclingMR`) do not make sense and seem wrong to me.

**Comment by ax3l** [comment]
I bisected the AMReX commits with the `RepellingParticles` test now and found that
https://github.com/AMReX-Codes/amrex/pull/2516
is the PR that introduces the changes in the checksum.

Update: Confirmed now with `subcyclingMR` and `PEC_particle`, too.

Maybe really just a change in grid layouts and thus particle order then?

**Comment by ax3l** [comment]
Clarification in https://github.com/AMReX-Codes/amrex/pull/2516#issuecomment-993012560

These three tests only had one grid, but use 2 MPI ranks. This is now splitting them up over both MPI ranks. Will reset tests.

**Review by atmyers — APPROVED** [review]

**Pull request merged**
