### PR TITLE
set INCLUDE_LOCATIONS in make files so that dependency can be properl…

### PR DESCRIPTION
**Pull request by WeiqunZhang**
…y handled by amrex gnu make build system

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
Looks like we only need to change the include line as @MaxThevenet suggested on slack.  Instead of `#include "Deposition/CurrentDeposition.H", do `#include "Particles/Depositon/CurrentDeposition.H".   This will work. But it's not clear how we are going to find all of them easily and prevent this type of things in the future.

**Comment by ax3l** [comment]
Hm, maybe I miss the problem description here.

It's actually checked by CI that such forgotten paths are not slipping in. And documented here: https://warpx.readthedocs.io/en/latest/developers/repo_organization.html#c-includes

**Comment by ax3l** [comment]
Could the problem be the following:
file `Source/Group/A.H` includes `Source/Group/Sub/B.H` as `#include "Sub/B.H"` and the AMReX `mkdep` script does not catch it?

**Comment by WeiqunZhang** [comment]
An alternative is to remove all the VPATH_LOCATIONS except `Src`.  Then it won't compile unless all the path under `Src` is specified.

**Comment by ax3l** [comment]
So we would enforce that people cannot specify relative includes (which are valid in C/C++)? Still better than silently forgetting to recompile.

**Comment by ax3l** [comment]
A hack could also be: Let's pass `VPATH_LOCATIONS` instead of (or combined with) `INCLUDE_LOCATIONS` to `mkdep`.

**Comment by MaxThevenet** [comment]
Is this still WIP? Should we add the [WIP] tag?

**Comment by ax3l** [comment]
Sounds good, @WeiqunZhang is it okay to modify the `VPATH_LOCATIONS`? Would love to keep proper include grouping covered by CI.

**Comment by ax3l** [comment]
Thanks for the update @WeiqunZhang, does https://github.com/AMReX-Codes/amrex/pull/980 fix this?

**Comment by WeiqunZhang** [comment]
No longer relevant.

**Pull request closed without merging**
