### PR TITLE
Replace Fortran Parser with the new Parser

### PR DESCRIPTION
**Pull request by WeiqunZhang**
This pull-request uses the new parser, and the Fortran parser has been removed.  It has passed the tests at https://github.com/WeiqunZhang/WarpXParser/tree/warpx/test using all the functions that can be found in the inputs files in WarpX repo.  In addition, I have tested it with various other functions.  I have also run regression tests.  The results are at https://ccse.lbl.gov/pub/RegressionTesting/WarpX/2019-03-13-003/index.html.  The errors are round-off.

Because the new parser is thread safe, we no longer need to set `WarpX::serialize_ics=true` to disable threading in particle initialization.

### CODE REVIEW

**Comment by RemiLehe** [comment]
@WeiqunZhang Thanks a lot for this PR.
Quick question: Within the `Source/Parser` folder, could you add a `README.md` file that explains the role of each file (my understanding is that some of them - including the GNUMakefile - are only here to re-generate the source code, but are not actually read when compiling WarpX, is that correct?).

**Comment by RemiLehe** [comment]
It looks like the source code defines a new function `setConstant`, but this function is not used in the WarpX code.
@WeiqunZhang Did you mean to use this function?

**Comment by RemiLehe** [comment]
or did you want to do this in a separate PR?

**Comment by WeiqunZhang** [comment]
Yes, I think we should do it in a separate PR, because it will require changes in inputs files.

**Comment by WeiqunZhang** [comment]
I updated the pull-request.  It added support for unary plus sign and fixed a bug.  I have done extensive testing with thousands of expressions with and without OpenMP.
.

**Pull request merged**
