### PR TITLE
AMReX/PICSAR: Weekly Update

### PR DESCRIPTION
**Pull request by ax3l**
Weekly update to latest AMReX.
Weekly update to latest PICSAR (no changes).

```console
./Tools/Release/updateAMReX.py
./Tools/Release/updatePICSAR.py
```

### CODE REVIEW

**Review by WeiqunZhang — APPROVED** [review]

**Comment by ax3l** [comment]
Looks like there are a few regressions in EB. All with
```
0::Assertion `getBDKey() == m_bdkey' failed, file "/tmp/ci/warpx/builddir/_deps/fetchedamrex-src/Src/Base/AMReX_FabArrayBase.cpp", line 2252 !!!
SIGABRT
See Backtrace.0.1 file for details
```

@WeiqunZhang got an idea what this assert could mean for these tests?

- [ ] `Python_magnetostatic_eb_rz CRASHED`
- [ ] `Python_magnetostatic_eb_3d CRASHED`
- [ ] `magnetostatic_eb_3d CRASHED`

**Comment by WeiqunZhang** [comment]
I believe this should be fixed by https://github.com/AMReX-Codes/amrex/pull/3594.

**Comment by ax3l** [comment]
Thank you, PR updated :)

**Comment by ax3l** [comment]
Works, thank you @WeiqunZhang :tada:

**Pull request merged**
