### PR TITLE
Sensei insitu dev

### PR DESCRIPTION
**Pull request by burlen**
integrates sensei into warpx, and some basic documentation in sphinx.

### CODE REVIEW

**Comment by RemiLehe** [comment]
Thanks for this PR @burlen 
It looks like the PR should contain a `sensei.rst` file in the documentation folder. Did you maybe forget to commit it?

**Comment by burlen** [comment]
yes! sorry abut that, I forgot to commit it. I have now added it.

**Comment by burlen** [comment]
@WeiqunZhang SENSEI currently uses non zero integer value to indicate an error. what are the conventions in amrex? is a signed integer a reasonable choice for the new error type?

I almost factored the code for conversions to cell data into it's own function that could be shared by both plot file writing and in situ processing but backed off. I thought it would be worth thinking about in more detail.
Down the road, it might make more sense for these centering conversions to live inside the in situ data adaptor, because other wise every simulation code would need to duplicate the conversion code. what do you think?

The code for cell centered conversion for in situ is almost but not quite duplicated from the plot file coversion. here are the differences

1. we need a layer of ghost cells. I set `ngrow=1`, but there is still some issue with it, and I may need to make more modifications if it's not a bug in the data adaptor.
2. The in situ api takes a different type for the collection of multifabs than the plot file writing api. I was worried about the cost to convert these collections to the type need by our api so just built up the data structure the way we needed it.
3. We support zero copy of  node centered data. those fields could be passed through directly via a zero-copy transfer rather than converted to cell centered. Would that cause a problem for plot file writer?

**Comment by burlen** [comment]
sounds good

**Pull request merged**
