### PR TITLE
Add note on realclean on GPU systems

### PR DESCRIPTION
**Pull request by LDAmorim**
Hi,
This small PR is just to let the users know that to clean the makefile for GPUs requires the use of the extra flag `USE_GPU=TRUE`. Otherwise the code can fail to compile.
Changed 1 file:
- Docs/source/building/summit.rst (to include the note)

Cheers,
Diana

### CODE REVIEW

**Comment by dpgrote** [comment]
What happens when make realclean is done without USE_GPU=TRUE? Is there something that isn't deleted? Could the makefile be modified to fix this instead?

**Comment by LDAmorim** [comment]
Thanks for the question @dpgrote .
From what I understood this is the correct behavior. It is so that if in the same machine we have a compilation of the code for the CPUs and another for GPUs we only erase the makefile for one. But I might have misunderstood this. @MaxThevenet can probably explain this more correctly.

**Comment by LDAmorim** [comment]
Hi all,
It appears that using `make realclean` on Summit is now sufficient and so it is no longer necessary to add the `USE_GPU=TRUE` flag to have a complete restoration of the system makefile. So I will close this issue.

**Comment by LDAmorim** [comment]
Small update:
I still needed to do the extra `make realclean USE_GPU=TRUE` line today to compile with `DIM=2D`.

**Comment by ax3l** [comment]
> It is so that if in the same machine we have a compilation of the code for the CPUs and another for GPUs we only erase the makefile for one.

I don't fully understand the report fully, I think. Is it possible to post the `ls` of the files that should be removed but are not? You mean something stays in `tmp_build_dir/` or elsewhere?

**Pull request closed without merging**
