### PR TITLE
Adding EB multifabs to the Python interface

### PR DESCRIPTION
**Pull request by lgiacome**
This PR adds the possibility to access `m_edge_lengths` and `m_face_areas` data from Python.
This is useful for debugging purposes.

### CODE REVIEW

**Comment by dpgrote** [comment]
Don't forget to add routines to fields.py to create the wrappers for the two new arrays of data.

**Comment by ax3l** [comment]
Please also use the new APIs in a test/example, so it gets covered by CI runs :)
Can be an existing test/example as well.

**Comment by lgiacome** [comment]
> Don't forget to add routines to fields.py to create the wrappers for the two new arrays of data.

This is done

> Please also use the new APIs in a test/example, so it gets covered by CI runs :)
> Can be an existing test/example as well.

Working on a CI test now :)

**Review by ax3l — APPROVED** [review]
Thanks a lot! :tada:

**Pull request merged**
