### PR TITLE
Select the fields that are written in tests

### PR DESCRIPTION
**Pull request by RemiLehe**
In the automated tests, a number of fields are zero by construction, and are therefore dominated by machine-precision noise.
One consequence is that the regression tests will fail with large relative error for these fields, whenever the code changes in such that the machine-precision noise is changed.

One way to avoid this is to prevent the tests scripts from writing these particular fields. This is what this PR does:
- For `Langmuir_x`, `Langmuir_y`, `Langmuir_z`, `Langmuir_2d` all fields are 0 except `E` and `j` in the direction in which the plasma moves.
- For `Langmuir_rz`, the fields `Ey` and `jy` correspond in fact to the azimuthal direction and are therefore 0 (the current test runs with exact cylindrical symmetry). For the same reasons `Bx` and `Bz` are also 0.
- In the laser injection tests, the component `By` should be non-zero but have a very small value (associated with second-order diffraction effects). In practice however, when looking at the plotfiles, this small value seems to be negligible compared to machine precision noise.

### CODE REVIEW

**Comment by dpgrote** [comment]
I understand the need for this, but caution is needed. It would probably still be a good idea to somehow make sure that the fields that are zero are actually zero (or tiny).

**Comment by MaxThevenet** [comment]
I think we forgot to discuss this topic at the last WarpX meeting. This PR will help avoiding recurring false-negative tests, for which we have to check tests one by one almost everyday, losing the advantage of CI.

I am fine with not checking fields that are supposed to be zero (fields in each direction are checked in different tests anyway).

Another option would be to:

- dump all fields in regression tests running everyday
- Dump only non-zero fields in the benchmark

If `fcompare` has the option to only compare fields that are in **both** plotfiles, this would prevent regression tests from failing for machine precision errors, but we could check fields = 0 with a Python script.

**Comment by MaxThevenet** [comment]
@WeiqunZhang will we have to reset the benchmarks after merging this PR?

**Comment by WeiqunZhang** [comment]
Yes, I think so.

**Comment by MaxThevenet** [comment]
I think `Langmuir_2d` analysis fails because the python script `langmuir2d_analysis.py` tries to access `Ez` etc. I'll commit a fix.

**Pull request merged**
