### PR TITLE
Fix Bug with Python Wrappers for F,G

### PR DESCRIPTION
**Pull request by EZoni**
The names of some of these `get_mesh` functions for F and G were not matching: this bug was introduced accidentally in #2460.

### CODE REVIEW

**Comment by EZoni** [comment]
@dpgrote Hi Dave, when I try to access these F and G field data through the new Python wrappers introduced in #2460, I still get errors, despite the bug fix here. Would it be possible for you to also have a look at #2460 just to see if you spot something obvisouly wrong or missing? The backtraces I get from the Python runs are not very clear unfortunately. Thanks in advance!

**Comment by dpgrote** [comment]
@EZoni Can you send me a script to use to test it?

**Comment by EZoni** [comment]
@dpgrote I'll have to implement the same changes in #2403 (temporarily) and then I could share a script to try accessing F and G.

**Review by dpgrote — APPROVED** [review]
This looks good - fixing the names is correct.

**Pull request merged**
