### PR TITLE
reimplementation of interpolation and removal of Fortran from gnu make

### PR DESCRIPTION
**Pull request by WeiqunZhang**
There are three main changes.

* Some obsolete functions have been removed.

* The interpolation of coarse patch data onto to fine patch grids has been reimplemented in C++.  The new functions do not preserve divergence free for B fields, since this is unnecessary.

* The GNU make system no longer needs a Fortran compiler.

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
@ax3l You can remove Fortran from cmake either in this PR or a new PR after this is merged.

**Review by RemiLehe — APPROVED** [review]

**Review by ax3l — APPROVED** [review]
Thanks @WeiqunZhang, this is great!
Since CI already passed I will merge this and open a follow-up :)

**Comment by ax3l** [comment]
Wow, I think we just saved 10min compile time on Travis-CI, yay!!
Update: ugh, just a hick-up in my baseline. ~1min saved still :)

**Comment by MaxThevenet** [comment]
@EZoni Could some of the functions you implemented be used for this interpolation?

**Comment by EZoni** [comment]
> @EZoni Could some of the functions you implemented be used for this interpolation?

I think that the functions here deal with interpolation from coarse patch to fine patch, while the functions that I implemented previously, in the `CoarsenIO` and `CoarsenMR` namespaces, deal with interpolation from fine patch to coarse patch. The functions here could be maybe re-designed in a way similar to the coarsening functions, regarding their generality with respect to the input and output index type (staggering). However, when this PR was discussed offline at the last WarpX development meeting the priority seemed to be to get rid of residual Fortran only.

**Comment by MaxThevenet** [comment]
Sounds good, thanks for the clarification.

**Pull request merged**
