### PR TITLE
[WIP] Convert divE and divB to c++

### PR DESCRIPTION
**Pull request by dpgrote**
This implements the divE and divB routines in c++. I followed the pattern used with warpx_push_ex etc, putting the kernel of the loops in separate routines (in the new filed WarpX_FDTD.H). This new file is intended to eventually include all of the kernels needed for the FDTD routines.

I checked the 3D version and it seems to run Ok. I'll next test the 2D and RZ.

Note for now, I put in divides by dx. I'll replace with precalculated 1/dx.

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
I have a few comments.

We need to change `for (MFIter mfi(divB, true);` to `for `(MFIter mfi(divB, TilingIfNotGPU()` to turn off tiling for GPU, otherwise there will not be enough work for GPU.

`std::array<Real,3> dx` is not GPU friendly.  We can pass three scalars to the kernel.  If we do that, we could also pass 1/dx instead.

We can replace `GetInstance().Geom(0).ProbLo(0)` with `Geom(0).ProbLo(0)` because it is inside a WarpX member function.

**Comment by dpgrote** [comment]
@WeiqunZhang I'm getting the error below. What is going wrong?

./Source/WarpX.cpp: In static member function 'static void WarpX::ComputeDivE(amrex::MultiFab&, int, const std::array<const amrex::MultiFab*, 3>&, const std::array<double, 3>&)':
./Source/WarpX.cpp:994:33: error: cannot call member function 'amrex::Geometry& amrex::AmrMesh::Geom(int)' without object
         const Real rmin = Geom(0).ProbLo(0);
                                 ^
./Source/WarpX.cpp: In static member function 'static void WarpX::ComputeDivE(amrex::MultiFab&, int, const std::array<const amrex::MultiFab*, 3>&, const std::array<double, 3>&, int)':
./Source/WarpX.cpp:1028:33: error: cannot call member function 'amrex::Geometry& amrex::AmrMesh::Geom(int)' without object
         const Real rmin = Geom(0).ProbLo(0);

**Comment by WeiqunZhang** [comment]
Sorry.  I didn't notice those are static functions of WarpX.  You can either make them non-static or change back to you previous way of getting Geometry objects.

**Comment by dpgrote** [comment]
I added back the GetInstance. Is there a reason that these routines were made static originally?

With this latest commit, it is now ready to merge. I ran tests comparing the old and new versions of the code and they give the same results out to round off. This also implements the divB for the RZ version.

**Pull request merged**
