### PR TITLE
Set EB (electrostatic) potential with a function of space and time

### PR DESCRIPTION
**Pull request by roelof-groenewald**
The embedded boundary functionality for the electrostatic solver has been extended to allow a function of space and time to be used to set the EB potential.
In the example below the embedded boundary was defined (through PICMI) with:
```
embedded_boundary = picmi.EmbeddedBoundary(
    implicit_function="-(x**2+z**2-radius**2)",
    potential="if(x>0,1.0,-2.0)",
    radius = 0.3
)
```
potential

### CODE REVIEW

**Comment by roelof-groenewald** [comment]
This PR requires a change to AMReX. In `AMReX_MLEBNodeFDLaplacian.H` the template `MLEBNodeFDLaplacian::setEBDirichlet` returns `Real(0.)`, but the `setEBDirichlet` function is defined as `void`. Therefore, I believe line 140 of that file should be removed.

**Review by dpgrote — APPROVED** [review]
This looks good to me.

**Comment by WeiqunZhang** [comment]
If the potential is a constant in space, the old approach without using a Parser is more efficient.  So should we keep the original approach for the constant potential case?

**Comment by WeiqunZhang** [comment]
We can use `Parser::symbols()` to find out if it depends on `x` etc.

**Review by RemiLehe — APPROVED** [review]

**Pull request merged**
