### PR TITLE
Cori Haswell/KNL: Update PSATD+RZ Instructions

### PR DESCRIPTION
**Pull request by RemiLehe**
Add instructions on how to compile BLAS++/LAPACK++ on Cori KNL & Haswell.

- [x] runtime tests

### CODE REVIEW

**Review by ax3l — APPROVED** [review]

**Comment by ax3l** [comment]
Using Cray's libsci for BLAS & LAPACK routines in BLAS++/LAPACK++ seems to destroy the stack.
I see in tests issues such as:
```
0::Assertion `isAnyBoundaryPML() == false' failed, file "/global/homes/a/ahuebl/src/warpx/Source/WarpX.cpp", line 809, Msg: "PML are not implemented in RZ geometry; please set a different boundary condition using boundary.field_lo and boundary.field_hi." !!!
```
as soon as it's linked.

Will try to use the system-level OpenBLAS instead that lingers in `/usr` and hope/test it works with KNL and Haswell...

**Comment by ax3l** [comment]
Hm, I also see this without PSATD on :scream:

**Comment by ax3l** [comment]
Problem identified: #2508

**Comment by RemiLehe** [comment]
Since the problem seems independent of the proposed changes here, I will merge this.

**Pull request merged**
