### PR TITLE
AMReX/PICSAR: Weekly Update

### PR DESCRIPTION
**Pull request by ax3l**
Weekly update to latest AMReX.
Weekly update to latest PICSAR (no changes).

```console
./Tools/Release/updateAMReX.py
./Tools/Release/updatePICSAR.py
```

## Fix Intel CI: dpcpp -> icpx

Intel has deprecated `dpcpp`.  We are supposed to use `icpx -fsycl` now for SYCL code.

### CODE REVIEW

**Review by RemiLehe — APPROVED** [review]

**Comment by WeiqunZhang** [comment]
@ax3l  Could you merge the commit in #3581 into this?  Could you also update amrex commit to `c2decc83820a5457fc64aabfa2ebd1d787e4744f` so that the Intel CI can pass?  After that you can close #3581.

(Edited: I meant to ping the author @ax3l.)

**Comment by ax3l** [comment]
Thanks - updated AMReX once more and will merge the other PR separately.

**Comment by ax3l** [comment]
I'll update AMReX once more once we have
https://github.com/ECP-WarpX/WarpX/pull/3581#issuecomment-1362165711
fixed :)

**Review by WeiqunZhang — APPROVED** [review]

**Comment by ax3l** [comment]
New issue we see with GCC 7.5.0 for the Ascent build (CPU, no acceleration):
```
/__w/WarpX/WarpX/build/_deps/fetchedamrex-src/Src/LinearSolvers/MLMG/AMReX_MLMG.cpp:11:16:   required from here
/__w/WarpX/WarpX/build/_deps/fetchedamrex-src/Src/LinearSolvers/MLMG/AMReX_MLCGSolver.H:408:31: error: 'MPI_Comm amrex::MLLinOpT<MF>::BottomCommunicator() const [with MF = amrex::MultiFab; MPI_Comm = int]' is protected within this context
         ParallelAllReduce::Max(result, Lp.BottomCommunicator());
         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Will merge for now.

**Pull request merged**
