### PR TITLE
Allocate fewer `rho` components for ES, MS, hybrid-PIC solvers

### LINKED ISSUE #4035: Only allocates `rho_ncomps = ncomps` instead of `rho_ncomps = 2*ncomps` for ES, MS and hybrid-PIC solvers
We could do a follow-up PR that only allocates `rho_ncomps = ncomps` instead of `rho_ncomps = 2*ncomps` in these cases. (See a few lines below.)

_Originally posted by @RemiLehe in https://github.com/ECP-WarpX/WarpX/pull/3665#discussion_r1227202244_

### PR DESCRIPTION
**Pull request by RemiLehe**
This fixes https://github.com/ECP-WarpX/WarpX/issues/4035.

### CODE REVIEW

**Comment by roelof-groenewald** [comment]
@RemiLehe I believe the tests currently failing can be fixed by the following alterations:
in `Examples/Physics_applications/capacitive_discharge/PICMI_inputs_2d.py` line 167
    `self.rho_data = self.rho_wrapper[Ellipsis][:,:,0]` -> `self.rho_data = self.rho_wrapper[Ellipsis]`
in `Examples/Physics_applications/capacitive_discharge/PICMI_inputs_1d.py` line 100
    `self.rho_data = fields.RhoFPWrapper(0, False)[...][:,0]` -> `self.rho_data = fields.RhoFPWrapper(0, False)[...]`

I ran the 2d test locally to confirm that the change allows the test to pass.

**Comment by RemiLehe** [comment]
@roelof-groenewald Thanks a lot for these suggestions! I modified the PR accordingly.

**Comment by roelof-groenewald** [comment]
> Thanks a lot for these suggestions! I modified the PR accordingly.

Sorry, I see I missed another required change in the 1d test, line 341:
   `rho_data = self.rho_wrapper[...][:,0]` -> `rho_data = self.rho_wrapper[...]`

**Comment by EZoni** [comment]
@RemiLehe @roelof-groenewald 
Since my review was requested here, I went ahead and fixed the merge conflicts with `development` as well as implemented the last missing fix pointed out by Roelof in the PICMI script for the 1D CI test.

**Review by roelof-groenewald — APPROVED** [review]
Thanks @RemiLehe for these changes and @EZoni for fixing the part I missed on the 1d CI test. I think this is good to go!

**Pull request merged**
