### PR TITLE
Python: Single Precision Support

### PR DESCRIPTION
**Pull request by dpgrote**
Allows single precision in Python interface

BTW, when I compile with float, I see a number of warnings about narrowing from double to float, some coming from amrex. They are mostly related to calls to Random. Should they be fixed, presumably with an explicit type conversion?

### CODE REVIEW

**Comment by atmyers** [comment]
Hi Dave,

Axel raised this issue on the AMReX Github - I think they should be fixed on the latest development branch.

**Comment by ax3l** [comment]
Hi Dave, I fixed a tiny bit of Python already in #422 (basically it compiles now). Shall we merge my PR or yours first?

**Comment by dpgrote** [comment]
Either can be merged first. I've made some of the same changes. This will need to be a hand merge to clean up the conflicts.

**Comment by ax3l** [comment]
Yes, I just changed a few throwing parameters that you refreshed the same way.

**Comment by ax3l** [comment]
I'll merge this already :)

**Pull request merged**
