### PR TITLE
RZ + single precision fix

### PR DESCRIPTION
**Pull request by mrowan137**
This fixes a build error with RZ in single precision (`make -j USE_RZ=TRUE PRECISION=FLOAT USE_SINGLE_PRECISION_PARTICLES=TRUE`; see issue #1415).

### CODE REVIEW

**Comment by dpgrote** [comment]
No problem. We've made the same fixes. Either PR can be used.

**Review by dpgrote — APPROVED** [review]
Looks good.

Presumably single precision Complex allows passing in double quantities and does the truncation there.

**Review by Yin-YinjianZhao — APPROVED** [review]

**Review by lucafedeli88 — APPROVED** [review]
Thanks for this PR!

**Comment by WeiqunZhang** [comment]
I pushed a change to fix cufft for SP RZ.

**Review by RemiLehe — APPROVED** [review]

**Pull request merged**
