### PR TITLE
Added stub for current correction in RZ spectral solver

### PR DESCRIPTION
**Pull request by dpgrote**
This stub is needed so that the RZ spectral solver can be compiled. A recently merge PR, #675, added calls to a current correction routine on the spectral solver instance. That routine was not defined in the RZ spectral solver and so the code could not be compiled. This fixes the issue, causing the code to abort if current correction is turned on.

Note that current correction is being implemented in RZ but is not ready yet.

### CODE REVIEW

**Comment by EZoni** [comment]
@dpgrote Thanks for spotting the bug.

**@everyone** Would it be useful (or is it planned) to add an automated test of the RZ spectral solver? This would add to the Travis CI suite a test that compiles WarpX with USE_RZ=TRUE and USE_PSATD=TRUE, which, I think, would help spot these kinds of bugs more easily.

**Comment by dpgrote** [comment]
@EZoni Yes, it is planned to include a CI test for RZ spectral.

**Review by EZoni — APPROVED** [review]
Thank you for this bug fix! I just suggest minor modifications to the Doxigen docs that were copied from the previous implementation.

This PR seems ready to be merged. You could maybe merge the master branch again or simply push a void commit in order to trigger the Travis build once more (the last one probably failed due to a stalled build).

**Comment by dpgrote** [comment]
Thanks for the comments @EZoni. I added them all in a commit and pushed it up. I also merge in master. Hopefully all of the tests will pass now.

**Review by MaxThevenet — APPROVED** [review]

**Pull request merged**
